version: 2

project_name: gorse

builds:
  - id: gorse-bench
    main: ./cmd/gorse-bench
    binary: gorse-bench
    env:
      - CGO_ENABLED=0
    targets: &linux_windows_targets
      - linux_amd64
      - linux_arm64
      - linux_loong64
      - linux_riscv64
      - windows_amd64
      - windows_arm64
    ldflags: &ldflags
      - >-
        -X 'github.com/gorse-io/gorse/cmd/version.Version={{ .Version }}'
        -X 'github.com/gorse-io/gorse/cmd/version.GitCommit={{ .Commit }}'
        -X 'github.com/gorse-io/gorse/cmd/version.BuildTime={{ .Date }}'
  - id: gorse-cli
    main: ./cmd/gorse-cli
    binary: gorse-cli
    env:
      - CGO_ENABLED=0
    targets: *linux_windows_targets
    ldflags: *ldflags
  - id: gorse-in-one
    main: ./cmd/gorse-in-one
    binary: gorse-in-one
    env:
      - CGO_ENABLED=0
    targets: *linux_windows_targets
    ldflags: *ldflags
  - id: gorse-master
    main: ./cmd/gorse-master
    binary: gorse-master
    env:
      - CGO_ENABLED=0
    targets: *linux_windows_targets
    ldflags: *ldflags
  - id: gorse-server
    main: ./cmd/gorse-server
    binary: gorse-server
    env:
      - CGO_ENABLED=0
    targets: *linux_windows_targets
    ldflags: *ldflags
  - id: gorse-worker
    main: ./cmd/gorse-worker
    binary: gorse-worker
    env:
      - CGO_ENABLED=0
    targets: *linux_windows_targets
    ldflags: *ldflags

archives:
  - id: gorse
    ids: &all_builds
      - gorse-bench
      - gorse-cli
      - gorse-in-one
      - gorse-master
      - gorse-server
      - gorse-worker
    formats:
      - zip
    name_template: "gorse_{{ .Os }}_{{ .Arch }}"
    files:
      - none*
  - id: gorse-cli
    ids:
      - gorse-cli
    formats:
      - binary
    name_template: "gorse-cli_{{ .Os }}_{{ .Arch }}"

checksum:
  disable: true

release:
  replace_existing_artifacts: true
  mode: keep-existing
