//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   20.1.8 (0ubuntu4)
// 	objdump 2.45
// flags: -mavx -mavx512f -mavx512bw -O3
// source: src/bfloats_avx512.c

TEXT ·_mm512_euclidean_bf16(SB), $8-24
	MOVQ a+0(FP), DI
	MOVQ b+8(FP), SI
	MOVQ n+16(FP), DX
	BYTE $0x55                             // pushq	%rbp
	WORD $0x8948; BYTE $0xe5               // movq	%rsp, %rbp
	LONG $0xf8e48348                       // andq	$-8, %rsp
	LONG $0x0f4a8d48                       // leaq	15(%rdx), %rcx
	WORD $0x8548; BYTE $0xd2               // testq	%rdx, %rdx
	LONG $0xca490f48                       // cmovnsq	%rdx, %rcx
	WORD $0x8949; BYTE $0xc8               // movq	%rcx, %r8
	LONG $0xf0e08349                       // andq	$-16, %r8
	WORD $0x8948; BYTE $0xd0               // movq	%rdx, %rax
	WORD $0x294c; BYTE $0xc0               // subq	%r8, %rax
	LONG $0xc057f8c5                       // vxorps	%xmm0, %xmm0, %xmm0
	LONG $0x10fa8348                       // cmpq	$16, %rdx
	JL   LBB0_6
	LONG $0x04f9c148                       // sarq	$4, %rcx
	QUAD $0xfffffffffff0b849; WORD $0x7fff // movabsq	$9223372036854775792, %r8       # imm = 0x7FFFFFFFFFFFFFF0
	WORD $0x214c; BYTE $0xc2               // andq	%r8, %rdx
	LONG $0x10fa8348                       // cmpq	$16, %rdx
	JNE  LBB0_12
	WORD $0x8948; BYTE $0xfa               // movq	%rdi, %rdx
	WORD $0x8949; BYTE $0xf0               // movq	%rsi, %r8
	JMP  LBB0_3

LBB0_12:
	QUAD $0xfffffffffffeb949; WORD $0x07ff // movabsq	$576460752303423486, %r9        # imm = 0x7FFFFFFFFFFFFFE
	WORD $0x2149; BYTE $0xc9               // andq	%rcx, %r9
	WORD $0x8948; BYTE $0xfa               // movq	%rdi, %rdx
	WORD $0x8949; BYTE $0xf0               // movq	%rsi, %r8

LBB0_13:
	LONG $0x487df262; WORD $0x0a33             // vpmovzxwd	(%rdx), %zmm1           # zmm1 = mem[0],zero,mem[1],zero,mem[2],zero,mem[3],zero,mem[4],zero,mem[5],zero,mem[6],zero,mem[7],zero,mem[8],zero,mem[9],zero,mem[10],zero,mem[11],zero,mem[12],zero,mem[13],zero,mem[14],zero,mem[15],zero
	LONG $0x4875f162; WORD $0xf172; BYTE $0x10 // vpslld	$16, %zmm1, %zmm1
	LONG $0x487dd262; WORD $0x1033             // vpmovzxwd	(%r8), %zmm2            # zmm2 = mem[0],zero,mem[1],zero,mem[2],zero,mem[3],zero,mem[4],zero,mem[5],zero,mem[6],zero,mem[7],zero,mem[8],zero,mem[9],zero,mem[10],zero,mem[11],zero,mem[12],zero,mem[13],zero,mem[14],zero,mem[15],zero
	LONG $0x486df162; WORD $0xf272; BYTE $0x10 // vpslld	$16, %zmm2, %zmm2
	LONG $0x4874f162; WORD $0xca5c             // vsubps	%zmm2, %zmm1, %zmm1
	LONG $0x4874f162; WORD $0xc959             // vmulps	%zmm1, %zmm1, %zmm1
	LONG $0x487cf162; WORD $0xc158             // vaddps	%zmm1, %zmm0, %zmm0
	LONG $0x487df262; WORD $0x4a33; BYTE $0x01 // vpmovzxwd	32(%rdx), %zmm1         # zmm1 = mem[0],zero,mem[1],zero,mem[2],zero,mem[3],zero,mem[4],zero,mem[5],zero,mem[6],zero,mem[7],zero,mem[8],zero,mem[9],zero,mem[10],zero,mem[11],zero,mem[12],zero,mem[13],zero,mem[14],zero,mem[15],zero
	LONG $0x487dd262; WORD $0x5033; BYTE $0x01 // vpmovzxwd	32(%r8), %zmm2          # zmm2 = mem[0],zero,mem[1],zero,mem[2],zero,mem[3],zero,mem[4],zero,mem[5],zero,mem[6],zero,mem[7],zero,mem[8],zero,mem[9],zero,mem[10],zero,mem[11],zero,mem[12],zero,mem[13],zero,mem[14],zero,mem[15],zero
	LONG $0x4875f162; WORD $0xf172; BYTE $0x10 // vpslld	$16, %zmm1, %zmm1
	LONG $0x486df162; WORD $0xf272; BYTE $0x10 // vpslld	$16, %zmm2, %zmm2
	LONG $0x4874f162; WORD $0xca5c             // vsubps	%zmm2, %zmm1, %zmm1
	LONG $0x4874f162; WORD $0xc959             // vmulps	%zmm1, %zmm1, %zmm1
	LONG $0x487cf162; WORD $0xc158             // vaddps	%zmm1, %zmm0, %zmm0
	LONG $0x40c28348                           // addq	$64, %rdx
	LONG $0x40c08349                           // addq	$64, %r8
	LONG $0xfec18349                           // addq	$-2, %r9
	JNE  LBB0_13

LBB0_3:
	WORD $0x8949; BYTE $0xc9                   // movq	%rcx, %r9
	LONG $0x05e1c149                           // shlq	$5, %r9
	WORD $0xc1f6; BYTE $0x01                   // testb	$1, %cl
	JE   LBB0_5
	LONG $0x487df262; WORD $0x0a33             // vpmovzxwd	(%rdx), %zmm1           # zmm1 = mem[0],zero,mem[1],zero,mem[2],zero,mem[3],zero,mem[4],zero,mem[5],zero,mem[6],zero,mem[7],zero,mem[8],zero,mem[9],zero,mem[10],zero,mem[11],zero,mem[12],zero,mem[13],zero,mem[14],zero,mem[15],zero
	LONG $0x4875f162; WORD $0xf172; BYTE $0x10 // vpslld	$16, %zmm1, %zmm1
	LONG $0x487dd262; WORD $0x1033             // vpmovzxwd	(%r8), %zmm2            # zmm2 = mem[0],zero,mem[1],zero,mem[2],zero,mem[3],zero,mem[4],zero,mem[5],zero,mem[6],zero,mem[7],zero,mem[8],zero,mem[9],zero,mem[10],zero,mem[11],zero,mem[12],zero,mem[13],zero,mem[14],zero,mem[15],zero
	LONG $0x486df162; WORD $0xf272; BYTE $0x10 // vpslld	$16, %zmm2, %zmm2
	LONG $0x4874f162; WORD $0xca5c             // vsubps	%zmm2, %zmm1, %zmm1
	LONG $0x4874f162; WORD $0xc959             // vmulps	%zmm1, %zmm1, %zmm1
	LONG $0x487cf162; WORD $0xc158             // vaddps	%zmm1, %zmm0, %zmm0

LBB0_5:
	WORD $0x014c; BYTE $0xcf // addq	%r9, %rdi
	WORD $0x014c; BYTE $0xce // addq	%r9, %rsi

LBB0_6:
	LONG $0xc816fac5                           // vmovshdup	%xmm0, %xmm1            # xmm1 = xmm0[1,1,3,3]
	LONG $0xc958fac5                           // vaddss	%xmm1, %xmm0, %xmm1
	LONG $0xd0c6f9c5; BYTE $0x01               // vshufpd	$1, %xmm0, %xmm0, %xmm2         # xmm2 = xmm0[1,0]
	LONG $0xca58f2c5                           // vaddss	%xmm2, %xmm1, %xmm1
	LONG $0xd0c6f8c5; BYTE $0xff               // vshufps	$255, %xmm0, %xmm0, %xmm2       # xmm2 = xmm0[3,3,3,3]
	LONG $0xca58f2c5                           // vaddss	%xmm2, %xmm1, %xmm1
	LONG $0x197de3c4; WORD $0x01c2             // vextractf128	$1, %ymm0, %xmm2
	LONG $0xca58f2c5                           // vaddss	%xmm2, %xmm1, %xmm1
	LONG $0xda16fac5                           // vmovshdup	%xmm2, %xmm3            # xmm3 = xmm2[1,1,3,3]
	LONG $0xcb58f2c5                           // vaddss	%xmm3, %xmm1, %xmm1
	LONG $0xdac6e9c5; BYTE $0x01               // vshufpd	$1, %xmm2, %xmm2, %xmm3         # xmm3 = xmm2[1,0]
	LONG $0xcb58f2c5                           // vaddss	%xmm3, %xmm1, %xmm1
	LONG $0xd2c6e8c5; BYTE $0xff               // vshufps	$255, %xmm2, %xmm2, %xmm2       # xmm2 = xmm2[3,3,3,3]
	LONG $0xca58f2c5                           // vaddss	%xmm2, %xmm1, %xmm1
	LONG $0x487df362; WORD $0xc219; BYTE $0x02 // vextractf32x4	$2, %zmm0, %xmm2
	LONG $0xca58f2c5                           // vaddss	%xmm2, %xmm1, %xmm1
	LONG $0xda16fac5                           // vmovshdup	%xmm2, %xmm3            # xmm3 = xmm2[1,1,3,3]
	LONG $0xcb58f2c5                           // vaddss	%xmm3, %xmm1, %xmm1
	LONG $0xdac6e9c5; BYTE $0x01               // vshufpd	$1, %xmm2, %xmm2, %xmm3         # xmm3 = xmm2[1,0]
	LONG $0xcb58f2c5                           // vaddss	%xmm3, %xmm1, %xmm1
	LONG $0xd2c6e8c5; BYTE $0xff               // vshufps	$255, %xmm2, %xmm2, %xmm2       # xmm2 = xmm2[3,3,3,3]
	LONG $0xca58f2c5                           // vaddss	%xmm2, %xmm1, %xmm1
	LONG $0x487df362; WORD $0xc019; BYTE $0x03 // vextractf32x4	$3, %zmm0, %xmm0
	LONG $0xc858f2c5                           // vaddss	%xmm0, %xmm1, %xmm1
	LONG $0xd016fac5                           // vmovshdup	%xmm0, %xmm2            # xmm2 = xmm0[1,1,3,3]
	LONG $0xca58f2c5                           // vaddss	%xmm2, %xmm1, %xmm1
	LONG $0xd0c6f9c5; BYTE $0x01               // vshufpd	$1, %xmm0, %xmm0, %xmm2         # xmm2 = xmm0[1,0]
	LONG $0xca58f2c5                           // vaddss	%xmm2, %xmm1, %xmm1
	LONG $0xc0c6f8c5; BYTE $0xff               // vshufps	$255, %xmm0, %xmm0, %xmm0       # xmm0 = xmm0[3,3,3,3]
	LONG $0xc058f2c5                           // vaddss	%xmm0, %xmm1, %xmm0
	WORD $0x8548; BYTE $0xc0                   // testq	%rax, %rax
	JLE  LBB0_11
	LONG $0x01f88348                           // cmpq	$1, %rax
	JNE  LBB0_14
	WORD $0xc931                               // xorl	%ecx, %ecx
	JMP  LBB0_9

LBB0_14:
	QUAD $0xfffffffffff0ba48; WORD $0x7fff // movabsq	$9223372036854775792, %rdx      # imm = 0x7FFFFFFFFFFFFFF0
	LONG $0x0eca8348                       // orq	$14, %rdx
	WORD $0x2148; BYTE $0xc2               // andq	%rax, %rdx
	WORD $0xc931                           // xorl	%ecx, %ecx

LBB0_15:
	LONG $0x04b70f44; BYTE $0x4f   // movzwl	(%rdi,%rcx,2), %r8d
	LONG $0x10e0c141               // shll	$16, %r8d
	LONG $0x6e79c1c4; BYTE $0xc8   // vmovd	%r8d, %xmm1
	LONG $0x04b70f44; BYTE $0x4e   // movzwl	(%rsi,%rcx,2), %r8d
	LONG $0x10e0c141               // shll	$16, %r8d
	LONG $0x6e79c1c4; BYTE $0xd0   // vmovd	%r8d, %xmm2
	LONG $0xca5cf2c5               // vsubss	%xmm2, %xmm1, %xmm1
	LONG $0xa971e2c4; BYTE $0xc8   // vfmadd213ss	%xmm0, %xmm1, %xmm1     # xmm1 = (xmm1 * xmm1) + xmm0
	LONG $0x44b70f44; WORD $0x024f // movzwl	2(%rdi,%rcx,2), %r8d
	LONG $0x10e0c141               // shll	$16, %r8d
	LONG $0x6e79c1c4; BYTE $0xc0   // vmovd	%r8d, %xmm0
	LONG $0x44b70f44; WORD $0x024e // movzwl	2(%rsi,%rcx,2), %r8d
	LONG $0x10e0c141               // shll	$16, %r8d
	LONG $0x6e79c1c4; BYTE $0xd0   // vmovd	%r8d, %xmm2
	LONG $0xc25cfac5               // vsubss	%xmm2, %xmm0, %xmm0
	LONG $0xa979e2c4; BYTE $0xc1   // vfmadd213ss	%xmm1, %xmm0, %xmm0     # xmm0 = (xmm0 * xmm0) + xmm1
	LONG $0x02c18348               // addq	$2, %rcx
	WORD $0x3948; BYTE $0xca       // cmpq	%rcx, %rdx
	JNE  LBB0_15

LBB0_9:
	WORD $0x01a8                 // testb	$1, %al
	JE   LBB0_11
	LONG $0x4f04b70f             // movzwl	(%rdi,%rcx,2), %eax
	WORD $0xe0c1; BYTE $0x10     // shll	$16, %eax
	LONG $0xc86ef9c5             // vmovd	%eax, %xmm1
	LONG $0x4e04b70f             // movzwl	(%rsi,%rcx,2), %eax
	WORD $0xe0c1; BYTE $0x10     // shll	$16, %eax
	LONG $0xd06ef9c5             // vmovd	%eax, %xmm2
	LONG $0xca5cf2c5             // vsubss	%xmm2, %xmm1, %xmm1
	LONG $0xb971e2c4; BYTE $0xc1 // vfmadd231ss	%xmm1, %xmm1, %xmm0     # xmm0 = (xmm1 * xmm1) + xmm0

LBB0_11:
	LONG  $0xc051fac5         // vsqrtss	%xmm0, %xmm0, %xmm0
	WORD  $0x8948; BYTE $0xec // movq	%rbp, %rsp
	BYTE  $0x5d               // popq	%rbp
	WORD  $0xf8c5; BYTE $0x77 // vzeroupper
	MOVSS X0, result+24(FP)
	RET
