//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   20.1.8 (0ubuntu4)
// 	objdump 2.45
// flags: -mavx -mavx512f -mavx512bw -O3
// source: src/bfloats_avx512.c

package bfloats

import "unsafe"

//go:noescape
func _mm512_euclidean_bf16(a, b unsafe.Pointer, n int64) (result float32)
