//go:build !noasm && loong64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   20.1.8 (0ubuntu4)
// 	objdump 2.46
// flags: -mlasx -O3
// source: src/bfloats_lasx.c

TEXT ·lasx_euclidean_bf16(SB), $8-32
	MOVV a+0(FP), R4
	MOVV b+8(FP), R5
	MOVV n+16(FP), R6
	WORD $0x02fec063    // addi.d	$sp, $sp, -80
	WORD $0x0049fcc7    // srai.d	$a3, $a2, 63
	WORD $0x0045f4e7    // srli.d	$a3, $a3, 61
	WORD $0x00109cc8    // add.d	$a4, $a2, $a3
	WORD $0x00150107    // move	$a3, $a4
	WORD $0x00820007    // bstrins.d	$a3, $zero, 2, 0
	WORD $0x00119cc7    // sub.d	$a3, $a2, $a3
	WORD $0x03802009    // ori	$a5, $zero, 8
	WORD $0x77e00000    // xvldi	$xr0, 0
	BLT  R6, R9, LBB0_3
	WORD $0x00490d06    // srai.d	$a2, $a4, 3
	WORD $0x02c0c068    // addi.d	$a4, $sp, 48
	WORD $0x02c04069    // addi.d	$a5, $sp, 16

LBB0_2:
	WORD $0x2c000081    // vld	$vr1, $a0, 0
	WORD $0x72efc02a    // vpickve2gr.h	$a6, $vr1, 0
	WORD $0x76ebc142    // xvinsgr2vr.w	$xr2, $a6, 0
	WORD $0x72efc42a    // vpickve2gr.h	$a6, $vr1, 1
	WORD $0x76ebc542    // xvinsgr2vr.w	$xr2, $a6, 1
	WORD $0x72efc82a    // vpickve2gr.h	$a6, $vr1, 2
	WORD $0x76ebc942    // xvinsgr2vr.w	$xr2, $a6, 2
	WORD $0x72efcc2a    // vpickve2gr.h	$a6, $vr1, 3
	WORD $0x76ebcd42    // xvinsgr2vr.w	$xr2, $a6, 3
	WORD $0x72efd02a    // vpickve2gr.h	$a6, $vr1, 4
	WORD $0x76ebd142    // xvinsgr2vr.w	$xr2, $a6, 4
	WORD $0x72efd42a    // vpickve2gr.h	$a6, $vr1, 5
	WORD $0x76ebd542    // xvinsgr2vr.w	$xr2, $a6, 5
	WORD $0x72efd82a    // vpickve2gr.h	$a6, $vr1, 6
	WORD $0x76ebd942    // xvinsgr2vr.w	$xr2, $a6, 6
	WORD $0x72efdc2a    // vpickve2gr.h	$a6, $vr1, 7
	WORD $0x2c0000a1    // vld	$vr1, $a1, 0
	WORD $0x76ebdd42    // xvinsgr2vr.w	$xr2, $a6, 7
	WORD $0x772cc042    // xvslli.w	$xr2, $xr2, 16
	WORD $0x2cc0c062    // xvst	$xr2, $sp, 48
	WORD $0x72efc02a    // vpickve2gr.h	$a6, $vr1, 0
	WORD $0x76ebc142    // xvinsgr2vr.w	$xr2, $a6, 0
	WORD $0x72efc42a    // vpickve2gr.h	$a6, $vr1, 1
	WORD $0x76ebc542    // xvinsgr2vr.w	$xr2, $a6, 1
	WORD $0x72efc82a    // vpickve2gr.h	$a6, $vr1, 2
	WORD $0x76ebc942    // xvinsgr2vr.w	$xr2, $a6, 2
	WORD $0x72efcc2a    // vpickve2gr.h	$a6, $vr1, 3
	WORD $0x76ebcd42    // xvinsgr2vr.w	$xr2, $a6, 3
	WORD $0x72efd02a    // vpickve2gr.h	$a6, $vr1, 4
	WORD $0x76ebd142    // xvinsgr2vr.w	$xr2, $a6, 4
	WORD $0x72efd42a    // vpickve2gr.h	$a6, $vr1, 5
	WORD $0x76ebd542    // xvinsgr2vr.w	$xr2, $a6, 5
	WORD $0x72efd82a    // vpickve2gr.h	$a6, $vr1, 6
	WORD $0x76ebd942    // xvinsgr2vr.w	$xr2, $a6, 6
	WORD $0x72efdc2a    // vpickve2gr.h	$a6, $vr1, 7
	WORD $0x76ebdd42    // xvinsgr2vr.w	$xr2, $a6, 7
	WORD $0x772cc041    // xvslli.w	$xr1, $xr2, 16
	WORD $0x2cc04061    // xvst	$xr1, $sp, 16
	WORD $0x2c800101    // xvld	$xr1, $a4, 0
	WORD $0x2c800122    // xvld	$xr2, $a5, 0
	WORD $0x75328821    // xvfsub.s	$xr1, $xr1, $xr2
	WORD $0x75388421    // xvfmul.s	$xr1, $xr1, $xr1
	WORD $0x75308400    // xvfadd.s	$xr0, $xr0, $xr1
	WORD $0x02c04084    // addi.d	$a0, $a0, 16
	WORD $0x02fffcc6    // addi.d	$a2, $a2, -1
	WORD $0x02c040a5    // addi.d	$a1, $a1, 16
	BNE  R6, R0, LBB0_2

LBB0_3:
	WORD $0x02c0c066    // addi.d	$a2, $sp, 48
	WORD $0x2cc000c0    // xvst	$xr0, $a2, 0
	WORD $0x2b00c060    // fld.s	$fa0, $sp, 48
	WORD $0x0114a401    // movgr2fr.w	$fa1, $zero
	WORD $0x2b00d062    // fld.s	$fa2, $sp, 52
	WORD $0x2b00e063    // fld.s	$fa3, $sp, 56
	WORD $0x01008400    // fadd.s	$fa0, $fa0, $fa1
	WORD $0x2b00f061    // fld.s	$fa1, $sp, 60
	WORD $0x01008040    // fadd.s	$fa0, $fa2, $fa0
	WORD $0x01008060    // fadd.s	$fa0, $fa3, $fa0
	WORD $0x2b010062    // fld.s	$fa2, $sp, 64
	WORD $0x01008020    // fadd.s	$fa0, $fa1, $fa0
	WORD $0x2b011061    // fld.s	$fa1, $sp, 68
	WORD $0x2b012063    // fld.s	$fa3, $sp, 72
	WORD $0x01008040    // fadd.s	$fa0, $fa2, $fa0
	WORD $0x2b013062    // fld.s	$fa2, $sp, 76
	WORD $0x01008020    // fadd.s	$fa0, $fa1, $fa0
	WORD $0x01008060    // fadd.s	$fa0, $fa3, $fa0
	WORD $0x03800406    // ori	$a2, $zero, 1
	WORD $0x01008040    // fadd.s	$fa0, $fa2, $fa0
	BLT  R7, R6, LBB0_5

LBB0_4:
	WORD $0x28400086    // ld.h	$a2, $a0, 0
	WORD $0x284000a8    // ld.h	$a4, $a1, 0
	WORD $0x004140c6    // slli.d	$a2, $a2, 16
	WORD $0x0114a4c1    // movgr2fr.w	$fa1, $a2
	WORD $0x00414106    // slli.d	$a2, $a4, 16
	WORD $0x0114a4c2    // movgr2fr.w	$fa2, $a2
	WORD $0x01028821    // fsub.s	$fa1, $fa1, $fa2
	WORD $0x08100420    // fmadd.s	$fa0, $fa1, $fa1, $fa0
	WORD $0x02fffce7    // addi.d	$a3, $a3, -1
	WORD $0x02c008a5    // addi.d	$a1, $a1, 2
	WORD $0x02c00884    // addi.d	$a0, $a0, 2
	BNE  R7, R0, LBB0_4

LBB0_5:
	WORD $0x2b403060       // fst.s	$fa0, $sp, 12
	WORD $0x02c03064       // addi.d	$a0, $sp, 12
	WORD $0x32200080       // xvldrepl.w	$xr0, $a0, 0
	WORD $0x769ce400       // xvfsqrt.s	$xr0, $xr0
	WORD $0x02c04064       // addi.d	$a0, $sp, 16
	WORD $0x2cc00080       // xvst	$xr0, $a0, 0
	WORD $0x2b004060       // fld.s	$fa0, $sp, 16
	WORD $0x02c14063       // addi.d	$sp, $sp, 80
	MOVF F0, result+24(FP)
	RET
