//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   20.1.8 (0ubuntu4)
// 	objdump 2.45
// flags: -mavx2 -O3
// source: src/bfloats_avx.c

TEXT ·_mm256_euclidean_bf16(SB), $8-24
	MOVQ a+0(FP), DI
	MOVQ b+8(FP), SI
	MOVQ n+16(FP), DX
	BYTE $0x55                             // pushq	%rbp
	WORD $0x8948; BYTE $0xe5               // movq	%rsp, %rbp
	LONG $0xf8e48348                       // andq	$-8, %rsp
	LONG $0x074a8d48                       // leaq	7(%rdx), %rcx
	WORD $0x8548; BYTE $0xd2               // testq	%rdx, %rdx
	LONG $0xca490f48                       // cmovnsq	%rdx, %rcx
	WORD $0x8949; BYTE $0xc8               // movq	%rcx, %r8
	LONG $0xf8e08349                       // andq	$-8, %r8
	WORD $0x8948; BYTE $0xd0               // movq	%rdx, %rax
	WORD $0x294c; BYTE $0xc0               // subq	%r8, %rax
	LONG $0xc057f8c5                       // vxorps	%xmm0, %xmm0, %xmm0
	LONG $0x08fa8348                       // cmpq	$8, %rdx
	JL   LBB0_6
	LONG $0x03f9c148                       // sarq	$3, %rcx
	QUAD $0xfffffffffff8b849; WORD $0x7fff // movabsq	$9223372036854775800, %r8       # imm = 0x7FFFFFFFFFFFFFF8
	WORD $0x214c; BYTE $0xc2               // andq	%r8, %rdx
	LONG $0x08fa8348                       // cmpq	$8, %rdx
	JNE  LBB0_15
	WORD $0x8948; BYTE $0xfa               // movq	%rdi, %rdx
	WORD $0x8949; BYTE $0xf0               // movq	%rsi, %r8
	JMP  LBB0_3

LBB0_15:
	QUAD $0xfffffffffffeb949; WORD $0x0fff // movabsq	$1152921504606846974, %r9       # imm = 0xFFFFFFFFFFFFFFE
	WORD $0x2149; BYTE $0xc9               // andq	%rcx, %r9
	WORD $0x8948; BYTE $0xfa               // movq	%rdi, %rdx
	WORD $0x8949; BYTE $0xf0               // movq	%rsi, %r8

LBB0_16:
	LONG $0x337de2c4; BYTE $0x0a   // vpmovzxwd	(%rdx), %ymm1           # ymm1 = mem[0],zero,mem[1],zero,mem[2],zero,mem[3],zero,mem[4],zero,mem[5],zero,mem[6],zero,mem[7],zero
	LONG $0xf172f5c5; BYTE $0x10   // vpslld	$16, %ymm1, %ymm1
	LONG $0x337dc2c4; BYTE $0x10   // vpmovzxwd	(%r8), %ymm2            # ymm2 = mem[0],zero,mem[1],zero,mem[2],zero,mem[3],zero,mem[4],zero,mem[5],zero,mem[6],zero,mem[7],zero
	LONG $0xf272edc5; BYTE $0x10   // vpslld	$16, %ymm2, %ymm2
	LONG $0xca5cf4c5               // vsubps	%ymm2, %ymm1, %ymm1
	LONG $0xc959f4c5               // vmulps	%ymm1, %ymm1, %ymm1
	LONG $0xc158fcc5               // vaddps	%ymm1, %ymm0, %ymm0
	LONG $0x337de2c4; WORD $0x104a // vpmovzxwd	16(%rdx), %ymm1         # ymm1 = mem[0],zero,mem[1],zero,mem[2],zero,mem[3],zero,mem[4],zero,mem[5],zero,mem[6],zero,mem[7],zero
	LONG $0x337dc2c4; WORD $0x1050 // vpmovzxwd	16(%r8), %ymm2          # ymm2 = mem[0],zero,mem[1],zero,mem[2],zero,mem[3],zero,mem[4],zero,mem[5],zero,mem[6],zero,mem[7],zero
	LONG $0xf172f5c5; BYTE $0x10   // vpslld	$16, %ymm1, %ymm1
	LONG $0xf272edc5; BYTE $0x10   // vpslld	$16, %ymm2, %ymm2
	LONG $0xca5cf4c5               // vsubps	%ymm2, %ymm1, %ymm1
	LONG $0xc959f4c5               // vmulps	%ymm1, %ymm1, %ymm1
	LONG $0xc158fcc5               // vaddps	%ymm1, %ymm0, %ymm0
	LONG $0x20c28348               // addq	$32, %rdx
	LONG $0x20c08349               // addq	$32, %r8
	LONG $0xfec18349               // addq	$-2, %r9
	JNE  LBB0_16

LBB0_3:
	WORD $0x8949; BYTE $0xc9     // movq	%rcx, %r9
	LONG $0x04e1c149             // shlq	$4, %r9
	WORD $0xc1f6; BYTE $0x01     // testb	$1, %cl
	JE   LBB0_5
	LONG $0x337de2c4; BYTE $0x0a // vpmovzxwd	(%rdx), %ymm1           # ymm1 = mem[0],zero,mem[1],zero,mem[2],zero,mem[3],zero,mem[4],zero,mem[5],zero,mem[6],zero,mem[7],zero
	LONG $0xf172f5c5; BYTE $0x10 // vpslld	$16, %ymm1, %ymm1
	LONG $0x337dc2c4; BYTE $0x10 // vpmovzxwd	(%r8), %ymm2            # ymm2 = mem[0],zero,mem[1],zero,mem[2],zero,mem[3],zero,mem[4],zero,mem[5],zero,mem[6],zero,mem[7],zero
	LONG $0xf272edc5; BYTE $0x10 // vpslld	$16, %ymm2, %ymm2
	LONG $0xca5cf4c5             // vsubps	%ymm2, %ymm1, %ymm1
	LONG $0xc959f4c5             // vmulps	%ymm1, %ymm1, %ymm1
	LONG $0xc158fcc5             // vaddps	%ymm1, %ymm0, %ymm0

LBB0_5:
	WORD $0x014c; BYTE $0xcf // addq	%r9, %rdi
	WORD $0x014c; BYTE $0xce // addq	%r9, %rsi

LBB0_6:
	LONG $0x197de3c4; WORD $0x01c1 // vextractf128	$1, %ymm0, %xmm1
	LONG $0xc058f0c5               // vaddps	%xmm0, %xmm1, %xmm0
	LONG $0xc8c6f9c5; BYTE $0x01   // vshufpd	$1, %xmm0, %xmm0, %xmm1         # xmm1 = xmm0[1,0]
	LONG $0xc158f8c5               // vaddps	%xmm1, %xmm0, %xmm0
	LONG $0xc816fac5               // vmovshdup	%xmm0, %xmm1            # xmm1 = xmm0[1,1,3,3]
	LONG $0xc158fac5               // vaddss	%xmm1, %xmm0, %xmm0
	WORD $0x8548; BYTE $0xc0       // testq	%rax, %rax
	JLE  LBB0_14
	WORD $0xb70f; BYTE $0x0f       // movzwl	(%rdi), %ecx
	WORD $0xe1c1; BYTE $0x10       // shll	$16, %ecx
	LONG $0xc96ef9c5               // vmovd	%ecx, %xmm1
	WORD $0xb70f; BYTE $0x0e       // movzwl	(%rsi), %ecx
	WORD $0xe1c1; BYTE $0x10       // shll	$16, %ecx
	LONG $0xd16ef9c5               // vmovd	%ecx, %xmm2
	LONG $0xca5cf2c5               // vsubss	%xmm2, %xmm1, %xmm1
	LONG $0xc959f2c5               // vmulss	%xmm1, %xmm1, %xmm1
	LONG $0xc058f2c5               // vaddss	%xmm0, %xmm1, %xmm0
	LONG $0x01f88348               // cmpq	$1, %rax
	JE   LBB0_14
	LONG $0x024fb70f               // movzwl	2(%rdi), %ecx
	WORD $0xe1c1; BYTE $0x10       // shll	$16, %ecx
	LONG $0xc96ef9c5               // vmovd	%ecx, %xmm1
	LONG $0x024eb70f               // movzwl	2(%rsi), %ecx
	WORD $0xe1c1; BYTE $0x10       // shll	$16, %ecx
	LONG $0xd16ef9c5               // vmovd	%ecx, %xmm2
	LONG $0xca5cf2c5               // vsubss	%xmm2, %xmm1, %xmm1
	LONG $0xc959f2c5               // vmulss	%xmm1, %xmm1, %xmm1
	LONG $0xc058f2c5               // vaddss	%xmm0, %xmm1, %xmm0
	LONG $0x02f88348               // cmpq	$2, %rax
	JE   LBB0_14
	LONG $0x044fb70f               // movzwl	4(%rdi), %ecx
	WORD $0xe1c1; BYTE $0x10       // shll	$16, %ecx
	LONG $0xc96ef9c5               // vmovd	%ecx, %xmm1
	LONG $0x044eb70f               // movzwl	4(%rsi), %ecx
	WORD $0xe1c1; BYTE $0x10       // shll	$16, %ecx
	LONG $0xd16ef9c5               // vmovd	%ecx, %xmm2
	LONG $0xca5cf2c5               // vsubss	%xmm2, %xmm1, %xmm1
	LONG $0xc959f2c5               // vmulss	%xmm1, %xmm1, %xmm1
	LONG $0xc058f2c5               // vaddss	%xmm0, %xmm1, %xmm0
	LONG $0x03f88348               // cmpq	$3, %rax
	JE   LBB0_14
	LONG $0x064fb70f               // movzwl	6(%rdi), %ecx
	WORD $0xe1c1; BYTE $0x10       // shll	$16, %ecx
	LONG $0xc96ef9c5               // vmovd	%ecx, %xmm1
	LONG $0x064eb70f               // movzwl	6(%rsi), %ecx
	WORD $0xe1c1; BYTE $0x10       // shll	$16, %ecx
	LONG $0xd16ef9c5               // vmovd	%ecx, %xmm2
	LONG $0xca5cf2c5               // vsubss	%xmm2, %xmm1, %xmm1
	LONG $0xc959f2c5               // vmulss	%xmm1, %xmm1, %xmm1
	LONG $0xc058f2c5               // vaddss	%xmm0, %xmm1, %xmm0
	LONG $0x04f88348               // cmpq	$4, %rax
	JE   LBB0_14
	LONG $0x084fb70f               // movzwl	8(%rdi), %ecx
	WORD $0xe1c1; BYTE $0x10       // shll	$16, %ecx
	LONG $0xc96ef9c5               // vmovd	%ecx, %xmm1
	LONG $0x084eb70f               // movzwl	8(%rsi), %ecx
	WORD $0xe1c1; BYTE $0x10       // shll	$16, %ecx
	LONG $0xd16ef9c5               // vmovd	%ecx, %xmm2
	LONG $0xca5cf2c5               // vsubss	%xmm2, %xmm1, %xmm1
	LONG $0xc959f2c5               // vmulss	%xmm1, %xmm1, %xmm1
	LONG $0xc058f2c5               // vaddss	%xmm0, %xmm1, %xmm0
	LONG $0x05f88348               // cmpq	$5, %rax
	JE   LBB0_14
	LONG $0x0a4fb70f               // movzwl	10(%rdi), %ecx
	WORD $0xe1c1; BYTE $0x10       // shll	$16, %ecx
	LONG $0xc96ef9c5               // vmovd	%ecx, %xmm1
	LONG $0x0a4eb70f               // movzwl	10(%rsi), %ecx
	WORD $0xe1c1; BYTE $0x10       // shll	$16, %ecx
	LONG $0xd16ef9c5               // vmovd	%ecx, %xmm2
	LONG $0xca5cf2c5               // vsubss	%xmm2, %xmm1, %xmm1
	LONG $0xc959f2c5               // vmulss	%xmm1, %xmm1, %xmm1
	LONG $0xc058f2c5               // vaddss	%xmm0, %xmm1, %xmm0
	LONG $0x06f88348               // cmpq	$6, %rax
	JE   LBB0_14
	LONG $0x0c47b70f               // movzwl	12(%rdi), %eax
	WORD $0xe0c1; BYTE $0x10       // shll	$16, %eax
	LONG $0xc86ef9c5               // vmovd	%eax, %xmm1
	LONG $0x0c46b70f               // movzwl	12(%rsi), %eax
	WORD $0xe0c1; BYTE $0x10       // shll	$16, %eax
	LONG $0xd06ef9c5               // vmovd	%eax, %xmm2
	LONG $0xca5cf2c5               // vsubss	%xmm2, %xmm1, %xmm1
	LONG $0xc959f2c5               // vmulss	%xmm1, %xmm1, %xmm1
	LONG $0xc058f2c5               // vaddss	%xmm0, %xmm1, %xmm0

LBB0_14:
	LONG  $0xc051fac5         // vsqrtss	%xmm0, %xmm0, %xmm0
	WORD  $0x8948; BYTE $0xec // movq	%rbp, %rsp
	BYTE  $0x5d               // popq	%rbp
	WORD  $0xf8c5; BYTE $0x77 // vzeroupper
	MOVSS X0, result+24(FP)
	RET
