// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// MasterClient is the client API for Master service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MasterClient interface {
	// meta distribute
	GetMeta(ctx context.Context, in *RequestInfo, opts ...grpc.CallOption) (*Meta, error)
	// data distribute
	GetUserIndex(ctx context.Context, in *RequestInfo, opts ...grpc.CallOption) (*UserIndex, error)
	GetFactorizationMachine(ctx context.Context, in *RequestInfo, opts ...grpc.CallOption) (*Model, error)
	GetCollaborativeFilteringModel(ctx context.Context, in *RequestInfo, opts ...grpc.CallOption) (*Model, error)
}

type masterClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterClient(cc grpc.ClientConnInterface) MasterClient {
	return &masterClient{cc}
}

func (c *masterClient) GetMeta(ctx context.Context, in *RequestInfo, opts ...grpc.CallOption) (*Meta, error) {
	out := new(Meta)
	err := c.cc.Invoke(ctx, "/protocol.Master/GetMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) GetUserIndex(ctx context.Context, in *RequestInfo, opts ...grpc.CallOption) (*UserIndex, error) {
	out := new(UserIndex)
	err := c.cc.Invoke(ctx, "/protocol.Master/GetUserIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) GetFactorizationMachine(ctx context.Context, in *RequestInfo, opts ...grpc.CallOption) (*Model, error) {
	out := new(Model)
	err := c.cc.Invoke(ctx, "/protocol.Master/GetFactorizationMachine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) GetCollaborativeFilteringModel(ctx context.Context, in *RequestInfo, opts ...grpc.CallOption) (*Model, error) {
	out := new(Model)
	err := c.cc.Invoke(ctx, "/protocol.Master/GetCollaborativeFilteringModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterServer is the server API for Master service.
// All implementations must embed UnimplementedMasterServer
// for forward compatibility
type MasterServer interface {
	// meta distribute
	GetMeta(context.Context, *RequestInfo) (*Meta, error)
	// data distribute
	GetUserIndex(context.Context, *RequestInfo) (*UserIndex, error)
	GetFactorizationMachine(context.Context, *RequestInfo) (*Model, error)
	GetCollaborativeFilteringModel(context.Context, *RequestInfo) (*Model, error)
	mustEmbedUnimplementedMasterServer()
}

// UnimplementedMasterServer must be embedded to have forward compatible implementations.
type UnimplementedMasterServer struct {
}

func (UnimplementedMasterServer) GetMeta(context.Context, *RequestInfo) (*Meta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMeta not implemented")
}
func (UnimplementedMasterServer) GetUserIndex(context.Context, *RequestInfo) (*UserIndex, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserIndex not implemented")
}
func (UnimplementedMasterServer) GetFactorizationMachine(context.Context, *RequestInfo) (*Model, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFactorizationMachine not implemented")
}
func (UnimplementedMasterServer) GetCollaborativeFilteringModel(context.Context, *RequestInfo) (*Model, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollaborativeFilteringModel not implemented")
}
func (UnimplementedMasterServer) mustEmbedUnimplementedMasterServer() {}

// UnsafeMasterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterServer will
// result in compilation errors.
type UnsafeMasterServer interface {
	mustEmbedUnimplementedMasterServer()
}

func RegisterMasterServer(s grpc.ServiceRegistrar, srv MasterServer) {
	s.RegisterService(&_Master_serviceDesc, srv)
}

func _Master_GetMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).GetMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Master/GetMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).GetMeta(ctx, req.(*RequestInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_GetUserIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).GetUserIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Master/GetUserIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).GetUserIndex(ctx, req.(*RequestInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_GetFactorizationMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).GetFactorizationMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Master/GetFactorizationMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).GetFactorizationMachine(ctx, req.(*RequestInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_GetCollaborativeFilteringModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).GetCollaborativeFilteringModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Master/GetCollaborativeFilteringModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).GetCollaborativeFilteringModel(ctx, req.(*RequestInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Master_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.Master",
	HandlerType: (*MasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMeta",
			Handler:    _Master_GetMeta_Handler,
		},
		{
			MethodName: "GetUserIndex",
			Handler:    _Master_GetUserIndex_Handler,
		},
		{
			MethodName: "GetFactorizationMachine",
			Handler:    _Master_GetFactorizationMachine_Handler,
		},
		{
			MethodName: "GetCollaborativeFilteringModel",
			Handler:    _Master_GetCollaborativeFilteringModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocol.proto",
}
