// Copyright 2026 gorse Project Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.3
// source: vector_store.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Distance int32

const (
	Distance_Unknown   Distance = 0
	Distance_Cosine    Distance = 1
	Distance_Euclidean Distance = 2
	Distance_Dot       Distance = 3
)

// Enum value maps for Distance.
var (
	Distance_name = map[int32]string{
		0: "Unknown",
		1: "Cosine",
		2: "Euclidean",
		3: "Dot",
	}
	Distance_value = map[string]int32{
		"Unknown":   0,
		"Cosine":    1,
		"Euclidean": 2,
		"Dot":       3,
	}
)

func (x Distance) Enum() *Distance {
	p := new(Distance)
	*p = x
	return p
}

func (x Distance) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Distance) Descriptor() protoreflect.EnumDescriptor {
	return file_vector_store_proto_enumTypes[0].Descriptor()
}

func (Distance) Type() protoreflect.EnumType {
	return &file_vector_store_proto_enumTypes[0]
}

func (x Distance) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Distance.Descriptor instead.
func (Distance) EnumDescriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{0}
}

type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Values        []float32              `protobuf:"fixed32,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	Categories    []string               `protobuf:"bytes,3,rep,name=categories,proto3" json:"categories,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IsHidden      bool                   `protobuf:"varint,5,opt,name=is_hidden,json=isHidden,proto3" json:"is_hidden,omitempty"`
	Indices       []uint32               `protobuf:"varint,6,rep,packed,name=indices,proto3" json:"indices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_vector_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{0}
}

func (x *Vector) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Vector) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Vector) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Vector) GetIsHidden() bool {
	if x != nil {
		return x.IsHidden
	}
	return false
}

func (x *Vector) GetIndices() []uint32 {
	if x != nil {
		return x.Indices
	}
	return nil
}

type ScoredVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        *Vector                `protobuf:"bytes,1,opt,name=vector,proto3" json:"vector,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoredVector) Reset() {
	*x = ScoredVector{}
	mi := &file_vector_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoredVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoredVector) ProtoMessage() {}

func (x *ScoredVector) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoredVector.ProtoReflect.Descriptor instead.
func (*ScoredVector) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{1}
}

func (x *ScoredVector) GetVector() *Vector {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *ScoredVector) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type ListCollectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsRequest) Reset() {
	*x = ListCollectionsRequest{}
	mi := &file_vector_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsRequest) ProtoMessage() {}

func (x *ListCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{2}
}

type ListCollectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collections   []string               `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResponse) Reset() {
	*x = ListCollectionsResponse{}
	mi := &file_vector_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResponse) ProtoMessage() {}

func (x *ListCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{3}
}

func (x *ListCollectionsResponse) GetCollections() []string {
	if x != nil {
		return x.Collections
	}
	return nil
}

type VectorConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	QuantizationType string                 `protobuf:"bytes,1,opt,name=quantization_type,json=quantizationType,proto3" json:"quantization_type,omitempty"`
	QuantizationBits int32                  `protobuf:"varint,2,opt,name=quantization_bits,json=quantizationBits,proto3" json:"quantization_bits,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VectorConfig) Reset() {
	*x = VectorConfig{}
	mi := &file_vector_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorConfig) ProtoMessage() {}

func (x *VectorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorConfig.ProtoReflect.Descriptor instead.
func (*VectorConfig) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{4}
}

func (x *VectorConfig) GetQuantizationType() string {
	if x != nil {
		return x.QuantizationType
	}
	return ""
}

func (x *VectorConfig) GetQuantizationBits() int32 {
	if x != nil {
		return x.QuantizationBits
	}
	return 0
}

type DescribeCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeCollectionRequest) Reset() {
	*x = DescribeCollectionRequest{}
	mi := &file_vector_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeCollectionRequest) ProtoMessage() {}

func (x *DescribeCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeCollectionRequest.ProtoReflect.Descriptor instead.
func (*DescribeCollectionRequest) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{5}
}

func (x *DescribeCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DescribeCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dimensions    int32                  `protobuf:"varint,2,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Distance      Distance               `protobuf:"varint,3,opt,name=distance,proto3,enum=protocol.Distance" json:"distance,omitempty"`
	Config        *VectorConfig          `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeCollectionResponse) Reset() {
	*x = DescribeCollectionResponse{}
	mi := &file_vector_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeCollectionResponse) ProtoMessage() {}

func (x *DescribeCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeCollectionResponse.ProtoReflect.Descriptor instead.
func (*DescribeCollectionResponse) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{6}
}

func (x *DescribeCollectionResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DescribeCollectionResponse) GetDimensions() int32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

func (x *DescribeCollectionResponse) GetDistance() Distance {
	if x != nil {
		return x.Distance
	}
	return Distance_Unknown
}

func (x *DescribeCollectionResponse) GetConfig() *VectorConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type AddCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dimensions    int32                  `protobuf:"varint,2,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Distance      Distance               `protobuf:"varint,3,opt,name=distance,proto3,enum=protocol.Distance" json:"distance,omitempty"`
	Config        *VectorConfig          `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCollectionRequest) Reset() {
	*x = AddCollectionRequest{}
	mi := &file_vector_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCollectionRequest) ProtoMessage() {}

func (x *AddCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCollectionRequest.ProtoReflect.Descriptor instead.
func (*AddCollectionRequest) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{7}
}

func (x *AddCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddCollectionRequest) GetDimensions() int32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

func (x *AddCollectionRequest) GetDistance() Distance {
	if x != nil {
		return x.Distance
	}
	return Distance_Unknown
}

func (x *AddCollectionRequest) GetConfig() *VectorConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type AddCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCollectionResponse) Reset() {
	*x = AddCollectionResponse{}
	mi := &file_vector_store_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCollectionResponse) ProtoMessage() {}

func (x *AddCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCollectionResponse.ProtoReflect.Descriptor instead.
func (*AddCollectionResponse) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{8}
}

type DeleteCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectionRequest) Reset() {
	*x = DeleteCollectionRequest{}
	mi := &file_vector_store_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionRequest) ProtoMessage() {}

func (x *DeleteCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionRequest.ProtoReflect.Descriptor instead.
func (*DeleteCollectionRequest) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectionResponse) Reset() {
	*x = DeleteCollectionResponse{}
	mi := &file_vector_store_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionResponse) ProtoMessage() {}

func (x *DeleteCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionResponse.ProtoReflect.Descriptor instead.
func (*DeleteCollectionResponse) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{10}
}

type AddVectorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Vectors       []*Vector              `protobuf:"bytes,2,rep,name=vectors,proto3" json:"vectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVectorsRequest) Reset() {
	*x = AddVectorsRequest{}
	mi := &file_vector_store_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVectorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVectorsRequest) ProtoMessage() {}

func (x *AddVectorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVectorsRequest.ProtoReflect.Descriptor instead.
func (*AddVectorsRequest) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{11}
}

func (x *AddVectorsRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *AddVectorsRequest) GetVectors() []*Vector {
	if x != nil {
		return x.Vectors
	}
	return nil
}

type AddVectorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVectorsResponse) Reset() {
	*x = AddVectorsResponse{}
	mi := &file_vector_store_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVectorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVectorsResponse) ProtoMessage() {}

func (x *AddVectorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVectorsResponse.ProtoReflect.Descriptor instead.
func (*AddVectorsResponse) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{12}
}

type DeleteVectorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVectorsRequest) Reset() {
	*x = DeleteVectorsRequest{}
	mi := &file_vector_store_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVectorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVectorsRequest) ProtoMessage() {}

func (x *DeleteVectorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVectorsRequest.ProtoReflect.Descriptor instead.
func (*DeleteVectorsRequest) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteVectorsRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DeleteVectorsRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type DeleteVectorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVectorsResponse) Reset() {
	*x = DeleteVectorsResponse{}
	mi := &file_vector_store_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVectorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVectorsResponse) ProtoMessage() {}

func (x *DeleteVectorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVectorsResponse.ProtoReflect.Descriptor instead.
func (*DeleteVectorsResponse) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{14}
}

type QueryVectorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Query         *Vector                `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Categories    []string               `protobuf:"bytes,3,rep,name=categories,proto3" json:"categories,omitempty"`
	TopK          int32                  `protobuf:"varint,4,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVectorsRequest) Reset() {
	*x = QueryVectorsRequest{}
	mi := &file_vector_store_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVectorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVectorsRequest) ProtoMessage() {}

func (x *QueryVectorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVectorsRequest.ProtoReflect.Descriptor instead.
func (*QueryVectorsRequest) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{15}
}

func (x *QueryVectorsRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *QueryVectorsRequest) GetQuery() *Vector {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *QueryVectorsRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *QueryVectorsRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type QueryVectorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vectors       []*ScoredVector        `protobuf:"bytes,1,rep,name=vectors,proto3" json:"vectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVectorsResponse) Reset() {
	*x = QueryVectorsResponse{}
	mi := &file_vector_store_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVectorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVectorsResponse) ProtoMessage() {}

func (x *QueryVectorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVectorsResponse.ProtoReflect.Descriptor instead.
func (*QueryVectorsResponse) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{16}
}

func (x *QueryVectorsResponse) GetVectors() []*ScoredVector {
	if x != nil {
		return x.Vectors
	}
	return nil
}

type CountVectorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountVectorsRequest) Reset() {
	*x = CountVectorsRequest{}
	mi := &file_vector_store_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountVectorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountVectorsRequest) ProtoMessage() {}

func (x *CountVectorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountVectorsRequest.ProtoReflect.Descriptor instead.
func (*CountVectorsRequest) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{17}
}

func (x *CountVectorsRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type CountVectorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountVectorsResponse) Reset() {
	*x = CountVectorsResponse{}
	mi := &file_vector_store_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountVectorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountVectorsResponse) ProtoMessage() {}

func (x *CountVectorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountVectorsResponse.ProtoReflect.Descriptor instead.
func (*CountVectorsResponse) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{18}
}

func (x *CountVectorsResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_vector_store_proto protoreflect.FileDescriptor

const file_vector_store_proto_rawDesc = "" +
	"\n" +
	"\x12vector_store.proto\x12\bprotocol\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc1\x01\n" +
	"\x06Vector\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x02R\x06values\x12\x1e\n" +
	"\n" +
	"categories\x18\x03 \x03(\tR\n" +
	"categories\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1b\n" +
	"\tis_hidden\x18\x05 \x01(\bR\bisHidden\x12\x18\n" +
	"\aindices\x18\x06 \x03(\rR\aindices\"N\n" +
	"\fScoredVector\x12(\n" +
	"\x06vector\x18\x01 \x01(\v2\x10.protocol.VectorR\x06vector\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\"\x18\n" +
	"\x16ListCollectionsRequest\";\n" +
	"\x17ListCollectionsResponse\x12 \n" +
	"\vcollections\x18\x01 \x03(\tR\vcollections\"h\n" +
	"\fVectorConfig\x12+\n" +
	"\x11quantization_type\x18\x01 \x01(\tR\x10quantizationType\x12+\n" +
	"\x11quantization_bits\x18\x02 \x01(\x05R\x10quantizationBits\"/\n" +
	"\x19DescribeCollectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xb0\x01\n" +
	"\x1aDescribeCollectionResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x02 \x01(\x05R\n" +
	"dimensions\x12.\n" +
	"\bdistance\x18\x03 \x01(\x0e2\x12.protocol.DistanceR\bdistance\x12.\n" +
	"\x06config\x18\x04 \x01(\v2\x16.protocol.VectorConfigR\x06config\"\xaa\x01\n" +
	"\x14AddCollectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x02 \x01(\x05R\n" +
	"dimensions\x12.\n" +
	"\bdistance\x18\x03 \x01(\x0e2\x12.protocol.DistanceR\bdistance\x12.\n" +
	"\x06config\x18\x04 \x01(\v2\x16.protocol.VectorConfigR\x06config\"\x17\n" +
	"\x15AddCollectionResponse\"-\n" +
	"\x17DeleteCollectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1a\n" +
	"\x18DeleteCollectionResponse\"_\n" +
	"\x11AddVectorsRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12*\n" +
	"\avectors\x18\x02 \x03(\v2\x10.protocol.VectorR\avectors\"\x14\n" +
	"\x12AddVectorsResponse\"p\n" +
	"\x14DeleteVectorsRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x17\n" +
	"\x15DeleteVectorsResponse\"\x92\x01\n" +
	"\x13QueryVectorsRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12&\n" +
	"\x05query\x18\x02 \x01(\v2\x10.protocol.VectorR\x05query\x12\x1e\n" +
	"\n" +
	"categories\x18\x03 \x03(\tR\n" +
	"categories\x12\x13\n" +
	"\x05top_k\x18\x04 \x01(\x05R\x04topK\"H\n" +
	"\x14QueryVectorsResponse\x120\n" +
	"\avectors\x18\x01 \x03(\v2\x16.protocol.ScoredVectorR\avectors\"5\n" +
	"\x13CountVectorsRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\",\n" +
	"\x14CountVectorsResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count*;\n" +
	"\bDistance\x12\v\n" +
	"\aUnknown\x10\x00\x12\n" +
	"\n" +
	"\x06Cosine\x10\x01\x12\r\n" +
	"\tEuclidean\x10\x02\x12\a\n" +
	"\x03Dot\x10\x032\xbc\x05\n" +
	"\vVectorStore\x12X\n" +
	"\x0fListCollections\x12 .protocol.ListCollectionsRequest\x1a!.protocol.ListCollectionsResponse\"\x00\x12a\n" +
	"\x12DescribeCollection\x12#.protocol.DescribeCollectionRequest\x1a$.protocol.DescribeCollectionResponse\"\x00\x12R\n" +
	"\rAddCollection\x12\x1e.protocol.AddCollectionRequest\x1a\x1f.protocol.AddCollectionResponse\"\x00\x12[\n" +
	"\x10DeleteCollection\x12!.protocol.DeleteCollectionRequest\x1a\".protocol.DeleteCollectionResponse\"\x00\x12O\n" +
	"\fCountVectors\x12\x1d.protocol.CountVectorsRequest\x1a\x1e.protocol.CountVectorsResponse\"\x00\x12I\n" +
	"\n" +
	"AddVectors\x12\x1b.protocol.AddVectorsRequest\x1a\x1c.protocol.AddVectorsResponse\"\x00\x12R\n" +
	"\rDeleteVectors\x12\x1e.protocol.DeleteVectorsRequest\x1a\x1f.protocol.DeleteVectorsResponse\"\x00\x12O\n" +
	"\fQueryVectors\x12\x1d.protocol.QueryVectorsRequest\x1a\x1e.protocol.QueryVectorsResponse\"\x00B$Z\"github.com/gorse-io/gorse/protocolb\x06proto3"

var (
	file_vector_store_proto_rawDescOnce sync.Once
	file_vector_store_proto_rawDescData []byte
)

func file_vector_store_proto_rawDescGZIP() []byte {
	file_vector_store_proto_rawDescOnce.Do(func() {
		file_vector_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vector_store_proto_rawDesc), len(file_vector_store_proto_rawDesc)))
	})
	return file_vector_store_proto_rawDescData
}

var file_vector_store_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vector_store_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_vector_store_proto_goTypes = []any{
	(Distance)(0),                      // 0: protocol.Distance
	(*Vector)(nil),                     // 1: protocol.Vector
	(*ScoredVector)(nil),               // 2: protocol.ScoredVector
	(*ListCollectionsRequest)(nil),     // 3: protocol.ListCollectionsRequest
	(*ListCollectionsResponse)(nil),    // 4: protocol.ListCollectionsResponse
	(*VectorConfig)(nil),               // 5: protocol.VectorConfig
	(*DescribeCollectionRequest)(nil),  // 6: protocol.DescribeCollectionRequest
	(*DescribeCollectionResponse)(nil), // 7: protocol.DescribeCollectionResponse
	(*AddCollectionRequest)(nil),       // 8: protocol.AddCollectionRequest
	(*AddCollectionResponse)(nil),      // 9: protocol.AddCollectionResponse
	(*DeleteCollectionRequest)(nil),    // 10: protocol.DeleteCollectionRequest
	(*DeleteCollectionResponse)(nil),   // 11: protocol.DeleteCollectionResponse
	(*AddVectorsRequest)(nil),          // 12: protocol.AddVectorsRequest
	(*AddVectorsResponse)(nil),         // 13: protocol.AddVectorsResponse
	(*DeleteVectorsRequest)(nil),       // 14: protocol.DeleteVectorsRequest
	(*DeleteVectorsResponse)(nil),      // 15: protocol.DeleteVectorsResponse
	(*QueryVectorsRequest)(nil),        // 16: protocol.QueryVectorsRequest
	(*QueryVectorsResponse)(nil),       // 17: protocol.QueryVectorsResponse
	(*CountVectorsRequest)(nil),        // 18: protocol.CountVectorsRequest
	(*CountVectorsResponse)(nil),       // 19: protocol.CountVectorsResponse
	(*timestamppb.Timestamp)(nil),      // 20: google.protobuf.Timestamp
}
var file_vector_store_proto_depIdxs = []int32{
	20, // 0: protocol.Vector.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 1: protocol.ScoredVector.vector:type_name -> protocol.Vector
	0,  // 2: protocol.DescribeCollectionResponse.distance:type_name -> protocol.Distance
	5,  // 3: protocol.DescribeCollectionResponse.config:type_name -> protocol.VectorConfig
	0,  // 4: protocol.AddCollectionRequest.distance:type_name -> protocol.Distance
	5,  // 5: protocol.AddCollectionRequest.config:type_name -> protocol.VectorConfig
	1,  // 6: protocol.AddVectorsRequest.vectors:type_name -> protocol.Vector
	20, // 7: protocol.DeleteVectorsRequest.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 8: protocol.QueryVectorsRequest.query:type_name -> protocol.Vector
	2,  // 9: protocol.QueryVectorsResponse.vectors:type_name -> protocol.ScoredVector
	3,  // 10: protocol.VectorStore.ListCollections:input_type -> protocol.ListCollectionsRequest
	6,  // 11: protocol.VectorStore.DescribeCollection:input_type -> protocol.DescribeCollectionRequest
	8,  // 12: protocol.VectorStore.AddCollection:input_type -> protocol.AddCollectionRequest
	10, // 13: protocol.VectorStore.DeleteCollection:input_type -> protocol.DeleteCollectionRequest
	18, // 14: protocol.VectorStore.CountVectors:input_type -> protocol.CountVectorsRequest
	12, // 15: protocol.VectorStore.AddVectors:input_type -> protocol.AddVectorsRequest
	14, // 16: protocol.VectorStore.DeleteVectors:input_type -> protocol.DeleteVectorsRequest
	16, // 17: protocol.VectorStore.QueryVectors:input_type -> protocol.QueryVectorsRequest
	4,  // 18: protocol.VectorStore.ListCollections:output_type -> protocol.ListCollectionsResponse
	7,  // 19: protocol.VectorStore.DescribeCollection:output_type -> protocol.DescribeCollectionResponse
	9,  // 20: protocol.VectorStore.AddCollection:output_type -> protocol.AddCollectionResponse
	11, // 21: protocol.VectorStore.DeleteCollection:output_type -> protocol.DeleteCollectionResponse
	19, // 22: protocol.VectorStore.CountVectors:output_type -> protocol.CountVectorsResponse
	13, // 23: protocol.VectorStore.AddVectors:output_type -> protocol.AddVectorsResponse
	15, // 24: protocol.VectorStore.DeleteVectors:output_type -> protocol.DeleteVectorsResponse
	17, // 25: protocol.VectorStore.QueryVectors:output_type -> protocol.QueryVectorsResponse
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_vector_store_proto_init() }
func file_vector_store_proto_init() {
	if File_vector_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vector_store_proto_rawDesc), len(file_vector_store_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vector_store_proto_goTypes,
		DependencyIndexes: file_vector_store_proto_depIdxs,
		EnumInfos:         file_vector_store_proto_enumTypes,
		MessageInfos:      file_vector_store_proto_msgTypes,
	}.Build()
	File_vector_store_proto = out.File
	file_vector_store_proto_goTypes = nil
	file_vector_store_proto_depIdxs = nil
}
