//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -march=armv8.2-a+fp16 -O3
// source: src/floats_fp16_neon.c

TEXT ·vfrom_float32(SB), $0-24
	MOVD a+0(FP), R0
	MOVD dst+8(FP), R1
	MOVD n+16(FP), R2
	WORD $0xf100045f   // cmp	x2, #1
	BLT  LBB0_3
	WORD $0xaa1f03e8   // mov	x8, xzr
	WORD $0x91004009   // add	x9, x0, #16

LBB0_2:
	WORD $0xad7f8520 // ldp	q0, q1, [x9, #-16]
	WORD $0x91002108 // add	x8, x8, #8
	WORD $0xeb02011f // cmp	x8, x2
	WORD $0x91008129 // add	x9, x9, #32
	WORD $0x0e216800 // fcvtn	v0.4h, v0.4s
	WORD $0x4e216820 // fcvtn2	v0.8h, v1.4s
	WORD $0x3c810420 // str	q0, [x1], #16
	BLT  LBB0_2

LBB0_3:
	RET

TEXT ·vto_float32(SB), $0-24
	MOVD a+0(FP), R0
	MOVD dst+8(FP), R1
	MOVD n+16(FP), R2
	WORD $0xf100045f   // cmp	x2, #1
	BLT  LBB1_3
	WORD $0xaa1f03e8   // mov	x8, xzr
	WORD $0x91004029   // add	x9, x1, #16

LBB1_2:
	WORD $0x3cc10400 // ldr	q0, [x0], #16
	WORD $0x91002108 // add	x8, x8, #8
	WORD $0xeb02011f // cmp	x8, x2
	WORD $0x0e217801 // fcvtl	v1.4s, v0.4h
	WORD $0x4e217800 // fcvtl2	v0.4s, v0.8h
	WORD $0xad3f8121 // stp	q1, q0, [x9, #-16]
	WORD $0x91008129 // add	x9, x9, #32
	BLT  LBB1_2

LBB1_3:
	RET
