//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   19.1.7 (++20250114103320+cd708029e0b2-1~exp1~20250114103432.75)
// 	objdump 2.38
// flags: -mavx -mfma -mavx512f -O3
// source: src/floats_avx512.c

package floats

import "unsafe"

//go:noescape
func _mm512_mul_const_add_to(a, b, c, dst unsafe.Pointer, n int64)

//go:noescape
func _mm512_mul_const_add(a, b, c unsafe.Pointer, n int64)

//go:noescape
func _mm512_mul_const_to(a, b, c unsafe.Pointer, n int64)

//go:noescape
func _mm512_mul_const(a, b unsafe.Pointer, n int64)

//go:noescape
func _mm512_add_const(a, b unsafe.Pointer, n int64)

//go:noescape
func _mm512_sub_to(a, b, c unsafe.Pointer, n int64)

//go:noescape
func _mm512_sub(a, b unsafe.Pointer, n int64)

//go:noescape
func _mm512_mul_to(a, b, c unsafe.Pointer, n int64)

//go:noescape
func _mm512_div_to(a, b, c unsafe.Pointer, n int64)

//go:noescape
func _mm512_sqrt_to(a, b unsafe.Pointer, n int64)

//go:noescape
func _mm512_dot(a, b unsafe.Pointer, n int64) (result float32)

//go:noescape
func _mm512_euclidean(a, b unsafe.Pointer, n int64) (result float32)

//go:noescape
func _mm512_mm(transA, transB bool, m, n, k int64, a unsafe.Pointer, lda int64, b unsafe.Pointer, ldb int64, c unsafe.Pointer, ldc int64)
