//go:build !noasm && riscv64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -march=rv64imafdv -isystem /usr/lib/llvm-21/lib/clang/21/include -O3
// source: src/floats_rvv.c

TEXT ·vmul_const_add_to(SB), $0-40
	MOV  a+0(FP), A0
	MOV  b+8(FP), A1
	MOV  c+16(FP), A2
	MOV  dst+24(FP), A3
	MOV  n+32(FP), A4
	BLEZ A4, LBB0_7
	WORD $0xc22028f3    // csrr	a7, vlenb
	WORD $0x0018d293    // srli	t0, a7, 1
	WORD $0x01800793    // li	a5, 24
	WORD $0x00028813    // mv	a6, t0
	BLTU A5, T0, LBB0_3
	WORD $0x01800813    // li	a6, 24

LBB0_3:
	WORD $0x00271793    // slli	a5, a4, 2
	BGEU A4, A6, LBB0_8
	WORD $0x00000813    // li	a6, 0

LBB0_5:
	WORD $0x00281813 // slli	a6, a6, 2
	WORD $0x01068733 // add	a4, a3, a6
	WORD $0x01060633 // add	a2, a2, a6
	WORD $0x01050533 // add	a0, a0, a6
	WORD $0x00f686b3 // add	a3, a3, a5

LBB0_6:
	WORD $0x00052787    // flw	fa5, 0(a0)
	WORD $0x0005a707    // flw	fa4, 0(a1)
	WORD $0x00062687    // flw	fa3, 0(a2)
	WORD $0x68e7f7c3    // fmadd.s	fa5, fa5, fa4, fa3
	WORD $0x00f72027    // fsw	fa5, 0(a4)
	WORD $0x00470713    // addi	a4, a4, 4
	WORD $0x00460613    // addi	a2, a2, 4
	WORD $0x00450513    // addi	a0, a0, 4
	BNE  A4, A3, LBB0_6

LBB0_7:
	RET

LBB0_8:
	WORD $0x00f68333 // add	t1, a3, a5
	WORD $0x00f50833 // add	a6, a0, a5
	WORD $0x0106b833 // sltu	a6, a3, a6
	WORD $0x006533b3 // sltu	t2, a0, t1
	WORD $0x007873b3 // and	t2, a6, t2
	WORD $0x00000813 // li	a6, 0
	BNEZ T2, LBB0_5
	WORD $0x00458393 // addi	t2, a1, 4
	WORD $0x0076b3b3 // sltu	t2, a3, t2
	WORD $0x0065be33 // sltu	t3, a1, t1
	WORD $0x01c3f3b3 // and	t2, t2, t3
	BNEZ T2, LBB0_5
	WORD $0x00f603b3 // add	t2, a2, a5
	WORD $0x0076b3b3 // sltu	t2, a3, t2
	WORD $0x00663333 // sltu	t1, a2, t1
	WORD $0x0063f333 // and	t1, t2, t1
	BNEZ T1, LBB0_5
	WORD $0x40500833 // neg	a6, t0
	WORD $0x01077833 // and	a6, a4, a6
	WORD $0x40580333 // sub	t1, a6, t0
	WORD $0x025352b3 // divu	t0, t1, t0
	WORD $0x0038d313 // srli	t1, a7, 3
	WORD $0x0005a787 // flw	fa5, 0(a1)
	WORD $0x00431893 // slli	a7, t1, 4
	WORD $0x00429293 // slli	t0, t0, 4
	WORD $0x01028293 // addi	t0, t0, 16
	WORD $0x026282b3 // mul	t0, t0, t1
	WORD $0x005682b3 // add	t0, a3, t0
	WORD $0x00050313 // mv	t1, a0
	WORD $0x00060393 // mv	t2, a2
	WORD $0x00068e13 // mv	t3, a3
	WORD $0x0d107ed7 // vsetvli	t4, zero, e32, m2, ta, ma

LBB0_12:
	WORD $0x22836407     // vl2re32.v	v8, (t1)
	WORD $0x2283e507     // vl2re32.v	v10, (t2)
	WORD $0xb287d557     // vfmacc.vf	v10, fa5, v8
	WORD $0x228e0527     // vs2r.v	v10, (t3)
	WORD $0x011e0e33     // add	t3, t3, a7
	WORD $0x011383b3     // add	t2, t2, a7
	WORD $0x01130333     // add	t1, t1, a7
	BNE  T3, T0, LBB0_12
	BNE  A4, A6, LBB0_5
	JMP  LBB0_7

TEXT ·vmul_const_add(SB), $0-32
	MOV  a+0(FP), A0
	MOV  b+8(FP), A1
	MOV  c+16(FP), A2
	MOV  n+24(FP), A3
	BLEZ A3, LBB1_7
	WORD $0xc2202873    // csrr	a6, vlenb
	WORD $0x00185893    // srli	a7, a6, 1
	WORD $0x01000713    // li	a4, 16
	WORD $0x00088793    // mv	a5, a7
	BLTU A4, A7, LBB1_3
	WORD $0x01000793    // li	a5, 16

LBB1_3:
	WORD $0x00269713    // slli	a4, a3, 2
	BGEU A3, A5, LBB1_8
	WORD $0x00000793    // li	a5, 0

LBB1_5:
	WORD $0x00279793 // slli	a5, a5, 2
	WORD $0x00f606b3 // add	a3, a2, a5
	WORD $0x00f50533 // add	a0, a0, a5
	WORD $0x00e60633 // add	a2, a2, a4

LBB1_6:
	WORD $0x00052787    // flw	fa5, 0(a0)
	WORD $0x0005a707    // flw	fa4, 0(a1)
	WORD $0x0006a687    // flw	fa3, 0(a3)
	WORD $0x68e7f7c3    // fmadd.s	fa5, fa5, fa4, fa3
	WORD $0x00f6a027    // fsw	fa5, 0(a3)
	WORD $0x00468693    // addi	a3, a3, 4
	WORD $0x00450513    // addi	a0, a0, 4
	BNE  A3, A2, LBB1_6

LBB1_7:
	RET

LBB1_8:
	WORD $0x00e602b3 // add	t0, a2, a4
	WORD $0x00e507b3 // add	a5, a0, a4
	WORD $0x00f637b3 // sltu	a5, a2, a5
	WORD $0x00553333 // sltu	t1, a0, t0
	WORD $0x0067f333 // and	t1, a5, t1
	WORD $0x00000793 // li	a5, 0
	BNEZ T1, LBB1_5
	WORD $0x00458313 // addi	t1, a1, 4
	WORD $0x00663333 // sltu	t1, a2, t1
	WORD $0x0055b2b3 // sltu	t0, a1, t0
	WORD $0x005372b3 // and	t0, t1, t0
	BNEZ T0, LBB1_5
	WORD $0x411007b3 // neg	a5, a7
	WORD $0x00f6f7b3 // and	a5, a3, a5
	WORD $0x411782b3 // sub	t0, a5, a7
	WORD $0x0312d8b3 // divu	a7, t0, a7
	WORD $0x00385293 // srli	t0, a6, 3
	WORD $0x0005a787 // flw	fa5, 0(a1)
	WORD $0x00429813 // slli	a6, t0, 4
	WORD $0x00489893 // slli	a7, a7, 4
	WORD $0x01088893 // addi	a7, a7, 16
	WORD $0x025888b3 // mul	a7, a7, t0
	WORD $0x011608b3 // add	a7, a2, a7
	WORD $0x00050293 // mv	t0, a0
	WORD $0x00060313 // mv	t1, a2
	WORD $0x0d1073d7 // vsetvli	t2, zero, e32, m2, ta, ma

LBB1_11:
	WORD $0x2282e407     // vl2re32.v	v8, (t0)
	WORD $0x22836507     // vl2re32.v	v10, (t1)
	WORD $0xb287d557     // vfmacc.vf	v10, fa5, v8
	WORD $0x22830527     // vs2r.v	v10, (t1)
	WORD $0x01030333     // add	t1, t1, a6
	WORD $0x010282b3     // add	t0, t0, a6
	BNE  T1, A7, LBB1_11
	BNE  A3, A5, LBB1_5
	JMP  LBB1_7

TEXT ·vmul_const_to(SB), $0-32
	MOV  a+0(FP), A0
	MOV  b+8(FP), A1
	MOV  c+16(FP), A2
	MOV  n+24(FP), A3
	BLEZ A3, LBB2_7
	WORD $0xc2202873    // csrr	a6, vlenb
	WORD $0x00185893    // srli	a7, a6, 1
	WORD $0x01000713    // li	a4, 16
	WORD $0x00088793    // mv	a5, a7
	BLTU A4, A7, LBB2_3
	WORD $0x01000793    // li	a5, 16

LBB2_3:
	WORD $0x00269713    // slli	a4, a3, 2
	BGEU A3, A5, LBB2_8
	WORD $0x00000793    // li	a5, 0

LBB2_5:
	WORD $0x00279793 // slli	a5, a5, 2
	WORD $0x00f606b3 // add	a3, a2, a5
	WORD $0x00f50533 // add	a0, a0, a5
	WORD $0x00e60633 // add	a2, a2, a4

LBB2_6:
	WORD $0x00052787    // flw	fa5, 0(a0)
	WORD $0x0005a707    // flw	fa4, 0(a1)
	WORD $0x10e7f7d3    // fmul.s	fa5, fa5, fa4
	WORD $0x00f6a027    // fsw	fa5, 0(a3)
	WORD $0x00468693    // addi	a3, a3, 4
	WORD $0x00450513    // addi	a0, a0, 4
	BNE  A3, A2, LBB2_6

LBB2_7:
	RET

LBB2_8:
	WORD $0x00e602b3 // add	t0, a2, a4
	WORD $0x00e507b3 // add	a5, a0, a4
	WORD $0x00f637b3 // sltu	a5, a2, a5
	WORD $0x00553333 // sltu	t1, a0, t0
	WORD $0x0067f333 // and	t1, a5, t1
	WORD $0x00000793 // li	a5, 0
	BNEZ T1, LBB2_5
	WORD $0x00458313 // addi	t1, a1, 4
	WORD $0x00663333 // sltu	t1, a2, t1
	WORD $0x0055b2b3 // sltu	t0, a1, t0
	WORD $0x005372b3 // and	t0, t1, t0
	BNEZ T0, LBB2_5
	WORD $0x411007b3 // neg	a5, a7
	WORD $0x00f6f7b3 // and	a5, a3, a5
	WORD $0x411782b3 // sub	t0, a5, a7
	WORD $0x0312d8b3 // divu	a7, t0, a7
	WORD $0x00385293 // srli	t0, a6, 3
	WORD $0x0005a787 // flw	fa5, 0(a1)
	WORD $0x00429813 // slli	a6, t0, 4
	WORD $0x00489893 // slli	a7, a7, 4
	WORD $0x01088893 // addi	a7, a7, 16
	WORD $0x025888b3 // mul	a7, a7, t0
	WORD $0x011608b3 // add	a7, a2, a7
	WORD $0x00050293 // mv	t0, a0
	WORD $0x00060313 // mv	t1, a2
	WORD $0x0d1073d7 // vsetvli	t2, zero, e32, m2, ta, ma

LBB2_11:
	WORD $0x2282e407     // vl2re32.v	v8, (t0)
	WORD $0x9287d457     // vfmul.vf	v8, v8, fa5
	WORD $0x22830427     // vs2r.v	v8, (t1)
	WORD $0x01030333     // add	t1, t1, a6
	WORD $0x010282b3     // add	t0, t0, a6
	BNE  T1, A7, LBB2_11
	BNE  A3, A5, LBB2_5
	JMP  LBB2_7

TEXT ·vmul_const(SB), $0-24
	MOV  a+0(FP), A0
	MOV  b+8(FP), A1
	MOV  n+16(FP), A2
	BLEZ A2, LBB3_9
	WORD $0xc22027f3    // csrr	a5, vlenb
	WORD $0x0017d813    // srli	a6, a5, 1
	WORD $0x00800693    // li	a3, 8
	WORD $0x00080713    // mv	a4, a6
	BLTU A3, A6, LBB3_3
	WORD $0x00800713    // li	a4, 8

LBB3_3:
	WORD $0x00261693     // slli	a3, a2, 2
	BLTU A2, A4, LBB3_6
	WORD $0x00458713     // addi	a4, a1, 4
	BGEU A0, A4, LBB3_10
	WORD $0x00d50733     // add	a4, a0, a3
	BGEU A1, A4, LBB3_10

LBB3_6:
	WORD $0x00000713 // li	a4, 0

LBB3_7:
	WORD $0x00271613 // slli	a2, a4, 2
	WORD $0x00c50633 // add	a2, a0, a2
	WORD $0x00d50533 // add	a0, a0, a3

LBB3_8:
	WORD $0x0005a787    // flw	fa5, 0(a1)
	WORD $0x00062707    // flw	fa4, 0(a2)
	WORD $0x10e7f7d3    // fmul.s	fa5, fa5, fa4
	WORD $0x00f62027    // fsw	fa5, 0(a2)
	WORD $0x00460613    // addi	a2, a2, 4
	BNE  A2, A0, LBB3_8

LBB3_9:
	RET

LBB3_10:
	WORD $0x41000733 // neg	a4, a6
	WORD $0x00e67733 // and	a4, a2, a4
	WORD $0x410708b3 // sub	a7, a4, a6
	WORD $0x0308d833 // divu	a6, a7, a6
	WORD $0x0037d893 // srli	a7, a5, 3
	WORD $0x0005a787 // flw	fa5, 0(a1)
	WORD $0x00489793 // slli	a5, a7, 4
	WORD $0x00481813 // slli	a6, a6, 4
	WORD $0x01080813 // addi	a6, a6, 16
	WORD $0x03180833 // mul	a6, a6, a7
	WORD $0x01050833 // add	a6, a0, a6
	WORD $0x00050893 // mv	a7, a0
	WORD $0x0d1072d7 // vsetvli	t0, zero, e32, m2, ta, ma

LBB3_11:
	WORD $0x2288e407     // vl2re32.v	v8, (a7)
	WORD $0x9287d457     // vfmul.vf	v8, v8, fa5
	WORD $0x22888427     // vs2r.v	v8, (a7)
	WORD $0x00f888b3     // add	a7, a7, a5
	BNE  A7, A6, LBB3_11
	BEQ  A2, A4, LBB3_9
	JMP  LBB3_7

TEXT ·vadd_const(SB), $0-24
	MOV  a+0(FP), A0
	MOV  b+8(FP), A1
	MOV  n+16(FP), A2
	BLEZ A2, LBB4_9
	WORD $0xc22027f3    // csrr	a5, vlenb
	WORD $0x0017d813    // srli	a6, a5, 1
	WORD $0x00800693    // li	a3, 8
	WORD $0x00080713    // mv	a4, a6
	BLTU A3, A6, LBB4_3
	WORD $0x00800713    // li	a4, 8

LBB4_3:
	WORD $0x00261693     // slli	a3, a2, 2
	BLTU A2, A4, LBB4_6
	WORD $0x00458713     // addi	a4, a1, 4
	BGEU A0, A4, LBB4_10
	WORD $0x00d50733     // add	a4, a0, a3
	BGEU A1, A4, LBB4_10

LBB4_6:
	WORD $0x00000713 // li	a4, 0

LBB4_7:
	WORD $0x00271613 // slli	a2, a4, 2
	WORD $0x00c50633 // add	a2, a0, a2
	WORD $0x00d50533 // add	a0, a0, a3

LBB4_8:
	WORD $0x0005a787    // flw	fa5, 0(a1)
	WORD $0x00062707    // flw	fa4, 0(a2)
	WORD $0x00e7f7d3    // fadd.s	fa5, fa5, fa4
	WORD $0x00f62027    // fsw	fa5, 0(a2)
	WORD $0x00460613    // addi	a2, a2, 4
	BNE  A2, A0, LBB4_8

LBB4_9:
	RET

LBB4_10:
	WORD $0x41000733 // neg	a4, a6
	WORD $0x00e67733 // and	a4, a2, a4
	WORD $0x410708b3 // sub	a7, a4, a6
	WORD $0x0308d833 // divu	a6, a7, a6
	WORD $0x0037d893 // srli	a7, a5, 3
	WORD $0x0005a787 // flw	fa5, 0(a1)
	WORD $0x00489793 // slli	a5, a7, 4
	WORD $0x00481813 // slli	a6, a6, 4
	WORD $0x01080813 // addi	a6, a6, 16
	WORD $0x03180833 // mul	a6, a6, a7
	WORD $0x01050833 // add	a6, a0, a6
	WORD $0x00050893 // mv	a7, a0
	WORD $0x0d1072d7 // vsetvli	t0, zero, e32, m2, ta, ma

LBB4_11:
	WORD $0x2288e407     // vl2re32.v	v8, (a7)
	WORD $0x0287d457     // vfadd.vf	v8, v8, fa5
	WORD $0x22888427     // vs2r.v	v8, (a7)
	WORD $0x00f888b3     // add	a7, a7, a5
	BNE  A7, A6, LBB4_11
	BEQ  A2, A4, LBB4_9
	JMP  LBB4_7

TEXT ·vsub_to(SB), $0-32
	MOV  a+0(FP), A0
	MOV  b+8(FP), A1
	MOV  c+16(FP), A2
	MOV  n+24(FP), A3
	BLEZ A3, LBB5_7
	WORD $0xc2202873    // csrr	a6, vlenb
	WORD $0x00185893    // srli	a7, a6, 1
	WORD $0x01000793    // li	a5, 16
	WORD $0x00088713    // mv	a4, a7
	BLTU A5, A7, LBB5_3
	WORD $0x01000713    // li	a4, 16

LBB5_3:
	BGEU A3, A4, LBB5_8
	WORD $0x00000713    // li	a4, 0

LBB5_5:
	WORD $0x00271713 // slli	a4, a4, 2
	WORD $0x00269793 // slli	a5, a3, 2
	WORD $0x00e606b3 // add	a3, a2, a4
	WORD $0x00e585b3 // add	a1, a1, a4
	WORD $0x00e50533 // add	a0, a0, a4
	WORD $0x00f60633 // add	a2, a2, a5

LBB5_6:
	WORD $0x00052787    // flw	fa5, 0(a0)
	WORD $0x0005a707    // flw	fa4, 0(a1)
	WORD $0x08e7f7d3    // fsub.s	fa5, fa5, fa4
	WORD $0x00f6a027    // fsw	fa5, 0(a3)
	WORD $0x00468693    // addi	a3, a3, 4
	WORD $0x00458593    // addi	a1, a1, 4
	WORD $0x00450513    // addi	a0, a0, 4
	BNE  A3, A2, LBB5_6

LBB5_7:
	RET

LBB5_8:
	WORD $0x00181793    // slli	a5, a6, 1
	WORD $0x40a602b3    // sub	t0, a2, a0
	WORD $0x00000713    // li	a4, 0
	BLTU T0, A5, LBB5_5
	WORD $0x40b602b3    // sub	t0, a2, a1
	BLTU T0, A5, LBB5_5
	WORD $0x41100733    // neg	a4, a7
	WORD $0x00e6f733    // and	a4, a3, a4
	WORD $0x411702b3    // sub	t0, a4, a7
	WORD $0x0312d8b3    // divu	a7, t0, a7
	WORD $0x00385813    // srli	a6, a6, 3
	WORD $0x00489893    // slli	a7, a7, 4
	WORD $0x01088893    // addi	a7, a7, 16
	WORD $0x03088833    // mul	a6, a7, a6
	WORD $0x01060833    // add	a6, a2, a6
	WORD $0x00050893    // mv	a7, a0
	WORD $0x00058293    // mv	t0, a1
	WORD $0x00060313    // mv	t1, a2
	WORD $0x0d1073d7    // vsetvli	t2, zero, e32, m2, ta, ma

LBB5_11:
	WORD $0x2288e407     // vl2re32.v	v8, (a7)
	WORD $0x2282e507     // vl2re32.v	v10, (t0)
	WORD $0x0a851457     // vfsub.vv	v8, v8, v10
	WORD $0x22830427     // vs2r.v	v8, (t1)
	WORD $0x00f30333     // add	t1, t1, a5
	WORD $0x00f282b3     // add	t0, t0, a5
	WORD $0x00f888b3     // add	a7, a7, a5
	BNE  T1, A6, LBB5_11
	BNE  A3, A4, LBB5_5
	JMP  LBB5_7

TEXT ·vsub(SB), $0-24
	MOV  a+0(FP), A0
	MOV  b+8(FP), A1
	MOV  n+16(FP), A2
	BLEZ A2, LBB6_9
	WORD $0xc22027f3    // csrr	a5, vlenb
	WORD $0x0017d813    // srli	a6, a5, 1
	WORD $0x01000693    // li	a3, 16
	WORD $0x00080713    // mv	a4, a6
	BLTU A3, A6, LBB6_3
	WORD $0x01000713    // li	a4, 16

LBB6_3:
	WORD $0x00261693     // slli	a3, a2, 2
	BLTU A2, A4, LBB6_6
	WORD $0x00d58733     // add	a4, a1, a3
	BGEU A0, A4, LBB6_10
	WORD $0x00d50733     // add	a4, a0, a3
	BGEU A1, A4, LBB6_10

LBB6_6:
	WORD $0x00000713 // li	a4, 0

LBB6_7:
	WORD $0x00271713 // slli	a4, a4, 2
	WORD $0x00e50633 // add	a2, a0, a4
	WORD $0x00e585b3 // add	a1, a1, a4
	WORD $0x00d50533 // add	a0, a0, a3

LBB6_8:
	WORD $0x0005a787    // flw	fa5, 0(a1)
	WORD $0x00062707    // flw	fa4, 0(a2)
	WORD $0x08f777d3    // fsub.s	fa5, fa4, fa5
	WORD $0x00f62027    // fsw	fa5, 0(a2)
	WORD $0x00460613    // addi	a2, a2, 4
	WORD $0x00458593    // addi	a1, a1, 4
	BNE  A2, A0, LBB6_8

LBB6_9:
	RET

LBB6_10:
	WORD $0x41000733 // neg	a4, a6
	WORD $0x00e67733 // and	a4, a2, a4
	WORD $0x410708b3 // sub	a7, a4, a6
	WORD $0x0308d833 // divu	a6, a7, a6
	WORD $0x0037d893 // srli	a7, a5, 3
	WORD $0x00489793 // slli	a5, a7, 4
	WORD $0x00481813 // slli	a6, a6, 4
	WORD $0x01080813 // addi	a6, a6, 16
	WORD $0x03180833 // mul	a6, a6, a7
	WORD $0x01050833 // add	a6, a0, a6
	WORD $0x00058893 // mv	a7, a1
	WORD $0x00050293 // mv	t0, a0
	WORD $0x0d107357 // vsetvli	t1, zero, e32, m2, ta, ma

LBB6_11:
	WORD $0x2288e407     // vl2re32.v	v8, (a7)
	WORD $0x2282e507     // vl2re32.v	v10, (t0)
	WORD $0x0aa41457     // vfsub.vv	v8, v10, v8
	WORD $0x22828427     // vs2r.v	v8, (t0)
	WORD $0x00f282b3     // add	t0, t0, a5
	WORD $0x00f888b3     // add	a7, a7, a5
	BNE  T0, A6, LBB6_11
	BEQ  A2, A4, LBB6_9
	JMP  LBB6_7

TEXT ·vmul_to(SB), $0-32
	MOV  a+0(FP), A0
	MOV  b+8(FP), A1
	MOV  c+16(FP), A2
	MOV  n+24(FP), A3
	BLEZ A3, LBB7_7
	WORD $0xc2202873    // csrr	a6, vlenb
	WORD $0x00185893    // srli	a7, a6, 1
	WORD $0x01000793    // li	a5, 16
	WORD $0x00088713    // mv	a4, a7
	BLTU A5, A7, LBB7_3
	WORD $0x01000713    // li	a4, 16

LBB7_3:
	BGEU A3, A4, LBB7_8
	WORD $0x00000713    // li	a4, 0

LBB7_5:
	WORD $0x00271713 // slli	a4, a4, 2
	WORD $0x00269793 // slli	a5, a3, 2
	WORD $0x00e606b3 // add	a3, a2, a4
	WORD $0x00e585b3 // add	a1, a1, a4
	WORD $0x00e50533 // add	a0, a0, a4
	WORD $0x00f60633 // add	a2, a2, a5

LBB7_6:
	WORD $0x00052787    // flw	fa5, 0(a0)
	WORD $0x0005a707    // flw	fa4, 0(a1)
	WORD $0x10e7f7d3    // fmul.s	fa5, fa5, fa4
	WORD $0x00f6a027    // fsw	fa5, 0(a3)
	WORD $0x00468693    // addi	a3, a3, 4
	WORD $0x00458593    // addi	a1, a1, 4
	WORD $0x00450513    // addi	a0, a0, 4
	BNE  A3, A2, LBB7_6

LBB7_7:
	RET

LBB7_8:
	WORD $0x00181793    // slli	a5, a6, 1
	WORD $0x40a602b3    // sub	t0, a2, a0
	WORD $0x00000713    // li	a4, 0
	BLTU T0, A5, LBB7_5
	WORD $0x40b602b3    // sub	t0, a2, a1
	BLTU T0, A5, LBB7_5
	WORD $0x41100733    // neg	a4, a7
	WORD $0x00e6f733    // and	a4, a3, a4
	WORD $0x411702b3    // sub	t0, a4, a7
	WORD $0x0312d8b3    // divu	a7, t0, a7
	WORD $0x00385813    // srli	a6, a6, 3
	WORD $0x00489893    // slli	a7, a7, 4
	WORD $0x01088893    // addi	a7, a7, 16
	WORD $0x03088833    // mul	a6, a7, a6
	WORD $0x01060833    // add	a6, a2, a6
	WORD $0x00050893    // mv	a7, a0
	WORD $0x00058293    // mv	t0, a1
	WORD $0x00060313    // mv	t1, a2
	WORD $0x0d1073d7    // vsetvli	t2, zero, e32, m2, ta, ma

LBB7_11:
	WORD $0x2288e407     // vl2re32.v	v8, (a7)
	WORD $0x2282e507     // vl2re32.v	v10, (t0)
	WORD $0x92851457     // vfmul.vv	v8, v8, v10
	WORD $0x22830427     // vs2r.v	v8, (t1)
	WORD $0x00f30333     // add	t1, t1, a5
	WORD $0x00f282b3     // add	t0, t0, a5
	WORD $0x00f888b3     // add	a7, a7, a5
	BNE  T1, A6, LBB7_11
	BNE  A3, A4, LBB7_5
	JMP  LBB7_7

TEXT ·vdiv_to(SB), $0-32
	MOV  a+0(FP), A0
	MOV  b+8(FP), A1
	MOV  c+16(FP), A2
	MOV  n+24(FP), A3
	BLEZ A3, LBB8_7
	WORD $0xc2202873    // csrr	a6, vlenb
	WORD $0x00185893    // srli	a7, a6, 1
	WORD $0x01000793    // li	a5, 16
	WORD $0x00088713    // mv	a4, a7
	BLTU A5, A7, LBB8_3
	WORD $0x01000713    // li	a4, 16

LBB8_3:
	BGEU A3, A4, LBB8_8
	WORD $0x00000713    // li	a4, 0

LBB8_5:
	WORD $0x00271713 // slli	a4, a4, 2
	WORD $0x00269793 // slli	a5, a3, 2
	WORD $0x00e606b3 // add	a3, a2, a4
	WORD $0x00e585b3 // add	a1, a1, a4
	WORD $0x00e50533 // add	a0, a0, a4
	WORD $0x00f60633 // add	a2, a2, a5

LBB8_6:
	WORD $0x00052787    // flw	fa5, 0(a0)
	WORD $0x0005a707    // flw	fa4, 0(a1)
	WORD $0x18e7f7d3    // fdiv.s	fa5, fa5, fa4
	WORD $0x00f6a027    // fsw	fa5, 0(a3)
	WORD $0x00468693    // addi	a3, a3, 4
	WORD $0x00458593    // addi	a1, a1, 4
	WORD $0x00450513    // addi	a0, a0, 4
	BNE  A3, A2, LBB8_6

LBB8_7:
	RET

LBB8_8:
	WORD $0x00181793    // slli	a5, a6, 1
	WORD $0x40a602b3    // sub	t0, a2, a0
	WORD $0x00000713    // li	a4, 0
	BLTU T0, A5, LBB8_5
	WORD $0x40b602b3    // sub	t0, a2, a1
	BLTU T0, A5, LBB8_5
	WORD $0x41100733    // neg	a4, a7
	WORD $0x00e6f733    // and	a4, a3, a4
	WORD $0x411702b3    // sub	t0, a4, a7
	WORD $0x0312d8b3    // divu	a7, t0, a7
	WORD $0x00385813    // srli	a6, a6, 3
	WORD $0x00489893    // slli	a7, a7, 4
	WORD $0x01088893    // addi	a7, a7, 16
	WORD $0x03088833    // mul	a6, a7, a6
	WORD $0x01060833    // add	a6, a2, a6
	WORD $0x00050893    // mv	a7, a0
	WORD $0x00058293    // mv	t0, a1
	WORD $0x00060313    // mv	t1, a2
	WORD $0x0d1073d7    // vsetvli	t2, zero, e32, m2, ta, ma

LBB8_11:
	WORD $0x2288e407     // vl2re32.v	v8, (a7)
	WORD $0x2282e507     // vl2re32.v	v10, (t0)
	WORD $0x82851457     // vfdiv.vv	v8, v8, v10
	WORD $0x22830427     // vs2r.v	v8, (t1)
	WORD $0x00f30333     // add	t1, t1, a5
	WORD $0x00f282b3     // add	t0, t0, a5
	WORD $0x00f888b3     // add	a7, a7, a5
	BNE  T1, A6, LBB8_11
	BNE  A3, A4, LBB8_5
	JMP  LBB8_7

TEXT ·vsqrt_to(SB), $0-24
	MOV  a+0(FP), A0
	MOV  b+8(FP), A1
	MOV  n+16(FP), A2
	BLEZ A2, LBB9_2

LBB9_1:
	WORD $0x0d0676d7 // vsetvli	a3, a2, e32, m1, ta, ma
	WORD $0x02056407 // vle32.v	v8, (a0)
	WORD $0x4e801457 // vfsqrt.v	v8, v8
	WORD $0x00269713 // slli	a4, a3, 2
	WORD $0x40d60633 // sub	a2, a2, a3
	WORD $0x00e50533 // add	a0, a0, a4
	WORD $0x0205e427 // vse32.v	v8, (a1)
	WORD $0x00e585b3 // add	a1, a1, a4
	BGTZ A2, LBB9_1

LBB9_2:
	RET

TEXT ·vdot(SB), $8-28
	MOV  a+0(FP), A0
	MOV  b+8(FP), A1
	MOV  n+16(FP), A2
	WORD $0x0d0076d7  // vsetvli	a3, zero, e32, m1, ta, ma
	WORD $0x02d65733  // divu	a4, a2, a3
	WORD $0x0007079b  // sext.w	a5, a4
	WORD $0x5e003457  // vmv.v.i	v8, 0
	BLEZ A5, LBB10_3
	WORD $0x00000813  // li	a6, 0
	WORD $0x00269893  // slli	a7, a3, 2
	WORD $0x9e8034d7  // vmv1r.v	v9, v8

LBB10_2:
	WORD $0x02056507     // vle32.v	v10, (a0)
	WORD $0x0205e587     // vle32.v	v11, (a1)
	WORD $0x0018081b     // addiw	a6, a6, 1
	WORD $0x01150533     // add	a0, a0, a7
	WORD $0xb2a594d7     // vfmacc.vv	v9, v11, v10
	WORD $0x011585b3     // add	a1, a1, a7
	BLT  A6, A5, LBB10_2
	JMP  LBB10_4

LBB10_3:
	WORD $0x9e8034d7 // vmv1r.v	v9, v8

LBB10_4:
	WORD $0x02d706b3        // mul	a3, a4, a3
	WORD $0x40d60633        // sub	a2, a2, a3
	WORD $0x0d067057        // vsetvli	zero, a2, e32, m1, ta, ma
	WORD $0x02056507        // vle32.v	v10, (a0)
	WORD $0x0205e587        // vle32.v	v11, (a1)
	WORD $0x0d007557        // vsetvli	a0, zero, e32, m1, ta, ma
	WORD $0x0e941457        // vfredosum.vs	v8, v9, v8
	WORD $0x0d067057        // vsetvli	zero, a2, e32, m1, ta, ma
	WORD $0x92a594d7        // vfmul.vv	v9, v10, v11
	WORD $0x0e941457        // vfredosum.vs	v8, v9, v8
	WORD $0x42801557        // vfmv.f.s	fa0, v8
	MOVF FA0, result+24(FP)
	RET

TEXT ·veuclidean(SB), $8-28
	MOV  a+0(FP), A0
	MOV  b+8(FP), A1
	MOV  n+16(FP), A2
	WORD $0x0d0076d7  // vsetvli	a3, zero, e32, m1, ta, ma
	WORD $0x02d65733  // divu	a4, a2, a3
	WORD $0x0007079b  // sext.w	a5, a4
	WORD $0x5e003457  // vmv.v.i	v8, 0
	BLEZ A5, LBB11_3
	WORD $0x00000813  // li	a6, 0
	WORD $0x00269893  // slli	a7, a3, 2
	WORD $0x9e8034d7  // vmv1r.v	v9, v8

LBB11_2:
	WORD $0x02056507     // vle32.v	v10, (a0)
	WORD $0x0205e587     // vle32.v	v11, (a1)
	WORD $0x0018081b     // addiw	a6, a6, 1
	WORD $0x01150533     // add	a0, a0, a7
	WORD $0x0aa59557     // vfsub.vv	v10, v10, v11
	WORD $0xb2a514d7     // vfmacc.vv	v9, v10, v10
	WORD $0x011585b3     // add	a1, a1, a7
	BLT  A6, A5, LBB11_2
	JMP  LBB11_4

LBB11_3:
	WORD $0x9e8034d7 // vmv1r.v	v9, v8

LBB11_4:
	WORD $0x02d706b3        // mul	a3, a4, a3
	WORD $0x40d60633        // sub	a2, a2, a3
	WORD $0x0d067057        // vsetvli	zero, a2, e32, m1, ta, ma
	WORD $0x02056507        // vle32.v	v10, (a0)
	WORD $0x0205e587        // vle32.v	v11, (a1)
	WORD $0x0d007557        // vsetvli	a0, zero, e32, m1, ta, ma
	WORD $0x0e941457        // vfredosum.vs	v8, v9, v8
	WORD $0x0d067057        // vsetvli	zero, a2, e32, m1, ta, ma
	WORD $0x0aa594d7        // vfsub.vv	v9, v10, v11
	WORD $0x929494d7        // vfmul.vv	v9, v9, v9
	WORD $0x0e941457        // vfredosum.vs	v8, v9, v8
	WORD $0x0d007557        // vsetvli	a0, zero, e32, m1, ta, ma
	WORD $0x4e801457        // vfsqrt.v	v8, v8
	WORD $0x42801557        // vfmv.f.s	fa0, v8
	MOVF FA0, result+24(FP)
	RET

TEXT ·vmm(SB), $0-80
	MOVB transA+0(FP), A0
	MOVB transB+1(FP), A1
	MOV  m+8(FP), A2
	MOV  n+16(FP), A3
	MOV  k+24(FP), A4
	MOV  a+32(FP), A5
	MOV  lda+40(FP), A6
	MOV  b+48(FP), A7
	MOV  ldb+56(FP), T0
	ADDI -24, SP, SP
	MOV  T0, 0(SP)
	ADDI 24, SP, SP
	MOV  c+64(FP), T0
	ADDI -24, SP, SP
	MOV  T0, 8(SP)
	ADDI 24, SP, SP
	MOV  ldc+72(FP), T0
	ADDI -24, SP, SP
	MOV  T0, 16(SP)
	WORD $0xf7010113       // addi	sp, sp, -144
	WORD $0x08113423       // sd	ra, 136(sp)                     # 8-byte Folded Spill
	WORD $0x08813023       // sd	s0, 128(sp)                     # 8-byte Folded Spill
	WORD $0x06913c23       // sd	s1, 120(sp)                     # 8-byte Folded Spill
	WORD $0x07213823       // sd	s2, 112(sp)                     # 8-byte Folded Spill
	WORD $0x07313423       // sd	s3, 104(sp)                     # 8-byte Folded Spill
	WORD $0x07413023       // sd	s4, 96(sp)                      # 8-byte Folded Spill
	WORD $0x05513c23       // sd	s5, 88(sp)                      # 8-byte Folded Spill
	WORD $0x05613823       // sd	s6, 80(sp)                      # 8-byte Folded Spill
	WORD $0x05713423       // sd	s7, 72(sp)                      # 8-byte Folded Spill
	WORD $0x05813023       // sd	s8, 64(sp)                      # 8-byte Folded Spill
	WORD $0x03913c23       // sd	s9, 56(sp)                      # 8-byte Folded Spill
	WORD $0x03a13823       // sd	s10, 48(sp)                     # 8-byte Folded Spill
	WORD $0x00080c93       // mv	s9, a6
	WORD $0x00078c13       // mv	s8, a5
	WORD $0x00070313       // mv	t1, a4
	WORD $0x00060d13       // mv	s10, a2
	WORD $0x0a013603       // ld	a2, 160(sp)
	WORD $0x09813083       // ld	ra, 152(sp)
	WORD $0x09013283       // ld	t0, 144(sp)
	WORD $0x00f13823       // sd	a5, 16(sp)                      # 8-byte Folded Spill
	WORD $0x03013423       // sd	a6, 40(sp)                      # 8-byte Folded Spill
	BNEZ A0, LBB12_4
	BNEZ A1, LBB12_4
	WORD $0x00400513       // li	a0, 4
	WORD $0x00513423       // sd	t0, 8(sp)                       # 8-byte Folded Spill
	BGE  S10, A0, LBB12_36
	WORD $0x00000513       // li	a0, 0
	JMP  LBB12_49

LBB12_4:
	WORD $0x00154713   // xori	a4, a0, 1
	BEQZ A1, LBB12_17
	BEQZ A4, LBB12_17
	BLEZ S10, LBB12_84
	BLEZ A3, LBB12_84
	WORD $0x00000513   // li	a0, 0
	WORD $0x0d007757   // vsetvli	a4, zero, e32, m1, ta, ma
	WORD $0x02e35f33   // divu	t5, t1, a4
	WORD $0x00229393   // slli	t2, t0, 2
	WORD $0x00261593   // slli	a1, a2, 2
	WORD $0x002c9e13   // slli	t3, s9, 2
	WORD $0x5e003457   // vmv.v.i	v8, 0
	WORD $0x00271e93   // slli	t4, a4, 2
	WORD $0x02ef0733   // mul	a4, t5, a4
	WORD $0x000f0f1b   // sext.w	t5, t5
	WORD $0x40e30733   // sub	a4, t1, a4
	WORD $0x0d0077d7   // vsetvli	a5, zero, e32, m1, ta, ma
	WORD $0x0e8414d7   // vfredosum.vs	v9, v8, v8
	WORD $0x000c0f93   // mv	t6, s8
	WORD $0x00008413   // mv	s0, ra
	JMP  LBB12_10

LBB12_9:
	WORD $0x00150513       // addi	a0, a0, 1
	WORD $0x00b40433       // add	s0, s0, a1
	WORD $0x01cf8fb3       // add	t6, t6, t3
	BEQ  A0, S10, LBB12_84

LBB12_10:
	BLEZ T5, LBB12_15
	WORD $0x00000493  // li	s1, 0
	WORD $0x02c507b3  // mul	a5, a0, a2
	WORD $0x00279793  // slli	a5, a5, 2
	WORD $0x00f08933  // add	s2, ra, a5
	WORD $0x00088793  // mv	a5, a7

LBB12_12:
	WORD $0x00000813 // li	a6, 0
	WORD $0x00078293 // mv	t0, a5
	WORD $0x000f8313 // mv	t1, t6
	WORD $0xcc00f057 // vsetivli	zero, 1, e8, m1, ta, ma
	WORD $0x9e803557 // vmv1r.v	v10, v8

LBB12_13:
	WORD $0x0d0079d7      // vsetvli	s3, zero, e32, m1, ta, ma
	WORD $0x02036587      // vle32.v	v11, (t1)
	WORD $0x0202e607      // vle32.v	v12, (t0)
	WORD $0x0018081b      // addiw	a6, a6, 1
	WORD $0x01d30333      // add	t1, t1, t4
	WORD $0xb2b61557      // vfmacc.vv	v10, v12, v11
	WORD $0x01d282b3      // add	t0, t0, t4
	BLT  A6, T5, LBB12_13
	WORD $0x0ea41557      // vfredosum.vs	v10, v10, v8
	WORD $0x0d077057      // vsetvli	zero, a4, e32, m1, ta, ma
	WORD $0x02036587      // vle32.v	v11, (t1)
	WORD $0x0202e607      // vle32.v	v12, (t0)
	WORD $0x00249813      // slli	a6, s1, 2
	WORD $0x00148493      // addi	s1, s1, 1
	WORD $0x01090833      // add	a6, s2, a6
	WORD $0x92b615d7      // vfmul.vv	v11, v11, v12
	WORD $0x0eb51557      // vfredosum.vs	v10, v11, v10
	WORD $0xcd00f057      // vsetivli	zero, 1, e32, m1, ta, ma
	WORD $0x02086527      // vse32.v	v10, (a6)
	WORD $0x007787b3      // add	a5, a5, t2
	BNE  S1, A3, LBB12_12
	JMP  LBB12_9

LBB12_15:
	WORD $0x039507b3 // mul	a5, a0, s9
	WORD $0x00279793 // slli	a5, a5, 2
	WORD $0x00fc07b3 // add	a5, s8, a5
	WORD $0x00068813 // mv	a6, a3
	WORD $0x00040293 // mv	t0, s0
	WORD $0x00088313 // mv	t1, a7

LBB12_16:
	WORD $0x0d077057  // vsetvli	zero, a4, e32, m1, ta, ma
	WORD $0x0207e507  // vle32.v	v10, (a5)
	WORD $0x02036587  // vle32.v	v11, (t1)
	WORD $0x00730333  // add	t1, t1, t2
	WORD $0xfff80813  // addi	a6, a6, -1
	WORD $0x92a59557  // vfmul.vv	v10, v10, v11
	WORD $0x0ea49557  // vfredosum.vs	v10, v10, v9
	WORD $0xcd00f057  // vsetivli	zero, 1, e32, m1, ta, ma
	WORD $0x0202e527  // vse32.v	v10, (t0)
	WORD $0x00428293  // addi	t0, t0, 4
	BNEZ A6, LBB12_16
	JMP  LBB12_9

LBB12_17:
	WORD $0x00e5e733      // or	a4, a1, a4
	BEQZ A4, LBB12_46
	BLEZ S10, LBB12_84
	BLEZ T1, LBB12_84
	BLEZ A3, LBB12_84
	BEQZ A1, LBB12_84
	BEQZ A0, LBB12_84
	WORD $0x00269f13      // slli	t5, a3, 2
	WORD $0xfff30593      // addi	a1, t1, -1
	WORD $0x00d30733      // add	a4, t1, a3
	WORD $0xc2202573      // csrr	a0, vlenb
	WORD $0x02bc87b3      // mul	a5, s9, a1
	WORD $0x00271713      // slli	a4, a4, 2
	WORD $0x00155593      // srli	a1, a0, 1
	WORD $0x00279793      // slli	a5, a5, 2
	WORD $0x00e88eb3      // add	t4, a7, a4
	WORD $0x00800813      // li	a6, 8
	WORD $0x00fc0fb3      // add	t6, s8, a5
	WORD $0x00058713      // mv	a4, a1
	BLTU A6, A1, LBB12_25
	WORD $0x00800713      // li	a4, 8

LBB12_25:
	WORD $0x00000e13 // li	t3, 0
	WORD $0x00261613 // slli	a2, a2, 2
	WORD $0xffce8e93 // addi	t4, t4, -4
	WORD $0x01e08f33 // add	t5, ra, t5
	WORD $0x004f8f93 // addi	t6, t6, 4
	WORD $0x00e6b733 // sltu	a4, a3, a4
	WORD $0xfff28793 // addi	a5, t0, -1
	WORD $0x00100813 // li	a6, 1
	WORD $0x00151413 // slli	s0, a0, 1
	WORD $0x00229393 // slli	t2, t0, 2
	WORD $0xfff74713 // not	a4, a4
	WORD $0x0017b793 // seqz	a5, a5
	WORD $0x03d81813 // slli	a6, a6, 61
	WORD $0x00f77733 // and	a4, a4, a5
	WORD $0x010cf7b3 // and	a5, s9, a6
	WORD $0x00f034b3 // snez	s1, a5
	WORD $0xfff74913 // not	s2, a4
	WORD $0x00008993 // mv	s3, ra
	JMP  LBB12_27

LBB12_26:
	WORD $0x001e0e13       // addi	t3, t3, 1
	WORD $0x00c989b3       // add	s3, s3, a2
	WORD $0x01013c03       // ld	s8, 16(sp)                      # 8-byte Folded Reload
	BEQ  T3, S10, LBB12_84

LBB12_27:
	WORD $0x00000a13 // li	s4, 0
	WORD $0x03c60733 // mul	a4, a2, t3
	WORD $0x002e1793 // slli	a5, t3, 2
	WORD $0x00e08833 // add	a6, ra, a4
	WORD $0x00ef0733 // add	a4, t5, a4
	WORD $0x00fc0ab3 // add	s5, s8, a5
	WORD $0x00ff87b3 // add	a5, t6, a5
	WORD $0x00f837b3 // sltu	a5, a6, a5
	WORD $0x00eab2b3 // sltu	t0, s5, a4
	WORD $0x0057f7b3 // and	a5, a5, t0
	WORD $0x01d83833 // sltu	a6, a6, t4
	WORD $0x00e8b733 // sltu	a4, a7, a4
	WORD $0x00e87733 // and	a4, a6, a4
	WORD $0x0097e7b3 // or	a5, a5, s1
	WORD $0x00e96733 // or	a4, s2, a4
	WORD $0x00f76733 // or	a4, a4, a5
	WORD $0x00177b13 // andi	s6, a4, 1
	WORD $0x00088b93 // mv	s7, a7
	JMP  LBB12_29

LBB12_28:
	WORD $0x001a0a13      // addi	s4, s4, 1
	WORD $0x004b8b93      // addi	s7, s7, 4
	BEQ  S4, T1, LBB12_26

LBB12_29:
	WORD $0x039a0733  // mul	a4, s4, s9
	WORD $0x00271713  // slli	a4, a4, 2
	WORD $0x00ea8c33  // add	s8, s5, a4
	BEQZ S6, LBB12_31
	WORD $0x00000713  // li	a4, 0
	JMP  LBB12_34

LBB12_31:
	WORD $0x00155713 // srli	a4, a0, 1
	WORD $0x000c2787 // flw	fa5, 0(s8)
	WORD $0x40e00733 // neg	a4, a4
	WORD $0x00e6f733 // and	a4, a3, a4
	WORD $0x000b8793 // mv	a5, s7
	WORD $0x00098813 // mv	a6, s3
	WORD $0x00070293 // mv	t0, a4
	WORD $0x0d107cd7 // vsetvli	s9, zero, e32, m2, ta, ma

LBB12_32:
	WORD $0x2287e407      // vl2re32.v	v8, (a5)
	WORD $0x22886507      // vl2re32.v	v10, (a6)
	WORD $0x40b282b3      // sub	t0, t0, a1
	WORD $0xb287d557      // vfmacc.vf	v10, fa5, v8
	WORD $0x22880527      // vs2r.v	v10, (a6)
	WORD $0x00880833      // add	a6, a6, s0
	WORD $0x008787b3      // add	a5, a5, s0
	BNEZ T0, LBB12_32
	WORD $0x02813c83      // ld	s9, 40(sp)                      # 8-byte Folded Reload
	BEQ  A3, A4, LBB12_28

LBB12_34:
	WORD $0x02e387b3 // mul	a5, t2, a4
	WORD $0x00271813 // slli	a6, a4, 2
	WORD $0x00fb87b3 // add	a5, s7, a5
	WORD $0x01098833 // add	a6, s3, a6
	WORD $0x40e68733 // sub	a4, a3, a4

LBB12_35:
	WORD $0x000c2787  // flw	fa5, 0(s8)
	WORD $0x0007a707  // flw	fa4, 0(a5)
	WORD $0x00082687  // flw	fa3, 0(a6)
	WORD $0x007787b3  // add	a5, a5, t2
	WORD $0xfff70713  // addi	a4, a4, -1
	WORD $0x68e7f7c3  // fmadd.s	fa5, fa5, fa4, fa3
	WORD $0x00f82027  // fsw	fa5, 0(a6)
	WORD $0x00480813  // addi	a6, a6, 4
	BNEZ A4, LBB12_35
	JMP  LBB12_28

LBB12_36:
	BLEZ A3, LBB12_48
	WORD $0x00000513  // li	a0, 0
	WORD $0x004c9393  // slli	t2, s9, 4
	WORD $0x002c9593  // slli	a1, s9, 2
	WORD $0x003c9813  // slli	a6, s9, 3
	WORD $0x00229e13  // slli	t3, t0, 2
	WORD $0x40b382b3  // sub	t0, t2, a1
	WORD $0x010c0833  // add	a6, s8, a6
	WORD $0x00bc05b3  // add	a1, s8, a1
	WORD $0x005c02b3  // add	t0, s8, t0
	WORD $0x00400713  // li	a4, 4
	WORD $0x000c0793  // mv	a5, s8
	WORD $0x03a13023  // sd	s10, 32(sp)                     # 8-byte Folded Spill
	WORD $0x00c13c23  // sd	a2, 24(sp)                      # 8-byte Folded Spill
	JMP  LBB12_39

LBB12_38:
	WORD $0x00450713       // addi	a4, a0, 4
	WORD $0x007282b3       // add	t0, t0, t2
	WORD $0x00780833       // add	a6, a6, t2
	WORD $0x007585b3       // add	a1, a1, t2
	WORD $0x007787b3       // add	a5, a5, t2
	WORD $0x02013d03       // ld	s10, 32(sp)                     # 8-byte Folded Reload
	WORD $0x00060093       // mv	ra, a2
	WORD $0x01813603       // ld	a2, 24(sp)                      # 8-byte Folded Reload
	BLT  S10, A4, LBB12_49

LBB12_39:
	WORD $0x02c50eb3  // mul	t4, a0, a2
	WORD $0x00150f13  // addi	t5, a0, 1
	WORD $0x00250f93  // addi	t6, a0, 2
	WORD $0x00350413  // addi	s0, a0, 3
	WORD $0x00070513  // mv	a0, a4
	WORD $0x002e9e93  // slli	t4, t4, 2
	WORD $0x02cf0733  // mul	a4, t5, a2
	WORD $0x02cf8f33  // mul	t5, t6, a2
	WORD $0x02c40fb3  // mul	t6, s0, a2
	WORD $0x01d084b3  // add	s1, ra, t4
	WORD $0x00271713  // slli	a4, a4, 2
	WORD $0x002f1f13  // slli	t5, t5, 2
	WORD $0x002f9f93  // slli	t6, t6, 2
	WORD $0x00e08933  // add	s2, ra, a4
	WORD $0x01e089b3  // add	s3, ra, t5
	WORD $0x00008613  // mv	a2, ra
	WORD $0x01f08a33  // add	s4, ra, t6
	BLEZ T1, LBB12_44
	WORD $0x00000a93  // li	s5, 0

LBB12_41:
	WORD $0x41568733 // sub	a4, a3, s5
	WORD $0x002a9093 // slli	ra, s5, 2
	WORD $0x0d077b57 // vsetvli	s6, a4, e32, m1, ta, ma
	WORD $0x00148bb3 // add	s7, s1, ra
	WORD $0x00190c33 // add	s8, s2, ra
	WORD $0x00198d33 // add	s10, s3, ra
	WORD $0x001a0cb3 // add	s9, s4, ra
	WORD $0x020be487 // vle32.v	v9, (s7)
	WORD $0x020c6507 // vle32.v	v10, (s8)
	WORD $0x020d6587 // vle32.v	v11, (s10)
	WORD $0x020ce407 // vle32.v	v8, (s9)
	WORD $0x001880b3 // add	ra, a7, ra
	WORD $0x00078413 // mv	s0, a5
	WORD $0x00058f13 // mv	t5, a1
	WORD $0x00080e93 // mv	t4, a6
	WORD $0x00028f93 // mv	t6, t0
	WORD $0x00030713 // mv	a4, t1

LBB12_42:
	WORD $0x0200e607      // vle32.v	v12, (ra)
	WORD $0x00042787      // flw	fa5, 0(s0)
	WORD $0x000f2707      // flw	fa4, 0(t5)
	WORD $0x92c7d6d7      // vfmul.vf	v13, v12, fa5
	WORD $0x000ea787      // flw	fa5, 0(t4)
	WORD $0x92c75757      // vfmul.vf	v14, v12, fa4
	WORD $0x029694d7      // vfadd.vv	v9, v9, v13
	WORD $0x02a71557      // vfadd.vv	v10, v10, v14
	WORD $0x92c7d6d7      // vfmul.vf	v13, v12, fa5
	WORD $0x000fa787      // flw	fa5, 0(t6)
	WORD $0xfff70713      // addi	a4, a4, -1
	WORD $0x004f8f93      // addi	t6, t6, 4
	WORD $0x004e8e93      // addi	t4, t4, 4
	WORD $0x004f0f13      // addi	t5, t5, 4
	WORD $0x00440413      // addi	s0, s0, 4
	WORD $0x92c7d657      // vfmul.vf	v12, v12, fa5
	WORD $0x02b695d7      // vfadd.vv	v11, v11, v13
	WORD $0x02861457      // vfadd.vv	v8, v8, v12
	WORD $0x01c080b3      // add	ra, ra, t3
	BNEZ A4, LBB12_42
	WORD $0x020be4a7      // vse32.v	v9, (s7)
	WORD $0x020c6527      // vse32.v	v10, (s8)
	WORD $0x020d65a7      // vse32.v	v11, (s10)
	WORD $0x015b0ab3      // add	s5, s6, s5
	WORD $0x020ce427      // vse32.v	v8, (s9)
	BLT  S5, A3, LBB12_41
	JMP  LBB12_38

LBB12_44:
	WORD $0x00000713 // li	a4, 0

LBB12_45:
	WORD $0x40e68eb3      // sub	t4, a3, a4
	WORD $0x00271f13      // slli	t5, a4, 2
	WORD $0x0d0efed7      // vsetvli	t4, t4, e32, m1, ta, ma
	WORD $0x01e48fb3      // add	t6, s1, t5
	WORD $0x01e90433      // add	s0, s2, t5
	WORD $0x01e98ab3      // add	s5, s3, t5
	WORD $0x01ea0f33      // add	t5, s4, t5
	WORD $0x020fe407      // vle32.v	v8, (t6)
	WORD $0x02046487      // vle32.v	v9, (s0)
	WORD $0x020ae507      // vle32.v	v10, (s5)
	WORD $0x020f6587      // vle32.v	v11, (t5)
	WORD $0x00ee8733      // add	a4, t4, a4
	WORD $0x020fe427      // vse32.v	v8, (t6)
	WORD $0x020464a7      // vse32.v	v9, (s0)
	WORD $0x020ae527      // vse32.v	v10, (s5)
	WORD $0x020f65a7      // vse32.v	v11, (t5)
	BLT  A4, A3, LBB12_45
	JMP  LBB12_38

LBB12_46:
	WORD $0x00400513       // li	a0, 4
	WORD $0x00513423       // sd	t0, 8(sp)                       # 8-byte Folded Spill
	BGE  S10, A0, LBB12_61
	WORD $0x00000513       // li	a0, 0
	JMP  LBB12_72

LBB12_48:
	WORD $0xff900513 // li	a0, -7
	WORD $0x00155513 // srli	a0, a0, 1
	WORD $0x00ad7533 // and	a0, s10, a0

LBB12_49:
	WORD $0x01013783       // ld	a5, 16(sp)                      # 8-byte Folded Reload
	WORD $0x02813803       // ld	a6, 40(sp)                      # 8-byte Folded Reload
	WORD $0x00813383       // ld	t2, 8(sp)                       # 8-byte Folded Reload
	BGE  A0, S10, LBB12_84
	BLEZ A3, LBB12_84
	BLEZ T1, LBB12_58
	WORD $0x030505b3       // mul	a1, a0, a6
	WORD $0x00281813       // slli	a6, a6, 2
	WORD $0x00259593       // slli	a1, a1, 2
	WORD $0x00b787b3       // add	a5, a5, a1
	WORD $0x00239393       // slli	t2, t2, 2

LBB12_53:
	WORD $0x00000593 // li	a1, 0
	WORD $0x02c50733 // mul	a4, a0, a2
	WORD $0x00271713 // slli	a4, a4, 2
	WORD $0x00e08733 // add	a4, ra, a4

LBB12_54:
	WORD $0x40b682b3 // sub	t0, a3, a1
	WORD $0x00259e93 // slli	t4, a1, 2
	WORD $0x0d02f2d7 // vsetvli	t0, t0, e32, m1, ta, ma
	WORD $0x01d70e33 // add	t3, a4, t4
	WORD $0x020e6407 // vle32.v	v8, (t3)
	WORD $0x01d88eb3 // add	t4, a7, t4
	WORD $0x00078f13 // mv	t5, a5
	WORD $0x00030f93 // mv	t6, t1

LBB12_55:
	WORD $0x020ee487       // vle32.v	v9, (t4)
	WORD $0x000f2787       // flw	fa5, 0(t5)
	WORD $0xffff8f93       // addi	t6, t6, -1
	WORD $0x004f0f13       // addi	t5, t5, 4
	WORD $0x9297d4d7       // vfmul.vf	v9, v9, fa5
	WORD $0x02849457       // vfadd.vv	v8, v8, v9
	WORD $0x007e8eb3       // add	t4, t4, t2
	BNEZ T6, LBB12_55
	WORD $0x00b285b3       // add	a1, t0, a1
	WORD $0x020e6427       // vse32.v	v8, (t3)
	BLT  A1, A3, LBB12_54
	WORD $0x00150513       // addi	a0, a0, 1
	WORD $0x010787b3       // add	a5, a5, a6
	BNE  A0, S10, LBB12_53
	JMP  LBB12_84

LBB12_58:
	WORD $0x00000593 // li	a1, 0
	WORD $0x02c50733 // mul	a4, a0, a2
	WORD $0x00271713 // slli	a4, a4, 2
	WORD $0x00e08733 // add	a4, ra, a4

LBB12_59:
	WORD $0x40b687b3       // sub	a5, a3, a1
	WORD $0x00259813       // slli	a6, a1, 2
	WORD $0x0d07f7d7       // vsetvli	a5, a5, e32, m1, ta, ma
	WORD $0x01070833       // add	a6, a4, a6
	WORD $0x02086407       // vle32.v	v8, (a6)
	WORD $0x00b785b3       // add	a1, a5, a1
	WORD $0x02086427       // vse32.v	v8, (a6)
	BLT  A1, A3, LBB12_59
	WORD $0x00150513       // addi	a0, a0, 1
	BNE  A0, S10, LBB12_58
	JMP  LBB12_84

LBB12_61:
	BLEZ A3, LBB12_71
	WORD $0x00000513  // li	a0, 0
	WORD $0x008c0593  // addi	a1, s8, 8
	WORD $0x002c9e13  // slli	t3, s9, 2
	WORD $0x00229e93  // slli	t4, t0, 2
	WORD $0x00400713  // li	a4, 4
	JMP  LBB12_64

LBB12_63:
	WORD $0x00450713       // addi	a4, a0, 4
	WORD $0x01058593       // addi	a1, a1, 16
	BLT  S10, A4, LBB12_72

LBB12_64:
	WORD $0x02c507b3  // mul	a5, a0, a2
	WORD $0x00150813  // addi	a6, a0, 1
	WORD $0x00250293  // addi	t0, a0, 2
	WORD $0x00350393  // addi	t2, a0, 3
	WORD $0x00070513  // mv	a0, a4
	WORD $0x00279793  // slli	a5, a5, 2
	WORD $0x02c80733  // mul	a4, a6, a2
	WORD $0x02c28833  // mul	a6, t0, a2
	WORD $0x02c382b3  // mul	t0, t2, a2
	WORD $0x00f08f33  // add	t5, ra, a5
	WORD $0x00271713  // slli	a4, a4, 2
	WORD $0x00281813  // slli	a6, a6, 2
	WORD $0x00229293  // slli	t0, t0, 2
	WORD $0x00e08fb3  // add	t6, ra, a4
	WORD $0x01008433  // add	s0, ra, a6
	WORD $0x005084b3  // add	s1, ra, t0
	BLEZ T1, LBB12_69
	WORD $0x00000913  // li	s2, 0

LBB12_66:
	WORD $0x41268733 // sub	a4, a3, s2
	WORD $0x00291793 // slli	a5, s2, 2
	WORD $0x0d0779d7 // vsetvli	s3, a4, e32, m1, ta, ma
	WORD $0x00ff0a33 // add	s4, t5, a5
	WORD $0x00ff8ab3 // add	s5, t6, a5
	WORD $0x00f40bb3 // add	s7, s0, a5
	WORD $0x00f48b33 // add	s6, s1, a5
	WORD $0x020a6487 // vle32.v	v9, (s4)
	WORD $0x020ae507 // vle32.v	v10, (s5)
	WORD $0x020be587 // vle32.v	v11, (s7)
	WORD $0x020b6407 // vle32.v	v8, (s6)
	WORD $0x00f88733 // add	a4, a7, a5
	WORD $0x00058793 // mv	a5, a1
	WORD $0x00030813 // mv	a6, t1

LBB12_67:
	WORD $0x02076607      // vle32.v	v12, (a4)
	WORD $0xff87a787      // flw	fa5, -8(a5)
	WORD $0xffc7a707      // flw	fa4, -4(a5)
	WORD $0x0007a687      // flw	fa3, 0(a5)
	WORD $0x0047a607      // flw	fa2, 4(a5)
	WORD $0x92c7d6d7      // vfmul.vf	v13, v12, fa5
	WORD $0x92c75757      // vfmul.vf	v14, v12, fa4
	WORD $0x92c6d7d7      // vfmul.vf	v15, v12, fa3
	WORD $0x029694d7      // vfadd.vv	v9, v9, v13
	WORD $0x02a71557      // vfadd.vv	v10, v10, v14
	WORD $0xfff80813      // addi	a6, a6, -1
	WORD $0x01c787b3      // add	a5, a5, t3
	WORD $0x92c65657      // vfmul.vf	v12, v12, fa2
	WORD $0x02b795d7      // vfadd.vv	v11, v11, v15
	WORD $0x02861457      // vfadd.vv	v8, v8, v12
	WORD $0x01d70733      // add	a4, a4, t4
	BNEZ A6, LBB12_67
	WORD $0x020a64a7      // vse32.v	v9, (s4)
	WORD $0x020ae527      // vse32.v	v10, (s5)
	WORD $0x020be5a7      // vse32.v	v11, (s7)
	WORD $0x01298933      // add	s2, s3, s2
	WORD $0x020b6427      // vse32.v	v8, (s6)
	BLT  S2, A3, LBB12_66
	JMP  LBB12_63

LBB12_69:
	WORD $0x00000713 // li	a4, 0

LBB12_70:
	WORD $0x40e687b3      // sub	a5, a3, a4
	WORD $0x00271813      // slli	a6, a4, 2
	WORD $0x0d07f7d7      // vsetvli	a5, a5, e32, m1, ta, ma
	WORD $0x010f02b3      // add	t0, t5, a6
	WORD $0x010f83b3      // add	t2, t6, a6
	WORD $0x01040933      // add	s2, s0, a6
	WORD $0x01048833      // add	a6, s1, a6
	WORD $0x0202e407      // vle32.v	v8, (t0)
	WORD $0x0203e487      // vle32.v	v9, (t2)
	WORD $0x02096507      // vle32.v	v10, (s2)
	WORD $0x02086587      // vle32.v	v11, (a6)
	WORD $0x00e78733      // add	a4, a5, a4
	WORD $0x0202e427      // vse32.v	v8, (t0)
	WORD $0x0203e4a7      // vse32.v	v9, (t2)
	WORD $0x02096527      // vse32.v	v10, (s2)
	WORD $0x020865a7      // vse32.v	v11, (a6)
	BLT  A4, A3, LBB12_70
	JMP  LBB12_63

LBB12_71:
	WORD $0xff900513 // li	a0, -7
	WORD $0x00155513 // srli	a0, a0, 1
	WORD $0x00ad7533 // and	a0, s10, a0

LBB12_72:
	WORD $0x00813383       // ld	t2, 8(sp)                       # 8-byte Folded Reload
	BGE  A0, S10, LBB12_84
	BLEZ A3, LBB12_84
	BLEZ T1, LBB12_81
	WORD $0x00251793       // slli	a5, a0, 2
	WORD $0x002c9813       // slli	a6, s9, 2
	WORD $0x00fc07b3       // add	a5, s8, a5
	WORD $0x00239393       // slli	t2, t2, 2

LBB12_76:
	WORD $0x00000593 // li	a1, 0
	WORD $0x02c50733 // mul	a4, a0, a2
	WORD $0x00271713 // slli	a4, a4, 2
	WORD $0x00e08733 // add	a4, ra, a4

LBB12_77:
	WORD $0x40b682b3 // sub	t0, a3, a1
	WORD $0x00259e93 // slli	t4, a1, 2
	WORD $0x0d02f2d7 // vsetvli	t0, t0, e32, m1, ta, ma
	WORD $0x01d70e33 // add	t3, a4, t4
	WORD $0x020e6407 // vle32.v	v8, (t3)
	WORD $0x01d88eb3 // add	t4, a7, t4
	WORD $0x00078f13 // mv	t5, a5
	WORD $0x00030f93 // mv	t6, t1

LBB12_78:
	WORD $0x020ee487       // vle32.v	v9, (t4)
	WORD $0x000f2787       // flw	fa5, 0(t5)
	WORD $0xffff8f93       // addi	t6, t6, -1
	WORD $0x010f0f33       // add	t5, t5, a6
	WORD $0x9297d4d7       // vfmul.vf	v9, v9, fa5
	WORD $0x02849457       // vfadd.vv	v8, v8, v9
	WORD $0x007e8eb3       // add	t4, t4, t2
	BNEZ T6, LBB12_78
	WORD $0x00b285b3       // add	a1, t0, a1
	WORD $0x020e6427       // vse32.v	v8, (t3)
	BLT  A1, A3, LBB12_77
	WORD $0x00150513       // addi	a0, a0, 1
	WORD $0x00478793       // addi	a5, a5, 4
	BNE  A0, S10, LBB12_76
	JMP  LBB12_84

LBB12_81:
	WORD $0x00000593 // li	a1, 0
	WORD $0x02c50733 // mul	a4, a0, a2
	WORD $0x00271713 // slli	a4, a4, 2
	WORD $0x00e08733 // add	a4, ra, a4

LBB12_82:
	WORD $0x40b687b3       // sub	a5, a3, a1
	WORD $0x00259813       // slli	a6, a1, 2
	WORD $0x0d07f7d7       // vsetvli	a5, a5, e32, m1, ta, ma
	WORD $0x01070833       // add	a6, a4, a6
	WORD $0x02086407       // vle32.v	v8, (a6)
	WORD $0x00b785b3       // add	a1, a5, a1
	WORD $0x02086427       // vse32.v	v8, (a6)
	BLT  A1, A3, LBB12_82
	WORD $0x00150513       // addi	a0, a0, 1
	BNE  A0, S10, LBB12_81

LBB12_84:
	WORD $0x08813083 // ld	ra, 136(sp)                     # 8-byte Folded Reload
	WORD $0x08013403 // ld	s0, 128(sp)                     # 8-byte Folded Reload
	WORD $0x07813483 // ld	s1, 120(sp)                     # 8-byte Folded Reload
	WORD $0x07013903 // ld	s2, 112(sp)                     # 8-byte Folded Reload
	WORD $0x06813983 // ld	s3, 104(sp)                     # 8-byte Folded Reload
	WORD $0x06013a03 // ld	s4, 96(sp)                      # 8-byte Folded Reload
	WORD $0x05813a83 // ld	s5, 88(sp)                      # 8-byte Folded Reload
	WORD $0x05013b03 // ld	s6, 80(sp)                      # 8-byte Folded Reload
	WORD $0x04813b83 // ld	s7, 72(sp)                      # 8-byte Folded Reload
	WORD $0x04013c03 // ld	s8, 64(sp)                      # 8-byte Folded Reload
	WORD $0x03813c83 // ld	s9, 56(sp)                      # 8-byte Folded Reload
	WORD $0x03013d03 // ld	s10, 48(sp)                     # 8-byte Folded Reload
	WORD $0x09010113 // addi	sp, sp, 144
	ADDI 24, SP, SP
	RET
