//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -O3
// source: src/floats_neon.c

TEXT ·vfrom_float32(SB), $0-24
	MOVD a+0(FP), R0
	MOVD dst+8(FP), R1
	MOVD n+16(FP), R2
	WORD $0xf100205f   // cmp	x2, #8
	BGE  LBB0_2
	WORD $0xaa1f03eb   // mov	x11, xzr
	B    LBB0_4

LBB0_2:
	WORD $0xaa1f03ea // mov	x10, xzr
	WORD $0x91004008 // add	x8, x0, #16
	WORD $0xaa0103e9 // mov	x9, x1

LBB0_3:
	WORD $0xad7f8500 // ldp	q0, q1, [x8, #-16]
	WORD $0x9100214b // add	x11, x10, #8
	WORD $0x9100414a // add	x10, x10, #16
	WORD $0x91008108 // add	x8, x8, #32
	WORD $0xeb02015f // cmp	x10, x2
	WORD $0xaa0b03ea // mov	x10, x11
	WORD $0x0e216800 // fcvtn	v0.4h, v0.4s
	WORD $0x4e216820 // fcvtn2	v0.8h, v1.4s
	WORD $0x3c810520 // str	q0, [x9], #16
	BLE  LBB0_3

LBB0_4:
	WORD $0xeb0b0048 // subs	x8, x2, x11
	BLE  LBB0_7
	WORD $0x8b0b0429 // add	x9, x1, x11, lsl #1
	WORD $0x8b0b080a // add	x10, x0, x11, lsl #2

LBB0_6:
	WORD $0x4ddfc940 // ld1r	{ v0.4s }, [x10], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	WORD $0x0e216800 // fcvtn	v0.4h, v0.4s
	WORD $0x0d9f4120 // st1	{ v0.h }[0], [x9], #2
	BNE  LBB0_6

LBB0_7:
	RET

TEXT ·vto_float32(SB), $0-24
	MOVD a+0(FP), R0
	MOVD dst+8(FP), R1
	MOVD n+16(FP), R2
	WORD $0xf100205f   // cmp	x2, #8
	BGE  LBB1_2
	WORD $0xaa1f03eb   // mov	x11, xzr
	B    LBB1_4

LBB1_2:
	WORD $0xaa1f03ea // mov	x10, xzr
	WORD $0x91004028 // add	x8, x1, #16
	WORD $0xaa0003e9 // mov	x9, x0

LBB1_3:
	WORD $0x3cc10520 // ldr	q0, [x9], #16
	WORD $0x9100414c // add	x12, x10, #16
	WORD $0x9100214b // add	x11, x10, #8
	WORD $0xeb02019f // cmp	x12, x2
	WORD $0x0e217801 // fcvtl	v1.4s, v0.4h
	WORD $0x4e217800 // fcvtl2	v0.4s, v0.8h
	WORD $0xaa0b03ea // mov	x10, x11
	WORD $0xad3f8101 // stp	q1, q0, [x8, #-16]
	WORD $0x91008108 // add	x8, x8, #32
	BLE  LBB1_3

LBB1_4:
	WORD $0xeb0b0048 // subs	x8, x2, x11
	BLE  LBB1_7
	WORD $0x8b0b0829 // add	x9, x1, x11, lsl #2
	WORD $0x8b0b040a // add	x10, x0, x11, lsl #1

LBB1_6:
	WORD $0x0ddfc540 // ld1r	{ v0.4h }, [x10], #2
	WORD $0xf1000508 // subs	x8, x8, #1
	WORD $0x0e217800 // fcvtl	v0.4s, v0.4h
	WORD $0x0d9f8120 // st1	{ v0.s }[0], [x9], #4
	BNE  LBB1_6

LBB1_7:
	RET

TEXT ·vmul_const_add_to(SB), $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD dst+24(FP), R3
	MOVD n+32(FP), R4
	WORD $0xf100049f    // cmp	x4, #1
	BLT  LBB2_5
	WORD $0xf100309f    // cmp	x4, #12
	BHS  LBB2_6
	WORD $0xaa1f03e8    // mov	x8, xzr

LBB2_3:
	WORD $0xd37ef50b // lsl	x11, x8, #2
	WORD $0xcb080088 // sub	x8, x4, x8
	WORD $0x8b0b0069 // add	x9, x3, x11
	WORD $0x8b0b004a // add	x10, x2, x11
	WORD $0x8b0b000b // add	x11, x0, x11

LBB2_4:
	WORD $0xbc404560 // ldr	s0, [x11], #4
	WORD $0xbd400021 // ldr	s1, [x1]
	WORD $0xbc404542 // ldr	s2, [x10], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbc004520 // str	s0, [x9], #4
	BNE  LBB2_4

LBB2_5:
	RET

LBB2_6:
	WORD $0xd37ef488 // lsl	x8, x4, #2
	WORD $0x91001029 // add	x9, x1, #4
	WORD $0xeb09007f // cmp	x3, x9
	WORD $0x8b08006b // add	x11, x3, x8
	WORD $0x8b08004a // add	x10, x2, x8
	WORD $0x8b080008 // add	x8, x0, x8
	WORD $0xfa4b3022 // ccmp	x1, x11, #2, lo
	WORD $0x1a9f27e9 // cset	w9, lo
	WORD $0xeb0a007f // cmp	x3, x10
	WORD $0xfa4b3042 // ccmp	x2, x11, #2, lo
	WORD $0x1a9f27ea // cset	w10, lo
	WORD $0xeb0b001f // cmp	x0, x11
	WORD $0xfa483062 // ccmp	x3, x8, #2, lo
	WORD $0xaa1f03e8 // mov	x8, xzr
	BLO  LBB2_3
	WORD $0x3707fc89 // tbnz	w9, #0, .LBB2_3
	WORD $0x3707fc6a // tbnz	w10, #0, .LBB2_3
	WORD $0x927dec88 // and	x8, x4, #0x7ffffffffffffff8
	WORD $0xbd400020 // ldr	s0, [x1]
	WORD $0x91004069 // add	x9, x3, #16
	WORD $0x9100404a // add	x10, x2, #16
	WORD $0x9100400b // add	x11, x0, #16
	WORD $0xaa0803ec // mov	x12, x8

LBB2_10:
	WORD $0xad7f9141 // ldp	q1, q4, [x10, #-16]
	WORD $0xf100218c // subs	x12, x12, #8
	WORD $0xad7f8d62 // ldp	q2, q3, [x11, #-16]
	WORD $0x9100814a // add	x10, x10, #32
	WORD $0x9100816b // add	x11, x11, #32
	WORD $0x4f801041 // fmla	v1.4s, v2.4s, v0.s[0]
	WORD $0x4f801064 // fmla	v4.4s, v3.4s, v0.s[0]
	WORD $0xad3f9121 // stp	q1, q4, [x9, #-16]
	WORD $0x91008129 // add	x9, x9, #32
	BNE  LBB2_10
	WORD $0xeb08009f // cmp	x4, x8
	BNE  LBB2_3
	B    LBB2_5

TEXT ·vmul_const_add(SB), $0-32
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD n+24(FP), R3
	WORD $0xf100047f  // cmp	x3, #1
	BLT  LBB3_5
	WORD $0xf100207f  // cmp	x3, #8
	BHS  LBB3_6
	WORD $0xaa1f03e8  // mov	x8, xzr

LBB3_3:
	WORD $0xd37ef50a // lsl	x10, x8, #2
	WORD $0xcb080068 // sub	x8, x3, x8
	WORD $0x8b0a0049 // add	x9, x2, x10
	WORD $0x8b0a000a // add	x10, x0, x10

LBB3_4:
	WORD $0xbc404540 // ldr	s0, [x10], #4
	WORD $0xbd400021 // ldr	s1, [x1]
	WORD $0xbd400122 // ldr	s2, [x9]
	WORD $0xf1000508 // subs	x8, x8, #1
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbc004520 // str	s0, [x9], #4
	BNE  LBB3_4

LBB3_5:
	RET

LBB3_6:
	WORD $0xd37ef468 // lsl	x8, x3, #2
	WORD $0x91001029 // add	x9, x1, #4
	WORD $0xeb09005f // cmp	x2, x9
	WORD $0x8b08004a // add	x10, x2, x8
	WORD $0x8b080008 // add	x8, x0, x8
	WORD $0xfa4a3022 // ccmp	x1, x10, #2, lo
	WORD $0x1a9f27e9 // cset	w9, lo
	WORD $0xeb0a001f // cmp	x0, x10
	WORD $0xfa483042 // ccmp	x2, x8, #2, lo
	WORD $0xaa1f03e8 // mov	x8, xzr
	BLO  LBB3_3
	WORD $0x3707fd29 // tbnz	w9, #0, .LBB3_3
	WORD $0x927dec68 // and	x8, x3, #0x7ffffffffffffff8
	WORD $0xbd400020 // ldr	s0, [x1]
	WORD $0x91004049 // add	x9, x2, #16
	WORD $0x9100400a // add	x10, x0, #16
	WORD $0xaa0803eb // mov	x11, x8

LBB3_9:
	WORD $0xad7f9121 // ldp	q1, q4, [x9, #-16]
	WORD $0xf100216b // subs	x11, x11, #8
	WORD $0xad7f8d42 // ldp	q2, q3, [x10, #-16]
	WORD $0x9100814a // add	x10, x10, #32
	WORD $0x4f801041 // fmla	v1.4s, v2.4s, v0.s[0]
	WORD $0x4f801064 // fmla	v4.4s, v3.4s, v0.s[0]
	WORD $0xad3f9121 // stp	q1, q4, [x9, #-16]
	WORD $0x91008129 // add	x9, x9, #32
	BNE  LBB3_9
	WORD $0xeb08007f // cmp	x3, x8
	BNE  LBB3_3
	B    LBB3_5

TEXT ·vmul_const_to(SB), $0-32
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD n+24(FP), R3
	WORD $0xf100047f  // cmp	x3, #1
	BLT  LBB4_5
	WORD $0xf100207f  // cmp	x3, #8
	BHS  LBB4_6
	WORD $0xaa1f03e8  // mov	x8, xzr

LBB4_3:
	WORD $0xd37ef50a // lsl	x10, x8, #2
	WORD $0xcb080068 // sub	x8, x3, x8
	WORD $0x8b0a0049 // add	x9, x2, x10
	WORD $0x8b0a000a // add	x10, x0, x10

LBB4_4:
	WORD $0xbc404540 // ldr	s0, [x10], #4
	WORD $0xbd400021 // ldr	s1, [x1]
	WORD $0xf1000508 // subs	x8, x8, #1
	WORD $0x1e210800 // fmul	s0, s0, s1
	WORD $0xbc004520 // str	s0, [x9], #4
	BNE  LBB4_4

LBB4_5:
	RET

LBB4_6:
	WORD $0xd37ef468 // lsl	x8, x3, #2
	WORD $0x91001029 // add	x9, x1, #4
	WORD $0xeb09005f // cmp	x2, x9
	WORD $0x8b08004a // add	x10, x2, x8
	WORD $0x8b080008 // add	x8, x0, x8
	WORD $0xfa4a3022 // ccmp	x1, x10, #2, lo
	WORD $0x1a9f27e9 // cset	w9, lo
	WORD $0xeb0a001f // cmp	x0, x10
	WORD $0xfa483042 // ccmp	x2, x8, #2, lo
	WORD $0xaa1f03e8 // mov	x8, xzr
	BLO  LBB4_3
	WORD $0x3707fd49 // tbnz	w9, #0, .LBB4_3
	WORD $0x927dec68 // and	x8, x3, #0x7ffffffffffffff8
	WORD $0xbd400020 // ldr	s0, [x1]
	WORD $0x91004049 // add	x9, x2, #16
	WORD $0x9100400a // add	x10, x0, #16
	WORD $0xaa0803eb // mov	x11, x8

LBB4_9:
	WORD $0xad7f8941 // ldp	q1, q2, [x10, #-16]
	WORD $0xf100216b // subs	x11, x11, #8
	WORD $0x9100814a // add	x10, x10, #32
	WORD $0x4f809021 // fmul	v1.4s, v1.4s, v0.s[0]
	WORD $0x4f809042 // fmul	v2.4s, v2.4s, v0.s[0]
	WORD $0xad3f8921 // stp	q1, q2, [x9, #-16]
	WORD $0x91008129 // add	x9, x9, #32
	BNE  LBB4_9
	WORD $0xeb08007f // cmp	x3, x8
	BNE  LBB4_3
	B    LBB4_5

TEXT ·vmul_const(SB), $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD n+16(FP), R2
	WORD $0xf100045f  // cmp	x2, #1
	BLT  LBB5_7
	WORD $0xf100205f  // cmp	x2, #8
	BLO  LBB5_4
	WORD $0x91001028  // add	x8, x1, #4
	WORD $0xeb08001f  // cmp	x0, x8
	BHS  LBB5_8
	WORD $0x8b020808  // add	x8, x0, x2, lsl #2
	WORD $0xeb08003f  // cmp	x1, x8
	BHS  LBB5_8

LBB5_4:
	WORD $0xaa1f03e8 // mov	x8, xzr

LBB5_5:
	WORD $0x8b080809 // add	x9, x0, x8, lsl #2
	WORD $0xcb080048 // sub	x8, x2, x8

LBB5_6:
	WORD $0xbd400020 // ldr	s0, [x1]
	WORD $0xbd400121 // ldr	s1, [x9]
	WORD $0xf1000508 // subs	x8, x8, #1
	WORD $0x1e210800 // fmul	s0, s0, s1
	WORD $0xbc004520 // str	s0, [x9], #4
	BNE  LBB5_6

LBB5_7:
	RET

LBB5_8:
	WORD $0x927dec48 // and	x8, x2, #0x7ffffffffffffff8
	WORD $0xbd400020 // ldr	s0, [x1]
	WORD $0x91004009 // add	x9, x0, #16
	WORD $0xaa0803ea // mov	x10, x8

LBB5_9:
	WORD $0xad7f8921 // ldp	q1, q2, [x9, #-16]
	WORD $0xf100214a // subs	x10, x10, #8
	WORD $0x4f809021 // fmul	v1.4s, v1.4s, v0.s[0]
	WORD $0x4f809042 // fmul	v2.4s, v2.4s, v0.s[0]
	WORD $0xad3f8921 // stp	q1, q2, [x9, #-16]
	WORD $0x91008129 // add	x9, x9, #32
	BNE  LBB5_9
	WORD $0xeb08005f // cmp	x2, x8
	BEQ  LBB5_7
	B    LBB5_5

TEXT ·vadd_const(SB), $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD n+16(FP), R2
	WORD $0xf100045f  // cmp	x2, #1
	BLT  LBB6_7
	WORD $0xf100205f  // cmp	x2, #8
	BLO  LBB6_4
	WORD $0x91001028  // add	x8, x1, #4
	WORD $0xeb08001f  // cmp	x0, x8
	BHS  LBB6_8
	WORD $0x8b020808  // add	x8, x0, x2, lsl #2
	WORD $0xeb08003f  // cmp	x1, x8
	BHS  LBB6_8

LBB6_4:
	WORD $0xaa1f03e8 // mov	x8, xzr

LBB6_5:
	WORD $0x8b080809 // add	x9, x0, x8, lsl #2
	WORD $0xcb080048 // sub	x8, x2, x8

LBB6_6:
	WORD $0xbd400020 // ldr	s0, [x1]
	WORD $0xbd400121 // ldr	s1, [x9]
	WORD $0xf1000508 // subs	x8, x8, #1
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0xbc004520 // str	s0, [x9], #4
	BNE  LBB6_6

LBB6_7:
	RET

LBB6_8:
	WORD $0x4d40c820 // ld1r	{ v0.4s }, [x1]
	WORD $0x927dec48 // and	x8, x2, #0x7ffffffffffffff8
	WORD $0x91004009 // add	x9, x0, #16
	WORD $0xaa0803ea // mov	x10, x8

LBB6_9:
	WORD $0xad7f8921 // ldp	q1, q2, [x9, #-16]
	WORD $0xf100214a // subs	x10, x10, #8
	WORD $0x4e21d401 // fadd	v1.4s, v0.4s, v1.4s
	WORD $0x4e22d402 // fadd	v2.4s, v0.4s, v2.4s
	WORD $0xad3f8921 // stp	q1, q2, [x9, #-16]
	WORD $0x91008129 // add	x9, x9, #32
	BNE  LBB6_9
	WORD $0xeb08005f // cmp	x2, x8
	BEQ  LBB6_7
	B    LBB6_5

TEXT ·vsub_to(SB), $0-32
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD n+24(FP), R3
	WORD $0xf100047f  // cmp	x3, #1
	BLT  LBB7_5
	WORD $0xf100207f  // cmp	x3, #8
	BHS  LBB7_6
	WORD $0xaa1f03e8  // mov	x8, xzr

LBB7_3:
	WORD $0xd37ef50b // lsl	x11, x8, #2
	WORD $0xcb080068 // sub	x8, x3, x8
	WORD $0x8b0b0049 // add	x9, x2, x11
	WORD $0x8b0b002a // add	x10, x1, x11
	WORD $0x8b0b000b // add	x11, x0, x11

LBB7_4:
	WORD $0xbc404560 // ldr	s0, [x11], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	WORD $0xbc404541 // ldr	s1, [x10], #4
	WORD $0x1e213800 // fsub	s0, s0, s1
	WORD $0xbc004520 // str	s0, [x9], #4
	BNE  LBB7_4

LBB7_5:
	RET

LBB7_6:
	WORD $0xcb000048 // sub	x8, x2, x0
	WORD $0xf100811f // cmp	x8, #32
	WORD $0xaa1f03e8 // mov	x8, xzr
	BLO  LBB7_3
	WORD $0xcb010049 // sub	x9, x2, x1
	WORD $0xf100813f // cmp	x9, #32
	BLO  LBB7_3
	WORD $0x927dec68 // and	x8, x3, #0x7ffffffffffffff8
	WORD $0x91004049 // add	x9, x2, #16
	WORD $0x9100402a // add	x10, x1, #16
	WORD $0x9100400b // add	x11, x0, #16
	WORD $0xaa0803ec // mov	x12, x8

LBB7_9:
	WORD $0xad7f8d40 // ldp	q0, q3, [x10, #-16]
	WORD $0xf100218c // subs	x12, x12, #8
	WORD $0xad7f8961 // ldp	q1, q2, [x11, #-16]
	WORD $0x9100814a // add	x10, x10, #32
	WORD $0x9100816b // add	x11, x11, #32
	WORD $0x4ea0d420 // fsub	v0.4s, v1.4s, v0.4s
	WORD $0x4ea3d441 // fsub	v1.4s, v2.4s, v3.4s
	WORD $0xad3f8520 // stp	q0, q1, [x9, #-16]
	WORD $0x91008129 // add	x9, x9, #32
	BNE  LBB7_9
	WORD $0xeb08007f // cmp	x3, x8
	BNE  LBB7_3
	B    LBB7_5

TEXT ·vsub(SB), $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD n+16(FP), R2
	WORD $0xf100045f  // cmp	x2, #1
	BLT  LBB8_7
	WORD $0xf100205f  // cmp	x2, #8
	BLO  LBB8_4
	WORD $0xd37ef448  // lsl	x8, x2, #2
	WORD $0x8b080029  // add	x9, x1, x8
	WORD $0xeb09001f  // cmp	x0, x9
	BHS  LBB8_8
	WORD $0x8b080008  // add	x8, x0, x8
	WORD $0xeb08003f  // cmp	x1, x8
	BHS  LBB8_8

LBB8_4:
	WORD $0xaa1f03e8 // mov	x8, xzr

LBB8_5:
	WORD $0xd37ef50a // lsl	x10, x8, #2
	WORD $0xcb080048 // sub	x8, x2, x8
	WORD $0x8b0a0009 // add	x9, x0, x10
	WORD $0x8b0a002a // add	x10, x1, x10

LBB8_6:
	WORD $0xbc404540 // ldr	s0, [x10], #4
	WORD $0xbd400121 // ldr	s1, [x9]
	WORD $0xf1000508 // subs	x8, x8, #1
	WORD $0x1e203820 // fsub	s0, s1, s0
	WORD $0xbc004520 // str	s0, [x9], #4
	BNE  LBB8_6

LBB8_7:
	RET

LBB8_8:
	WORD $0x927dec48 // and	x8, x2, #0x7ffffffffffffff8
	WORD $0x91004009 // add	x9, x0, #16
	WORD $0x9100402a // add	x10, x1, #16
	WORD $0xaa0803eb // mov	x11, x8

LBB8_9:
	WORD $0xad7f8d20 // ldp	q0, q3, [x9, #-16]
	WORD $0xf100216b // subs	x11, x11, #8
	WORD $0xad7f8941 // ldp	q1, q2, [x10, #-16]
	WORD $0x9100814a // add	x10, x10, #32
	WORD $0x4ea1d400 // fsub	v0.4s, v0.4s, v1.4s
	WORD $0x4ea2d461 // fsub	v1.4s, v3.4s, v2.4s
	WORD $0xad3f8520 // stp	q0, q1, [x9, #-16]
	WORD $0x91008129 // add	x9, x9, #32
	BNE  LBB8_9
	WORD $0xeb08005f // cmp	x2, x8
	BEQ  LBB8_7
	B    LBB8_5

TEXT ·vmul_to(SB), $0-32
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD n+24(FP), R3
	WORD $0xf100047f  // cmp	x3, #1
	BLT  LBB9_5
	WORD $0xf100207f  // cmp	x3, #8
	BHS  LBB9_6
	WORD $0xaa1f03e8  // mov	x8, xzr

LBB9_3:
	WORD $0xd37ef50b // lsl	x11, x8, #2
	WORD $0xcb080068 // sub	x8, x3, x8
	WORD $0x8b0b0049 // add	x9, x2, x11
	WORD $0x8b0b002a // add	x10, x1, x11
	WORD $0x8b0b000b // add	x11, x0, x11

LBB9_4:
	WORD $0xbc404560 // ldr	s0, [x11], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	WORD $0xbc404541 // ldr	s1, [x10], #4
	WORD $0x1e210800 // fmul	s0, s0, s1
	WORD $0xbc004520 // str	s0, [x9], #4
	BNE  LBB9_4

LBB9_5:
	RET

LBB9_6:
	WORD $0xcb000048 // sub	x8, x2, x0
	WORD $0xf100811f // cmp	x8, #32
	WORD $0xaa1f03e8 // mov	x8, xzr
	BLO  LBB9_3
	WORD $0xcb010049 // sub	x9, x2, x1
	WORD $0xf100813f // cmp	x9, #32
	BLO  LBB9_3
	WORD $0x927dec68 // and	x8, x3, #0x7ffffffffffffff8
	WORD $0x91004049 // add	x9, x2, #16
	WORD $0x9100402a // add	x10, x1, #16
	WORD $0x9100400b // add	x11, x0, #16
	WORD $0xaa0803ec // mov	x12, x8

LBB9_9:
	WORD $0xad7f8d40 // ldp	q0, q3, [x10, #-16]
	WORD $0xf100218c // subs	x12, x12, #8
	WORD $0xad7f8961 // ldp	q1, q2, [x11, #-16]
	WORD $0x9100814a // add	x10, x10, #32
	WORD $0x9100816b // add	x11, x11, #32
	WORD $0x6e20dc20 // fmul	v0.4s, v1.4s, v0.4s
	WORD $0x6e23dc41 // fmul	v1.4s, v2.4s, v3.4s
	WORD $0xad3f8520 // stp	q0, q1, [x9, #-16]
	WORD $0x91008129 // add	x9, x9, #32
	BNE  LBB9_9
	WORD $0xeb08007f // cmp	x3, x8
	BNE  LBB9_3
	B    LBB9_5

TEXT ·vdiv_to(SB), $0-32
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD n+24(FP), R3
	WORD $0xf100047f  // cmp	x3, #1
	BLT  LBB10_5
	WORD $0xf100207f  // cmp	x3, #8
	BHS  LBB10_6
	WORD $0xaa1f03e8  // mov	x8, xzr

LBB10_3:
	WORD $0xd37ef50b // lsl	x11, x8, #2
	WORD $0xcb080068 // sub	x8, x3, x8
	WORD $0x8b0b0049 // add	x9, x2, x11
	WORD $0x8b0b002a // add	x10, x1, x11
	WORD $0x8b0b000b // add	x11, x0, x11

LBB10_4:
	WORD $0xbc404560 // ldr	s0, [x11], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	WORD $0xbc404541 // ldr	s1, [x10], #4
	WORD $0x1e211800 // fdiv	s0, s0, s1
	WORD $0xbc004520 // str	s0, [x9], #4
	BNE  LBB10_4

LBB10_5:
	RET

LBB10_6:
	WORD $0xcb000048 // sub	x8, x2, x0
	WORD $0xf100811f // cmp	x8, #32
	WORD $0xaa1f03e8 // mov	x8, xzr
	BLO  LBB10_3
	WORD $0xcb010049 // sub	x9, x2, x1
	WORD $0xf100813f // cmp	x9, #32
	BLO  LBB10_3
	WORD $0x927dec68 // and	x8, x3, #0x7ffffffffffffff8
	WORD $0x91004049 // add	x9, x2, #16
	WORD $0x9100402a // add	x10, x1, #16
	WORD $0x9100400b // add	x11, x0, #16
	WORD $0xaa0803ec // mov	x12, x8

LBB10_9:
	WORD $0xad7f8d40 // ldp	q0, q3, [x10, #-16]
	WORD $0xf100218c // subs	x12, x12, #8
	WORD $0xad7f8961 // ldp	q1, q2, [x11, #-16]
	WORD $0x9100814a // add	x10, x10, #32
	WORD $0x9100816b // add	x11, x11, #32
	WORD $0x6e20fc20 // fdiv	v0.4s, v1.4s, v0.4s
	WORD $0x6e23fc41 // fdiv	v1.4s, v2.4s, v3.4s
	WORD $0xad3f8520 // stp	q0, q1, [x9, #-16]
	WORD $0x91008129 // add	x9, x9, #32
	BNE  LBB10_9
	WORD $0xeb08007f // cmp	x3, x8
	BNE  LBB10_3
	B    LBB10_5

TEXT ·vsqrt_to(SB), $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD n+16(FP), R2
	WORD $0x91000c48  // add	x8, x2, #3
	WORD $0xf100005f  // cmp	x2, #0
	WORD $0x9a82b108  // csel	x8, x8, x2, lt
	WORD $0xd342fd09  // lsr	x9, x8, #2
	WORD $0x927ef508  // and	x8, x8, #0xfffffffffffffffc
	WORD $0xcb080048  // sub	x8, x2, x8
	WORD $0x7100053f  // cmp	w9, #1
	BLT  LBB11_2

LBB11_1:
	WORD $0x3cc10400 // ldr	q0, [x0], #16
	WORD $0x71000529 // subs	w9, w9, #1
	WORD $0x6ea1f800 // fsqrt	v0.4s, v0.4s
	WORD $0x3c810420 // str	q0, [x1], #16
	BNE  LBB11_1

LBB11_2:
	WORD $0xf100011f // cmp	x8, #0
	BLE  LBB11_6
	WORD $0xbd400000 // ldr	s0, [x0]
	WORD $0xf100051f // cmp	x8, #1
	WORD $0x1e21c000 // fsqrt	s0, s0
	WORD $0xbd000020 // str	s0, [x1]
	BEQ  LBB11_6
	WORD $0xbd400400 // ldr	s0, [x0, #4]
	WORD $0xf100091f // cmp	x8, #2
	WORD $0x1e21c000 // fsqrt	s0, s0
	WORD $0xbd000420 // str	s0, [x1, #4]
	BEQ  LBB11_6
	WORD $0xbd400800 // ldr	s0, [x0, #8]
	WORD $0x1e21c000 // fsqrt	s0, s0
	WORD $0xbd000820 // str	s0, [x1, #8]

LBB11_6:
	RET

TEXT ·vdot(SB), $0-28
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD n+16(FP), R2
	WORD $0x91000c48  // add	x8, x2, #3
	WORD $0xf100005f  // cmp	x2, #0
	WORD $0x9a82b108  // csel	x8, x8, x2, lt
	WORD $0x9342fd09  // asr	x9, x8, #2
	WORD $0x927ef508  // and	x8, x8, #0xfffffffffffffffc
	WORD $0xcb080048  // sub	x8, x2, x8
	WORD $0x7100053f  // cmp	w9, #1
	BLT  LBB12_5
	WORD $0x3cc10400  // ldr	q0, [x0], #16
	WORD $0x7100052a  // subs	w10, w9, #1
	WORD $0x3cc10421  // ldr	q1, [x1], #16
	WORD $0x6e21dc00  // fmul	v0.4s, v0.4s, v1.4s
	BEQ  LBB12_6
	WORD $0xaa0003eb  // mov	x11, x0
	WORD $0xaa0103ec  // mov	x12, x1

LBB12_3:
	WORD $0x3cc10561 // ldr	q1, [x11], #16
	WORD $0x7100054a // subs	w10, w10, #1
	WORD $0x3cc10582 // ldr	q2, [x12], #16
	WORD $0x4e21cc40 // fmla	v0.4s, v2.4s, v1.4s
	BNE  LBB12_3
	WORD $0xb27b7bea // mov	x10, #68719476704
	WORD $0x8b091149 // add	x9, x10, x9, lsl #4
	WORD $0x927c7d29 // and	x9, x9, #0xffffffff0
	WORD $0x91004129 // add	x9, x9, #16
	WORD $0x8b090000 // add	x0, x0, x9
	WORD $0x8b090021 // add	x1, x1, x9
	B    LBB12_6

LBB12_5:
	WORD $0x6f00e400 // movi	v0.2d, #0000000000000000

LBB12_6:
	WORD $0x2f00e401 // movi	d1, #0000000000000000
	WORD $0x5e0c0402 // mov	s2, v0.s[1]
	WORD $0xf100011f // cmp	x8, #0
	WORD $0x1e212801 // fadd	s1, s0, s1
	WORD $0x1e212841 // fadd	s1, s2, s1
	WORD $0x5e140402 // mov	s2, v0.s[2]
	WORD $0x5e1c0400 // mov	s0, v0.s[3]
	WORD $0x1e212841 // fadd	s1, s2, s1
	WORD $0x1e212800 // fadd	s0, s0, s1
	BLE  LBB12_10
	WORD $0xbd400001 // ldr	s1, [x0]
	WORD $0xbd400022 // ldr	s2, [x1]
	WORD $0xf100051f // cmp	x8, #1
	WORD $0x1f020020 // fmadd	s0, s1, s2, s0
	BEQ  LBB12_10
	WORD $0xbd400401 // ldr	s1, [x0, #4]
	WORD $0xbd400422 // ldr	s2, [x1, #4]
	WORD $0xf100091f // cmp	x8, #2
	WORD $0x1f020020 // fmadd	s0, s1, s2, s0
	BEQ  LBB12_10
	WORD $0xbd400801 // ldr	s1, [x0, #8]
	WORD $0xbd400822 // ldr	s2, [x1, #8]
	WORD $0x1f020020 // fmadd	s0, s1, s2, s0

LBB12_10:
	FMOVS F0, result+24(FP)
	RET

TEXT ·veuclidean(SB), $0-28
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD n+16(FP), R2
	WORD $0xd10043ff  // sub	sp, sp, #16
	WORD $0x91000c48  // add	x8, x2, #3
	WORD $0xf100005f  // cmp	x2, #0
	WORD $0x9a82b108  // csel	x8, x8, x2, lt
	WORD $0x9342fd09  // asr	x9, x8, #2
	WORD $0x927ef508  // and	x8, x8, #0xfffffffffffffffc
	WORD $0xcb080048  // sub	x8, x2, x8
	WORD $0x7100053f  // cmp	w9, #1
	BLT  LBB13_5
	WORD $0x3cc10400  // ldr	q0, [x0], #16
	WORD $0x7100052a  // subs	w10, w9, #1
	WORD $0x3cc10421  // ldr	q1, [x1], #16
	WORD $0x4ea1d400  // fsub	v0.4s, v0.4s, v1.4s
	WORD $0x6e20dc00  // fmul	v0.4s, v0.4s, v0.4s
	BEQ  LBB13_6
	WORD $0xaa0003eb  // mov	x11, x0
	WORD $0xaa0103ec  // mov	x12, x1

LBB13_3:
	WORD $0x3cc10561 // ldr	q1, [x11], #16
	WORD $0x7100054a // subs	w10, w10, #1
	WORD $0x3cc10582 // ldr	q2, [x12], #16
	WORD $0x4ea2d421 // fsub	v1.4s, v1.4s, v2.4s
	WORD $0x4e21cc20 // fmla	v0.4s, v1.4s, v1.4s
	BNE  LBB13_3
	WORD $0xb27b7bea // mov	x10, #68719476704
	WORD $0x8b091149 // add	x9, x10, x9, lsl #4
	WORD $0x927c7d29 // and	x9, x9, #0xffffffff0
	WORD $0x91004129 // add	x9, x9, #16
	WORD $0x8b090000 // add	x0, x0, x9
	WORD $0x8b090021 // add	x1, x1, x9
	B    LBB13_6

LBB13_5:
	WORD $0x6f00e400 // movi	v0.2d, #0000000000000000

LBB13_6:
	WORD $0x4e0c0401 // dup	v1.4s, v0.s[1]
	WORD $0x4e140402 // dup	v2.4s, v0.s[2]
	WORD $0xf100011f // cmp	x8, #0
	WORD $0x4e20d421 // fadd	v1.4s, v1.4s, v0.4s
	WORD $0x4e1c0400 // dup	v0.4s, v0.s[3]
	WORD $0x4e21d441 // fadd	v1.4s, v2.4s, v1.4s
	WORD $0x4e21d400 // fadd	v0.4s, v0.4s, v1.4s
	WORD $0xbd000be0 // str	s0, [sp, #8]
	BLE  LBB13_11
	WORD $0xbd400001 // ldr	s1, [x0]
	WORD $0xbd400022 // ldr	s2, [x1]
	WORD $0xf100051f // cmp	x8, #1
	WORD $0x1e223821 // fsub	s1, s1, s2
	WORD $0x1f010020 // fmadd	s0, s1, s1, s0
	BEQ  LBB13_10
	WORD $0xbd400401 // ldr	s1, [x0, #4]
	WORD $0xbd400422 // ldr	s2, [x1, #4]
	WORD $0xf100091f // cmp	x8, #2
	WORD $0x1e223821 // fsub	s1, s1, s2
	WORD $0x1f010020 // fmadd	s0, s1, s1, s0
	BEQ  LBB13_10
	WORD $0xbd400801 // ldr	s1, [x0, #8]
	WORD $0xbd400822 // ldr	s2, [x1, #8]
	WORD $0x1e223821 // fsub	s1, s1, s2
	WORD $0x1f010020 // fmadd	s0, s1, s1, s0

LBB13_10:
	WORD $0xbd000be0 // str	s0, [sp, #8]

LBB13_11:
	WORD  $0xfd4007e0       // ldr	d0, [sp, #8]
	WORD  $0x2ea1f800       // fsqrt	v0.2s, v0.2s
	WORD  $0x910043ff       // add	sp, sp, #16
	FMOVS F0, result+24(FP)
	RET

TEXT ·vmm(SB), $24-80
	MOVBU transA+0(FP), R0
	MOVBU transB+1(FP), R1
	MOVD  m+8(FP), R2
	MOVD  n+16(FP), R3
	MOVD  k+24(FP), R4
	MOVD  a+32(FP), R5
	MOVD  lda+40(FP), R6
	MOVD  b+48(FP), R7
	MOVD  ldb+56(FP), R8
	MOVD  R8, 0(RSP)
	MOVD  c+64(FP), R8
	MOVD  R8, 8(RSP)
	MOVD  ldc+72(FP), R8
	MOVD  R8, 16(RSP)
	WORD  $0xd10283ff      // sub	sp, sp, #160
	WORD  $0xa94aa7e8      // ldp	x8, x9, [sp, #168]
	WORD  $0xf94053ed      // ldr	x13, [sp, #160]
	WORD  $0xf90017e5      // str	x5, [sp, #40]
	WORD  $0xaa0403e5      // mov	x5, x4
	WORD  $0xa903fbe7      // stp	x7, x30, [sp, #56]
	WORD  $0xa9056ffc      // stp	x28, x27, [sp, #80]
	WORD  $0xa90667fa      // stp	x26, x25, [sp, #96]
	WORD  $0xa9075ff8      // stp	x24, x23, [sp, #112]
	WORD  $0xa90857f6      // stp	x22, x21, [sp, #128]
	WORD  $0xa9094ff4      // stp	x20, x19, [sp, #144]
	WORD  $0xf90027e8      // str	x8, [sp, #72]
	WORD  $0x36000b41      // tbz	w1, #0, .LBB14_16
	WORD  $0x36002b00      // tbz	w0, #0, .LBB14_53
	WORD  $0xf10004a8      // subs	x8, x5, #1
	BLT   LBB14_128
	WORD  $0xf100047f      // cmp	x3, #1
	BLT   LBB14_128
	WORD  $0xf100045f      // cmp	x2, #1
	BLT   LBB14_128
	WORD  $0x9b087cc8      // mul	x8, x6, x8
	WORD  $0xf9401fe1      // ldr	x1, [sp, #56]
	WORD  $0x8b0300ae      // add	x14, x5, x3
	WORD  $0xf94027f3      // ldr	x19, [sp, #72]
	WORD  $0xf1001c7f      // cmp	x3, #7
	WORD  $0xd37ef529      // lsl	x9, x9, #2
	WORD  $0x8b0e0830      // add	x16, x1, x14, lsl #2
	WORD  $0xf94017ee      // ldr	x14, [sp, #40]
	WORD  $0xd37df4cf      // ubfx	x15, x6, #61, #1
	WORD  $0x8b030a6b      // add	x11, x19, x3, lsl #2
	WORD  $0xfa4189a0      // ccmp	x13, #1, #0, hi
	WORD  $0xaa1f03ea      // mov	x10, xzr
	WORD  $0x927dec6c      // and	x12, x3, #0x7ffffffffffffff8
	WORD  $0xd1001210      // sub	x16, x16, #4
	WORD  $0x91004260      // add	x0, x19, #16
	WORD  $0x8b0809c8      // add	x8, x14, x8, lsl #2
	WORD  $0xd37ef5ae      // lsl	x14, x13, #2
	WORD  $0x1a9f17ed      // cset	w13, eq
	WORD  $0x91004021      // add	x1, x1, #16
	WORD  $0x91001111      // add	x17, x8, #4
	B     LBB14_7

LBB14_6:
	WORD $0x9100054a // add	x10, x10, #1
	WORD $0x8b090000 // add	x0, x0, x9
	WORD $0x8b090273 // add	x19, x19, x9
	WORD $0xeb02015f // cmp	x10, x2
	BEQ  LBB14_128

LBB14_7:
	WORD $0x9b0a7d28 // mul	x8, x9, x10
	WORD $0xd37ef544 // lsl	x4, x10, #2
	WORD $0xf94027e7 // ldr	x7, [sp, #72]
	WORD $0xf94017f5 // ldr	x21, [sp, #40]
	WORD $0xf9401ff7 // ldr	x23, [sp, #56]
	WORD $0xaa1f03f4 // mov	x20, xzr
	WORD $0x8b040236 // add	x22, x17, x4
	WORD $0xaa0103f8 // mov	x24, x1
	WORD $0x8b0402b5 // add	x21, x21, x4
	WORD $0x8b0800e7 // add	x7, x7, x8
	WORD $0x8b080168 // add	x8, x11, x8
	WORD $0xeb1600ff // cmp	x7, x22
	WORD $0xfa4832a2 // ccmp	x21, x8, #2, lo
	WORD $0x1a9f25e4 // csinc	w4, w15, wzr, hs
	WORD $0xeb1000ff // cmp	x7, x16
	WORD $0xfa4832e2 // ccmp	x23, x8, #2, lo
	WORD $0x1a9f2488 // csinc	w8, w4, wzr, hs
	WORD $0x2a2d0116 // orn	w22, w8, w13
	B    LBB14_9

LBB14_8:
	WORD $0x91000694 // add	x20, x20, #1
	WORD $0x91001318 // add	x24, x24, #4
	WORD $0x910012f7 // add	x23, x23, #4
	WORD $0xeb05029f // cmp	x20, x5
	BEQ  LBB14_6

LBB14_9:
	WORD $0x9b067e87 // mul	x7, x20, x6
	WORD $0x36000076 // tbz	w22, #0, .LBB14_11
	WORD $0xaa1f03f9 // mov	x25, xzr
	B    LBB14_14

LBB14_11:
	WORD $0xbc677aa0 // ldr	s0, [x21, x7, lsl #2]
	WORD $0xaa1803e8 // mov	x8, x24
	WORD $0xaa0003e4 // mov	x4, x0
	WORD $0xaa0c03f9 // mov	x25, x12

LBB14_12:
	WORD $0xad7f9081 // ldp	q1, q4, [x4, #-16]
	WORD $0xf1002339 // subs	x25, x25, #8
	WORD $0xad7f8d02 // ldp	q2, q3, [x8, #-16]
	WORD $0x91008108 // add	x8, x8, #32
	WORD $0x4f801041 // fmla	v1.4s, v2.4s, v0.s[0]
	WORD $0x4f801064 // fmla	v4.4s, v3.4s, v0.s[0]
	WORD $0xad3f9081 // stp	q1, q4, [x4, #-16]
	WORD $0x91008084 // add	x4, x4, #32
	BNE  LBB14_12
	WORD $0xeb0c007f // cmp	x3, x12
	WORD $0xaa0c03f9 // mov	x25, x12
	BEQ  LBB14_8

LBB14_14:
	WORD $0x9b195dc8 // madd	x8, x14, x25, x23
	WORD $0x8b190a64 // add	x4, x19, x25, lsl #2
	WORD $0xcb190079 // sub	x25, x3, x25

LBB14_15:
	WORD $0xbc677aa0 // ldr	s0, [x21, x7, lsl #2]
	WORD $0xbd400101 // ldr	s1, [x8]
	WORD $0xf1000739 // subs	x25, x25, #1
	WORD $0xbd400082 // ldr	s2, [x4]
	WORD $0x8b0e0108 // add	x8, x8, x14
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbc004480 // str	s0, [x4], #4
	BNE  LBB14_15
	B    LBB14_8

LBB14_16:
	WORD $0xd37ef4ca // lsl	x10, x6, #2
	WORD $0xd37ef5ab // lsl	x11, x13, #2
	WORD $0xb90037e0 // str	w0, [sp, #52]
	WORD $0xf100105f // cmp	x2, #4
	WORD $0xaa0203e0 // mov	x0, x2
	WORD $0xaa1f03ec // mov	x12, xzr
	BGE  LBB14_65

LBB14_17:
	WORD $0xeb02019f // cmp	x12, x2
	BGE  LBB14_128
	WORD $0x9b067d90 // mul	x16, x12, x6
	WORD $0x8b050191 // add	x17, x12, x5
	WORD $0xf9401fe7 // ldr	x7, [sp, #56]
	WORD $0xf90013f1 // str	x17, [sp, #32]
	WORD $0x8b0300b1 // add	x17, x5, x3
	WORD $0xf1001cbf // cmp	x5, #7
	WORD $0x9b097d88 // mul	x8, x12, x9
	WORD $0x8b1108e1 // add	x1, x7, x17, lsl #2
	WORD $0x1a9f97e4 // cset	w4, hi
	WORD $0xf10004df // cmp	x6, #1
	WORD $0xf94017e2 // ldr	x2, [sp, #40]
	WORD $0xd37ef52f // lsl	x15, x9, #2
	WORD $0x1a9f07e6 // cset	w6, ne
	WORD $0xf10005bf // cmp	x13, #1
	WORD $0xd100102d // sub	x13, x1, #4
	WORD $0x1a8413e1 // csel	w1, wzr, w4, ne
	WORD $0x8b050204 // add	x4, x16, x5
	WORD $0x8b10085b // add	x27, x2, x16, lsl #2
	WORD $0xf94027f0 // ldr	x16, [sp, #72]
	WORD $0xb9001be1 // str	w1, [sp, #24]
	WORD $0x8b0c0856 // add	x22, x2, x12, lsl #2
	WORD $0x8b030101 // add	x1, x8, x3
	WORD $0xaa1f03ee // mov	x14, xzr
	WORD $0x927decb1 // and	x17, x5, #0x7ffffffffffffff8
	WORD $0x8b080a14 // add	x20, x16, x8, lsl #2
	WORD $0x8b010a15 // add	x21, x16, x1, lsl #2
	WORD $0x8b040848 // add	x8, x2, x4, lsl #2
	WORD $0x1a9f04d3 // csinc	w19, w6, wzr, eq
	WORD $0x91004378 // add	x24, x27, #16
	WORD $0x910040f9 // add	x25, x7, #16
	WORD $0x910042da // add	x26, x22, #16
	WORD $0xaa0c03fc // mov	x28, x12
	WORD $0xa900efe8 // stp	x8, x27, [sp, #8]
	B    LBB14_20

LBB14_19:
	WORD $0x9100079c // add	x28, x28, #1
	WORD $0x910005ce // add	x14, x14, #1
	WORD $0x8b0a037b // add	x27, x27, x10
	WORD $0xeb00039f // cmp	x28, x0
	WORD $0x910012d6 // add	x22, x22, #4
	WORD $0x8b0a0318 // add	x24, x24, x10
	WORD $0x9100135a // add	x26, x26, #4
	BEQ  LBB14_128

LBB14_20:
	WORD $0xf100107f // cmp	x3, #4
	BGE  LBB14_22
	WORD $0xaa1f03fe // mov	x30, xzr
	B    LBB14_32

LBB14_22:
	WORD $0xf10004bf // cmp	x5, #1
	BLT  LBB14_19
	WORD $0x9b097f88 // mul	x8, x28, x9
	WORD $0xf94027f0 // ldr	x16, [sp, #72]
	WORD $0x8b080a10 // add	x16, x16, x8, lsl #2
	WORD $0xb94037e8 // ldr	w8, [sp, #52]
	WORD $0x36000328 // tbz	w8, #0, .LBB14_28
	WORD $0xf9401fe8 // ldr	x8, [sp, #56]
	WORD $0xaa1f03fe // mov	x30, xzr
	WORD $0x52800084 // mov	w4, #4

LBB14_25:
	WORD $0xaa1e03e1 // mov	x1, x30
	WORD $0xaa0403fe // mov	x30, x4
	WORD $0xaa0803e4 // mov	x4, x8
	WORD $0x8b010a01 // add	x1, x16, x1, lsl #2
	WORD $0xaa1603e6 // mov	x6, x22
	WORD $0xaa0503e7 // mov	x7, x5
	WORD $0x3dc00020 // ldr	q0, [x1]

LBB14_26:
	WORD $0x3dc00081 // ldr	q1, [x4]
	WORD $0xbd4000c2 // ldr	s2, [x6]
	WORD $0xf10004e7 // subs	x7, x7, #1
	WORD $0x8b0a00c6 // add	x6, x6, x10
	WORD $0x8b0b0084 // add	x4, x4, x11
	WORD $0x4f829021 // fmul	v1.4s, v1.4s, v2.s[0]
	WORD $0x4e21d400 // fadd	v0.4s, v0.4s, v1.4s
	BNE  LBB14_26
	WORD $0x910013c4 // add	x4, x30, #4
	WORD $0x91004108 // add	x8, x8, #16
	WORD $0x3d800020 // str	q0, [x1]
	WORD $0xeb03009f // cmp	x4, x3
	BLE  LBB14_25
	B    LBB14_32

LBB14_28:
	WORD $0xf9401fe8 // ldr	x8, [sp, #56]
	WORD $0xaa1f03fe // mov	x30, xzr
	WORD $0x52800084 // mov	w4, #4

LBB14_29:
	WORD $0xaa1e03e1 // mov	x1, x30
	WORD $0xaa0403fe // mov	x30, x4
	WORD $0xaa0803e4 // mov	x4, x8
	WORD $0x8b010a01 // add	x1, x16, x1, lsl #2
	WORD $0xaa0503e6 // mov	x6, x5
	WORD $0xaa1b03e7 // mov	x7, x27
	WORD $0x3dc00020 // ldr	q0, [x1]

LBB14_30:
	WORD $0x3dc00081 // ldr	q1, [x4]
	WORD $0xbc4044e2 // ldr	s2, [x7], #4
	WORD $0xf10004c6 // subs	x6, x6, #1
	WORD $0x8b0b0084 // add	x4, x4, x11
	WORD $0x4f829021 // fmul	v1.4s, v1.4s, v2.s[0]
	WORD $0x4e21d400 // fadd	v0.4s, v0.4s, v1.4s
	BNE  LBB14_30
	WORD $0x910013c4 // add	x4, x30, #4
	WORD $0x91004108 // add	x8, x8, #16
	WORD $0x3d800020 // str	q0, [x1]
	WORD $0xeb03009f // cmp	x4, x3
	BLE  LBB14_29

LBB14_32:
	WORD $0xeb0303df // cmp	x30, x3
	BGE  LBB14_19
	WORD $0xf10004bf // cmp	x5, #1
	BLT  LBB14_19
	WORD $0x9b0e7de1 // mul	x1, x15, x14
	WORD $0xf94027e2 // ldr	x2, [sp, #72]
	WORD $0xd37ef7c8 // lsl	x8, x30, #2
	WORD $0x9b097f90 // mul	x16, x28, x9
	WORD $0x8b010286 // add	x6, x20, x1
	WORD $0x8b0102a4 // add	x4, x21, x1
	WORD $0xf9401fe1 // ldr	x1, [sp, #56]
	WORD $0x8b100850 // add	x16, x2, x16, lsl #2
	WORD $0xb94037e2 // ldr	w2, [sp, #52]
	WORD $0x8b080021 // add	x1, x1, x8
	WORD $0x360008a2 // tbz	w2, #0, .LBB14_44
	WORD $0xf94013e2 // ldr	x2, [sp, #32]
	WORD $0x8b0e0197 // add	x23, x12, x14
	WORD $0x8b0800c6 // add	x6, x6, x8
	WORD $0x8b0e0047 // add	x7, x2, x14
	WORD $0xf94017e2 // ldr	x2, [sp, #40]
	WORD $0x8b070847 // add	x7, x2, x7, lsl #2
	WORD $0x8b170857 // add	x23, x2, x23, lsl #2
	WORD $0xeb0700df // cmp	x6, x7
	WORD $0xfa4432e2 // ccmp	x23, x4, #2, lo
	WORD $0x1a9f27e7 // cset	w7, lo
	WORD $0xeb0d00df // cmp	x6, x13
	WORD $0x8b080326 // add	x6, x25, x8
	WORD $0xfa443022 // ccmp	x1, x4, #2, lo
	WORD $0x1a9f24f7 // csinc	w23, w7, wzr, hs
	B    LBB14_37

LBB14_36:
	WORD $0x910007de // add	x30, x30, #1
	WORD $0x910010c6 // add	x6, x6, #4
	WORD $0x91001021 // add	x1, x1, #4
	WORD $0xeb0303df // cmp	x30, x3
	BEQ  LBB14_19

LBB14_37:
	WORD $0xf10030bf // cmp	x5, #12
	WORD $0xbc7e7a00 // ldr	s0, [x16, x30, lsl #2]
	WORD $0x1a9f2668 // csinc	w8, w19, wzr, hs
	WORD $0x2a170108 // orr	w8, w8, w23
	WORD $0x36000068 // tbz	w8, #0, .LBB14_39
	WORD $0xaa1f03e7 // mov	x7, xzr
	B    LBB14_42

LBB14_39:
	WORD $0xaa0603e8 // mov	x8, x6
	WORD $0xaa1a03e4 // mov	x4, x26
	WORD $0xaa1103e7 // mov	x7, x17

LBB14_40:
	WORD $0xad7f9101 // ldp	q1, q4, [x8, #-16]
	WORD $0xf10020e7 // subs	x7, x7, #8
	WORD $0xad7f8c82 // ldp	q2, q3, [x4, #-16]
	WORD $0x91008084 // add	x4, x4, #32
	WORD $0x91008108 // add	x8, x8, #32
	WORD $0x6e21dc41 // fmul	v1.4s, v2.4s, v1.4s
	WORD $0x5e0c0422 // mov	s2, v1.s[1]
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x5e140425 // mov	s5, v1.s[2]
	WORD $0x5e1c0421 // mov	s1, v1.s[3]
	WORD $0x1e222800 // fadd	s0, s0, s2
	WORD $0x6e24dc62 // fmul	v2.4s, v3.4s, v4.4s
	WORD $0x1e252800 // fadd	s0, s0, s5
	WORD $0x5e140443 // mov	s3, v2.s[2]
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x5e0c0441 // mov	s1, v2.s[1]
	WORD $0x1e222800 // fadd	s0, s0, s2
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x5e1c0441 // mov	s1, v2.s[3]
	WORD $0x1e232800 // fadd	s0, s0, s3
	WORD $0x1e212800 // fadd	s0, s0, s1
	BNE  LBB14_40
	WORD $0xeb1100bf // cmp	x5, x17
	WORD $0xaa1103e7 // mov	x7, x17
	WORD $0xbc3e7a00 // str	s0, [x16, x30, lsl #2]
	BEQ  LBB14_36

LBB14_42:
	WORD $0x9b070568 // madd	x8, x11, x7, x1
	WORD $0x9b077d44 // mul	x4, x10, x7
	WORD $0xcb0700a7 // sub	x7, x5, x7

LBB14_43:
	WORD $0xbc646ac1 // ldr	s1, [x22, x4]
	WORD $0xbd400102 // ldr	s2, [x8]
	WORD $0xf10004e7 // subs	x7, x7, #1
	WORD $0x8b0b0108 // add	x8, x8, x11
	WORD $0x8b0a0084 // add	x4, x4, x10
	WORD $0x1f020020 // fmadd	s0, s1, s2, s0
	WORD $0xbc3e7a00 // str	s0, [x16, x30, lsl #2]
	BNE  LBB14_43
	B    LBB14_36

LBB14_44:
	WORD $0x9b0e7d47 // mul	x7, x10, x14
	WORD $0xf94007e2 // ldr	x2, [sp, #8]
	WORD $0x8b0800c6 // add	x6, x6, x8
	WORD $0x8b070057 // add	x23, x2, x7
	WORD $0xf9400be2 // ldr	x2, [sp, #16]
	WORD $0xeb1700df // cmp	x6, x23
	WORD $0x8b070047 // add	x7, x2, x7
	WORD $0xfa4430e2 // ccmp	x7, x4, #2, lo
	WORD $0x1a9f27e7 // cset	w7, lo
	WORD $0xeb0d00df // cmp	x6, x13
	WORD $0x8b080326 // add	x6, x25, x8
	WORD $0xfa443022 // ccmp	x1, x4, #2, lo
	WORD $0xb9401be8 // ldr	w8, [sp, #24]
	WORD $0x1a9f24e4 // csinc	w4, w7, wzr, hs
	WORD $0x2a280097 // orn	w23, w4, w8
	B    LBB14_46

LBB14_45:
	WORD $0x910007de // add	x30, x30, #1
	WORD $0x910010c6 // add	x6, x6, #4
	WORD $0x91001021 // add	x1, x1, #4
	WORD $0xeb0303df // cmp	x30, x3
	BEQ  LBB14_19

LBB14_46:
	WORD $0xbc7e7a00 // ldr	s0, [x16, x30, lsl #2]
	WORD $0x36000077 // tbz	w23, #0, .LBB14_48
	WORD $0xaa1f03e8 // mov	x8, xzr
	B    LBB14_51

LBB14_48:
	WORD $0xaa0603e8 // mov	x8, x6
	WORD $0xaa1803e4 // mov	x4, x24
	WORD $0xaa1103e7 // mov	x7, x17

LBB14_49:
	WORD $0xad7f9101 // ldp	q1, q4, [x8, #-16]
	WORD $0xf10020e7 // subs	x7, x7, #8
	WORD $0xad7f8c82 // ldp	q2, q3, [x4, #-16]
	WORD $0x91008084 // add	x4, x4, #32
	WORD $0x91008108 // add	x8, x8, #32
	WORD $0x6e21dc41 // fmul	v1.4s, v2.4s, v1.4s
	WORD $0x5e0c0422 // mov	s2, v1.s[1]
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x5e140425 // mov	s5, v1.s[2]
	WORD $0x5e1c0421 // mov	s1, v1.s[3]
	WORD $0x1e222800 // fadd	s0, s0, s2
	WORD $0x6e24dc62 // fmul	v2.4s, v3.4s, v4.4s
	WORD $0x1e252800 // fadd	s0, s0, s5
	WORD $0x5e140443 // mov	s3, v2.s[2]
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x5e0c0441 // mov	s1, v2.s[1]
	WORD $0x1e222800 // fadd	s0, s0, s2
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x5e1c0441 // mov	s1, v2.s[3]
	WORD $0x1e232800 // fadd	s0, s0, s3
	WORD $0x1e212800 // fadd	s0, s0, s1
	BNE  LBB14_49
	WORD $0xeb1100bf // cmp	x5, x17
	WORD $0xaa1103e8 // mov	x8, x17
	WORD $0xbc3e7a00 // str	s0, [x16, x30, lsl #2]
	BEQ  LBB14_45

LBB14_51:
	WORD $0x9b080564 // madd	x4, x11, x8, x1

LBB14_52:
	WORD $0xbc687b61 // ldr	s1, [x27, x8, lsl #2]
	WORD $0xbd400082 // ldr	s2, [x4]
	WORD $0x91000508 // add	x8, x8, #1
	WORD $0xeb0800bf // cmp	x5, x8
	WORD $0x8b0b0084 // add	x4, x4, x11
	WORD $0x1f020020 // fmadd	s0, s1, s2, s0
	WORD $0xbc3e7a00 // str	s0, [x16, x30, lsl #2]
	BNE  LBB14_52
	B    LBB14_45

LBB14_53:
	WORD $0xf100045f // cmp	x2, #1
	BLT  LBB14_128
	WORD $0x91000ca8 // add	x8, x5, #3
	WORD $0xf10000bf // cmp	x5, #0
	WORD $0x9a85b10a // csel	x10, x8, x5, lt
	WORD $0xf100047f // cmp	x3, #1
	BLT  LBB14_128
	WORD $0x9342fd48 // asr	x8, x10, #2
	WORD $0x927ef54a // and	x10, x10, #0xfffffffffffffffc
	WORD $0xcb0a00aa // sub	x10, x5, x10
	WORD $0x7100050b // subs	w11, w8, #1
	BLT  LBB14_97
	BNE  LBB14_105
	WORD $0xf9401fe8 // ldr	x8, [sp, #56]
	WORD $0xf100015f // cmp	x10, #0
	BLE  LBB14_124
	WORD $0x2f00e400 // movi	d0, #0000000000000000
	WORD $0xd37ef5ac // lsl	x12, x13, #2
	WORD $0xd37ef529 // lsl	x9, x9, #2
	WORD $0xaa1f03eb // mov	x11, xzr
	WORD $0x91006108 // add	x8, x8, #24
	B    LBB14_60

LBB14_59:
	WORD $0xf94027ed // ldr	x13, [sp, #72]
	WORD $0x9100056b // add	x11, x11, #1
	WORD $0xeb02017f // cmp	x11, x2
	WORD $0x8b0901ad // add	x13, x13, x9
	WORD $0xf90027ed // str	x13, [sp, #72]
	BEQ  LBB14_128

LBB14_60:
	WORD $0x9b067d6d // mul	x13, x11, x6
	WORD $0xf94017ee // ldr	x14, [sp, #40]
	WORD $0xf94027ef // ldr	x15, [sp, #72]
	WORD $0xaa0803f0 // mov	x16, x8
	WORD $0x8b0d09cd // add	x13, x14, x13, lsl #2
	WORD $0xaa0303ee // mov	x14, x3
	B    LBB14_62

LBB14_61:
	WORD $0xf10005ce // subs	x14, x14, #1
	WORD $0x8b0c0210 // add	x16, x16, x12
	WORD $0xbc0045e1 // str	s1, [x15], #4
	BEQ  LBB14_59

LBB14_62:
	WORD $0x3dc001a1 // ldr	q1, [x13]
	WORD $0x3cde8202 // ldur	q2, [x16, #-24]
	WORD $0xf100055f // cmp	x10, #1
	WORD $0x6e22dc21 // fmul	v1.4s, v1.4s, v2.4s
	WORD $0x5e0c0422 // mov	s2, v1.s[1]
	WORD $0x1e202823 // fadd	s3, s1, s0
	WORD $0x5e140424 // mov	s4, v1.s[2]
	WORD $0x5e1c0421 // mov	s1, v1.s[3]
	WORD $0x1e232842 // fadd	s2, s2, s3
	WORD $0xbc5f8203 // ldur	s3, [x16, #-8]
	WORD $0x1e222882 // fadd	s2, s4, s2
	WORD $0x1e222821 // fadd	s1, s1, s2
	WORD $0xbd4011a2 // ldr	s2, [x13, #16]
	WORD $0x1f030441 // fmadd	s1, s2, s3, s1
	BEQ  LBB14_61
	WORD $0xbd4015a2 // ldr	s2, [x13, #20]
	WORD $0xbc5fc203 // ldur	s3, [x16, #-4]
	WORD $0xf100095f // cmp	x10, #2
	WORD $0x1f030441 // fmadd	s1, s2, s3, s1
	BEQ  LBB14_61
	WORD $0xbd4019a2 // ldr	s2, [x13, #24]
	WORD $0xbd400203 // ldr	s3, [x16]
	WORD $0x1f030441 // fmadd	s1, s2, s3, s1
	B    LBB14_61

LBB14_65:
	WORD $0xd1001068 // sub	x8, x3, #4
	WORD $0x8b0604ce // add	x14, x6, x6, lsl #1
	WORD $0xd37df0cf // lsl	x15, x6, #3
	WORD $0xf90013e8 // str	x8, [sp, #32]
	WORD $0xd342fd08 // lsr	x8, x8, #2
	WORD $0xd37cecd1 // lsl	x17, x6, #4
	WORD $0xd37ef5c1 // lsl	x1, x14, #2
	WORD $0xf94017ee // ldr	x14, [sp, #40]
	WORD $0x91000510 // add	x16, x8, #1
	WORD $0xd37ef608 // lsl	x8, x16, #2
	WORD $0xf9000bf0 // str	x16, [sp, #16]
	WORD $0x927ff610 // and	x16, x16, #0x7ffffffffffffffe
	WORD $0xf9000ff0 // str	x16, [sp, #24]
	WORD $0x910021d3 // add	x19, x14, #8
	WORD $0x8b0f01d4 // add	x20, x14, x15
	WORD $0xb27e0110 // orr	x16, x8, #0x4
	WORD $0x927df108 // and	x8, x8, #0xfffffffffffffff8
	WORD $0x8b0101d6 // add	x22, x14, x1
	WORD $0xa90043e8 // stp	x8, x16, [sp]
	WORD $0x8b0a01d9 // add	x25, x14, x10
	WORD $0x52800088 // mov	w8, #4
	B    LBB14_67

LBB14_66:
	WORD $0x91001188 // add	x8, x12, #4
	WORD $0x8b1101ce // add	x14, x14, x17
	WORD $0x91004273 // add	x19, x19, #16
	WORD $0xeb02011f // cmp	x8, x2
	WORD $0x8b1102d6 // add	x22, x22, x17
	WORD $0x8b110294 // add	x20, x20, x17
	WORD $0x8b110339 // add	x25, x25, x17
	BGT  LBB14_17

LBB14_67:
	WORD $0xf100107f // cmp	x3, #4
	WORD $0xaa0c03fc // mov	x28, x12
	WORD $0xaa0803ec // mov	x12, x8
	BGE  LBB14_69
	WORD $0xaa1f03fb // mov	x27, xzr
	B    LBB14_86

LBB14_69:
	WORD $0xf10000bf // cmp	x5, #0
	BLE  LBB14_75
	WORD $0xb2400390 // orr	x16, x28, #0x1
	WORD $0xb27f0384 // orr	x4, x28, #0x2
	WORD $0xb2400787 // orr	x7, x28, #0x3
	WORD $0x9b097f88 // mul	x8, x28, x9
	WORD $0xf94027e2 // ldr	x2, [sp, #72]
	WORD $0x9b097e10 // mul	x16, x16, x9
	WORD $0x9b097c84 // mul	x4, x4, x9
	WORD $0x8b08085e // add	x30, x2, x8, lsl #2
	WORD $0xb94037e8 // ldr	w8, [sp, #52]
	WORD $0x9b097ce7 // mul	x7, x7, x9
	WORD $0x8b100857 // add	x23, x2, x16, lsl #2
	WORD $0x8b040858 // add	x24, x2, x4, lsl #2
	WORD $0x8b070850 // add	x16, x2, x7, lsl #2
	WORD $0x36000568 // tbz	w8, #0, .LBB14_77
	WORD $0xf9401fe7 // ldr	x7, [sp, #56]
	WORD $0xaa1f03fb // mov	x27, xzr
	WORD $0x52800088 // mov	w8, #4

LBB14_72:
	WORD $0xaa1b03e4 // mov	x4, x27
	WORD $0xaa0803fb // mov	x27, x8
	WORD $0xaa0703e8 // mov	x8, x7
	WORD $0xd37ef495 // lsl	x21, x4, #2
	WORD $0xaa1303e4 // mov	x4, x19
	WORD $0xaa0503fa // mov	x26, x5
	WORD $0x3cf56bc2 // ldr	q2, [x30, x21]
	WORD $0x3cf56ae3 // ldr	q3, [x23, x21]
	WORD $0x3cf56b01 // ldr	q1, [x24, x21]
	WORD $0x3cf56a00 // ldr	q0, [x16, x21]

LBB14_73:
	WORD $0x2d7f1885 // ldp	s5, s6, [x4, #-8]
	WORD $0xf100075a // subs	x26, x26, #1
	WORD $0x2d404087 // ldp	s7, s16, [x4]
	WORD $0x8b0a0084 // add	x4, x4, x10
	WORD $0x3dc00104 // ldr	q4, [x8]
	WORD $0x8b0b0108 // add	x8, x8, x11
	WORD $0x4f859085 // fmul	v5.4s, v4.4s, v5.s[0]
	WORD $0x4f869086 // fmul	v6.4s, v4.4s, v6.s[0]
	WORD $0x4f879087 // fmul	v7.4s, v4.4s, v7.s[0]
	WORD $0x4f909084 // fmul	v4.4s, v4.4s, v16.s[0]
	WORD $0x4e25d442 // fadd	v2.4s, v2.4s, v5.4s
	WORD $0x4e26d463 // fadd	v3.4s, v3.4s, v6.4s
	WORD $0x4e27d421 // fadd	v1.4s, v1.4s, v7.4s
	WORD $0x4e24d400 // fadd	v0.4s, v0.4s, v4.4s
	BNE  LBB14_73
	WORD $0x91001368 // add	x8, x27, #4
	WORD $0x910040e7 // add	x7, x7, #16
	WORD $0x3cb56bc2 // str	q2, [x30, x21]
	WORD $0xeb03011f // cmp	x8, x3
	WORD $0x3cb56ae3 // str	q3, [x23, x21]
	WORD $0x3cb56b01 // str	q1, [x24, x21]
	WORD $0x3cb56a00 // str	q0, [x16, x21]
	BLE  LBB14_72
	B    LBB14_86

LBB14_75:
	WORD $0xf94013e8 // ldr	x8, [sp, #32]
	WORD $0xf100111f // cmp	x8, #4
	BHS  LBB14_81
	WORD $0x52800088 // mov	w8, #4
	B    LBB14_84

LBB14_77:
	WORD $0xf9401fe8 // ldr	x8, [sp, #56]
	WORD $0xaa1f03fb // mov	x27, xzr
	WORD $0x52800084 // mov	w4, #4

LBB14_78:
	WORD $0xaa1b03e7 // mov	x7, x27
	WORD $0xaa0403fb // mov	x27, x4
	WORD $0xaa0503e4 // mov	x4, x5
	WORD $0xd37ef4f5 // lsl	x21, x7, #2
	WORD $0xaa0803e7 // mov	x7, x8
	WORD $0xaa0e03fa // mov	x26, x14
	WORD $0x3cf56bc2 // ldr	q2, [x30, x21]
	WORD $0x3cf56ae3 // ldr	q3, [x23, x21]
	WORD $0x3cf56b01 // ldr	q1, [x24, x21]
	WORD $0x3cf56a00 // ldr	q0, [x16, x21]

LBB14_79:
	WORD $0x3dc000e4 // ldr	q4, [x7]
	WORD $0xbd400345 // ldr	s5, [x26]
	WORD $0xf1000484 // subs	x4, x4, #1
	WORD $0xbc6a6b46 // ldr	s6, [x26, x10]
	WORD $0xbc6f6b47 // ldr	s7, [x26, x15]
	WORD $0x8b0b00e7 // add	x7, x7, x11
	WORD $0xbc616b50 // ldr	s16, [x26, x1]
	WORD $0x4f859085 // fmul	v5.4s, v4.4s, v5.s[0]
	WORD $0x9100135a // add	x26, x26, #4
	WORD $0x4f869086 // fmul	v6.4s, v4.4s, v6.s[0]
	WORD $0x4f879087 // fmul	v7.4s, v4.4s, v7.s[0]
	WORD $0x4f909084 // fmul	v4.4s, v4.4s, v16.s[0]
	WORD $0x4e25d442 // fadd	v2.4s, v2.4s, v5.4s
	WORD $0x4e26d463 // fadd	v3.4s, v3.4s, v6.4s
	WORD $0x4e27d421 // fadd	v1.4s, v1.4s, v7.4s
	WORD $0x4e24d400 // fadd	v0.4s, v0.4s, v4.4s
	BNE  LBB14_79
	WORD $0x91001364 // add	x4, x27, #4
	WORD $0x91004108 // add	x8, x8, #16
	WORD $0x3cb56bc2 // str	q2, [x30, x21]
	WORD $0xeb03009f // cmp	x4, x3
	WORD $0x3cb56ae3 // str	q3, [x23, x21]
	WORD $0x3cb56b01 // str	q1, [x24, x21]
	WORD $0x3cb56a00 // str	q0, [x16, x21]
	BLE  LBB14_78
	B    LBB14_86

LBB14_81:
	WORD $0xf9400fe8 // ldr	x8, [sp, #24]

LBB14_82:
	WORD $0xf1000908 // subs	x8, x8, #2
	BNE  LBB14_82
	WORD $0xa94143e8 // ldp	x8, x16, [sp, #16]
	WORD $0xeb10011f // cmp	x8, x16
	WORD $0xa94023fb // ldp	x27, x8, [sp]
	BEQ  LBB14_86

LBB14_84:
	WORD $0x91001108 // add	x8, x8, #4
	WORD $0xeb03011f // cmp	x8, x3
	BLE  LBB14_84
	WORD $0xd100111b // sub	x27, x8, #4

LBB14_86:
	WORD $0xeb03037f // cmp	x27, x3
	WORD $0xaa0003e2 // mov	x2, x0
	BGE  LBB14_66
	WORD $0xf10004bf // cmp	x5, #1
	BLT  LBB14_66
	WORD $0xb2400390 // orr	x16, x28, #0x1
	WORD $0x9b097f88 // mul	x8, x28, x9
	WORD $0xf94027fa // ldr	x26, [sp, #72]
	WORD $0x9b097e04 // mul	x4, x16, x9
	WORD $0xb27f0390 // orr	x16, x28, #0x2
	WORD $0x9b097e07 // mul	x7, x16, x9
	WORD $0xb2400790 // orr	x16, x28, #0x3
	WORD $0x9b097e15 // mul	x21, x16, x9
	WORD $0x8b080b50 // add	x16, x26, x8, lsl #2
	WORD $0xb94037e8 // ldr	w8, [sp, #52]
	WORD $0x8b040b57 // add	x23, x26, x4, lsl #2
	WORD $0x8b070b58 // add	x24, x26, x7, lsl #2
	WORD $0x8b150b5c // add	x28, x26, x21, lsl #2
	WORD $0x36000408 // tbz	w8, #0, .LBB14_93
	WORD $0xf9401fe8 // ldr	x8, [sp, #56]
	WORD $0x8b1b0908 // add	x8, x8, x27, lsl #2

LBB14_90:
	WORD $0xaa0803e4 // mov	x4, x8
	WORD $0xaa1303e7 // mov	x7, x19
	WORD $0xaa0503f5 // mov	x21, x5

LBB14_91:
	WORD $0xbd400080 // ldr	s0, [x4]
	WORD $0xbc5f80e1 // ldur	s1, [x7, #-8]
	WORD $0xf10006b5 // subs	x21, x21, #1
	WORD $0xbc7b7a02 // ldr	s2, [x16, x27, lsl #2]
	WORD $0x8b0b0084 // add	x4, x4, x11
	WORD $0x1f000821 // fmadd	s1, s1, s0, s2
	WORD $0xbc3b7a01 // str	s1, [x16, x27, lsl #2]
	WORD $0xbc5fc0e1 // ldur	s1, [x7, #-4]
	WORD $0xbc7b7ae2 // ldr	s2, [x23, x27, lsl #2]
	WORD $0x1f000821 // fmadd	s1, s1, s0, s2
	WORD $0xbc3b7ae1 // str	s1, [x23, x27, lsl #2]
	WORD $0xbd4000e1 // ldr	s1, [x7]
	WORD $0xbc7b7b02 // ldr	s2, [x24, x27, lsl #2]
	WORD $0x1f000821 // fmadd	s1, s1, s0, s2
	WORD $0xbc3b7b01 // str	s1, [x24, x27, lsl #2]
	WORD $0xbd4004e1 // ldr	s1, [x7, #4]
	WORD $0xbc7b7b82 // ldr	s2, [x28, x27, lsl #2]
	WORD $0x8b0a00e7 // add	x7, x7, x10
	WORD $0x1f000820 // fmadd	s0, s1, s0, s2
	WORD $0xbc3b7b80 // str	s0, [x28, x27, lsl #2]
	BNE  LBB14_91
	WORD $0x9100077b // add	x27, x27, #1
	WORD $0x91001108 // add	x8, x8, #4
	WORD $0xeb03037f // cmp	x27, x3
	BNE  LBB14_90
	B    LBB14_66

LBB14_93:
	WORD $0xf9401fe8 // ldr	x8, [sp, #56]
	WORD $0x8b1b0907 // add	x7, x8, x27, lsl #2

LBB14_94:
	WORD $0xaa1f03e8 // mov	x8, xzr
	WORD $0xaa0703e4 // mov	x4, x7

LBB14_95:
	WORD $0xbd400080 // ldr	s0, [x4]
	WORD $0xbc6879c1 // ldr	s1, [x14, x8, lsl #2]
	WORD $0x8b0b0084 // add	x4, x4, x11
	WORD $0xbc7b7a02 // ldr	s2, [x16, x27, lsl #2]
	WORD $0x1f000821 // fmadd	s1, s1, s0, s2
	WORD $0xbc3b7a01 // str	s1, [x16, x27, lsl #2]
	WORD $0xbc687b21 // ldr	s1, [x25, x8, lsl #2]
	WORD $0xbc7b7ae2 // ldr	s2, [x23, x27, lsl #2]
	WORD $0x1f000821 // fmadd	s1, s1, s0, s2
	WORD $0xbc3b7ae1 // str	s1, [x23, x27, lsl #2]
	WORD $0xbc687a81 // ldr	s1, [x20, x8, lsl #2]
	WORD $0xbc7b7b02 // ldr	s2, [x24, x27, lsl #2]
	WORD $0x1f000821 // fmadd	s1, s1, s0, s2
	WORD $0xbc3b7b01 // str	s1, [x24, x27, lsl #2]
	WORD $0xbc687ac1 // ldr	s1, [x22, x8, lsl #2]
	WORD $0xbc7b7b82 // ldr	s2, [x28, x27, lsl #2]
	WORD $0x91000508 // add	x8, x8, #1
	WORD $0xeb0800bf // cmp	x5, x8
	WORD $0x1f000820 // fmadd	s0, s1, s0, s2
	WORD $0xbc3b7b80 // str	s0, [x28, x27, lsl #2]
	BNE  LBB14_95
	WORD $0x9100077b // add	x27, x27, #1
	WORD $0x910010e7 // add	x7, x7, #4
	WORD $0xeb03037f // cmp	x27, x3
	BNE  LBB14_94
	B    LBB14_66

LBB14_97:
	WORD $0xf9401fe8 // ldr	x8, [sp, #56]
	WORD $0xf100015f // cmp	x10, #0
	BLE  LBB14_115
	WORD $0x2f00e400 // movi	d0, #0000000000000000
	WORD $0xd37ef5ac // lsl	x12, x13, #2
	WORD $0xd37ef529 // lsl	x9, x9, #2
	WORD $0xaa1f03eb // mov	x11, xzr
	WORD $0x91002108 // add	x8, x8, #8
	B    LBB14_100

LBB14_99:
	WORD $0xf94027ed // ldr	x13, [sp, #72]
	WORD $0x9100056b // add	x11, x11, #1
	WORD $0xeb02017f // cmp	x11, x2
	WORD $0x8b0901ad // add	x13, x13, x9
	WORD $0xf90027ed // str	x13, [sp, #72]
	BEQ  LBB14_128

LBB14_100:
	WORD $0x9b067d6d // mul	x13, x11, x6
	WORD $0xf94017ee // ldr	x14, [sp, #40]
	WORD $0xf94027ef // ldr	x15, [sp, #72]
	WORD $0xaa0803f0 // mov	x16, x8
	WORD $0x8b0d09cd // add	x13, x14, x13, lsl #2
	WORD $0xaa0303ee // mov	x14, x3
	B    LBB14_102

LBB14_101:
	WORD $0xf10005ce // subs	x14, x14, #1
	WORD $0x8b0c0210 // add	x16, x16, x12
	WORD $0xbc0045e1 // str	s1, [x15], #4
	BEQ  LBB14_99

LBB14_102:
	WORD $0xbd4001a1 // ldr	s1, [x13]
	WORD $0xbc5f8202 // ldur	s2, [x16, #-8]
	WORD $0xf100055f // cmp	x10, #1
	WORD $0x1f020021 // fmadd	s1, s1, s2, s0
	BEQ  LBB14_101
	WORD $0xbd4005a2 // ldr	s2, [x13, #4]
	WORD $0xbc5fc203 // ldur	s3, [x16, #-4]
	WORD $0xf100095f // cmp	x10, #2
	WORD $0x1f030441 // fmadd	s1, s2, s3, s1
	BEQ  LBB14_101
	WORD $0xbd4009a2 // ldr	s2, [x13, #8]
	WORD $0xbd400203 // ldr	s3, [x16]
	WORD $0x1f030441 // fmadd	s1, s2, s3, s1
	B    LBB14_101

LBB14_105:
	WORD $0xb27b7bee // mov	x14, #68719476704
	WORD $0x2f00e400 // movi	d0, #0000000000000000
	WORD $0xf9401ff3 // ldr	x19, [sp, #56]
	WORD $0x8b0811c8 // add	x8, x14, x8, lsl #4
	WORD $0xaa1f03ec // mov	x12, xzr
	WORD $0x927c7d08 // and	x8, x8, #0xffffffff0
	WORD $0x9100410e // add	x14, x8, #16
	B    LBB14_107

LBB14_106:
	WORD $0x9100058c // add	x12, x12, #1
	WORD $0xeb02019f // cmp	x12, x2
	BEQ  LBB14_128

LBB14_107:
	WORD $0x9b067d88 // mul	x8, x12, x6
	WORD $0xf94017f0 // ldr	x16, [sp, #40]
	WORD $0xaa1f03ef // mov	x15, xzr
	WORD $0x9b097d80 // mul	x0, x12, x9
	WORD $0x8b080a10 // add	x16, x16, x8, lsl #2
	WORD $0xf94027e8 // ldr	x8, [sp, #72]
	WORD $0x91004211 // add	x17, x16, #16
	WORD $0x8b000900 // add	x0, x8, x0, lsl #2
	WORD $0x8b0e0221 // add	x1, x17, x14
	B    LBB14_109

LBB14_108:
	WORD $0xbc2f7801 // str	s1, [x0, x15, lsl #2]
	WORD $0x910005ef // add	x15, x15, #1
	WORD $0xeb0301ff // cmp	x15, x3
	BEQ  LBB14_106

LBB14_109:
	WORD $0x9b0d7de8 // mul	x8, x15, x13
	WORD $0x3dc00201 // ldr	q1, [x16]
	WORD $0x2a0b03e4 // mov	w4, w11
	WORD $0xaa1103e5 // mov	x5, x17
	WORD $0x8b080a68 // add	x8, x19, x8, lsl #2
	WORD $0x3cc10502 // ldr	q2, [x8], #16
	WORD $0xaa0803e7 // mov	x7, x8
	WORD $0x6e22dc21 // fmul	v1.4s, v1.4s, v2.4s

LBB14_110:
	WORD $0x3cc104a2 // ldr	q2, [x5], #16
	WORD $0x71000484 // subs	w4, w4, #1
	WORD $0x3cc104e3 // ldr	q3, [x7], #16
	WORD $0x4e22cc61 // fmla	v1.4s, v3.4s, v2.4s
	BNE  LBB14_110
	WORD $0x1e202822 // fadd	s2, s1, s0
	WORD $0x5e0c0423 // mov	s3, v1.s[1]
	WORD $0xf100055f // cmp	x10, #1
	WORD $0x1e222862 // fadd	s2, s3, s2
	WORD $0x5e140423 // mov	s3, v1.s[2]
	WORD $0x5e1c0421 // mov	s1, v1.s[3]
	WORD $0x1e222862 // fadd	s2, s3, s2
	WORD $0x1e222821 // fadd	s1, s1, s2
	BLT  LBB14_108
	WORD $0x8b0e0108 // add	x8, x8, x14
	WORD $0xbd400022 // ldr	s2, [x1]
	WORD $0xf100055f // cmp	x10, #1
	WORD $0xbd400103 // ldr	s3, [x8]
	WORD $0x1f030441 // fmadd	s1, s2, s3, s1
	BEQ  LBB14_108
	WORD $0xbd400422 // ldr	s2, [x1, #4]
	WORD $0xbd400503 // ldr	s3, [x8, #4]
	WORD $0xf100095f // cmp	x10, #2
	WORD $0x1f030441 // fmadd	s1, s2, s3, s1
	BEQ  LBB14_108
	WORD $0xbd400822 // ldr	s2, [x1, #8]
	WORD $0xbd400903 // ldr	s3, [x8, #8]
	WORD $0x1f030441 // fmadd	s1, s2, s3, s1
	B    LBB14_108

LBB14_115:
	WORD $0x6f00e400 // movi	v0.2d, #0000000000000000
	WORD $0xf94027eb // ldr	x11, [sp, #72]
	WORD $0xd37ef528 // lsl	x8, x9, #2
	WORD $0xaa1f03ea // mov	x10, xzr
	WORD $0x927dec69 // and	x9, x3, #0x7ffffffffffffff8
	WORD $0x9100416b // add	x11, x11, #16
	B    LBB14_117

LBB14_116:
	WORD $0xf94027ec // ldr	x12, [sp, #72]
	WORD $0x9100054a // add	x10, x10, #1
	WORD $0x8b08016b // add	x11, x11, x8
	WORD $0xeb02015f // cmp	x10, x2
	WORD $0x8b08018c // add	x12, x12, x8
	WORD $0xf90027ec // str	x12, [sp, #72]
	BEQ  LBB14_128

LBB14_117:
	WORD $0xf100207f // cmp	x3, #8
	BHS  LBB14_119
	WORD $0xaa1f03ed // mov	x13, xzr
	B    LBB14_122

LBB14_119:
	WORD $0xaa0b03ec // mov	x12, x11
	WORD $0xaa0903ed // mov	x13, x9

LBB14_120:
	WORD $0xf10021ad // subs	x13, x13, #8
	WORD $0xad3f8180 // stp	q0, q0, [x12, #-16]
	WORD $0x9100818c // add	x12, x12, #32
	BNE  LBB14_120
	WORD $0xeb09007f // cmp	x3, x9
	WORD $0xaa0903ed // mov	x13, x9
	BEQ  LBB14_116

LBB14_122:
	WORD $0xf94027ec // ldr	x12, [sp, #72]
	WORD $0x8b0d098c // add	x12, x12, x13, lsl #2
	WORD $0xcb0d006d // sub	x13, x3, x13

LBB14_123:
	WORD $0xf10005ad // subs	x13, x13, #1
	WORD $0xb800459f // str	wzr, [x12], #4
	BNE  LBB14_123
	B    LBB14_116

LBB14_124:
	WORD $0x2f00e400 // movi	d0, #0000000000000000
	WORD $0xd37ef5aa // lsl	x10, x13, #2
	WORD $0xd37ef528 // lsl	x8, x9, #2
	WORD $0xaa1f03e9 // mov	x9, xzr

LBB14_125:
	WORD $0x9b067d2b // mul	x11, x9, x6
	WORD $0xf94017ec // ldr	x12, [sp, #40]
	WORD $0xf94027ed // ldr	x13, [sp, #72]
	WORD $0xf9401fee // ldr	x14, [sp, #56]
	WORD $0x8b0b098b // add	x11, x12, x11, lsl #2
	WORD $0xaa0303ec // mov	x12, x3

LBB14_126:
	WORD $0x3dc00161 // ldr	q1, [x11]
	WORD $0x3dc001c2 // ldr	q2, [x14]
	WORD $0xf100058c // subs	x12, x12, #1
	WORD $0x8b0a01ce // add	x14, x14, x10
	WORD $0x6e22dc21 // fmul	v1.4s, v1.4s, v2.4s
	WORD $0x1e202822 // fadd	s2, s1, s0
	WORD $0x5e0c0423 // mov	s3, v1.s[1]
	WORD $0x1e222862 // fadd	s2, s3, s2
	WORD $0x5e140423 // mov	s3, v1.s[2]
	WORD $0x5e1c0421 // mov	s1, v1.s[3]
	WORD $0x1e222862 // fadd	s2, s3, s2
	WORD $0x1e222821 // fadd	s1, s1, s2
	WORD $0xbc0045a1 // str	s1, [x13], #4
	BNE  LBB14_126
	WORD $0xf94027eb // ldr	x11, [sp, #72]
	WORD $0x91000529 // add	x9, x9, #1
	WORD $0xeb02013f // cmp	x9, x2
	WORD $0x8b08016b // add	x11, x11, x8
	WORD $0xf90027eb // str	x11, [sp, #72]
	BNE  LBB14_125

LBB14_128:
	WORD $0xa9494ff4 // ldp	x20, x19, [sp, #144]
	WORD $0xf94023fe // ldr	x30, [sp, #64]
	WORD $0xa94857f6 // ldp	x22, x21, [sp, #128]
	WORD $0xa9475ff8 // ldp	x24, x23, [sp, #112]
	WORD $0xa94667fa // ldp	x26, x25, [sp, #96]
	WORD $0xa9456ffc // ldp	x28, x27, [sp, #80]
	WORD $0x910283ff // add	sp, sp, #160
	RET
