//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   18.1.3 (1ubuntu1)
// 	objdump 2.42
// flags: -O3
// source: src/floats_neon.c

TEXT ·vmul_const_add_to(SB), $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD dst+24(FP), R3
	MOVD n+32(FP), R4
	WORD $0xf100049f    // cmp	x4, #1
	BLT  LBB0_6
	WORD $0xa9bf7bfd    // stp	x29, x30, [sp, #-16]!
	WORD $0xf100309f    // cmp	x4, #12
	WORD $0x910003fd    // mov	x29, sp
	BHS  LBB0_7
	WORD $0xaa1f03e8    // mov	x8, xzr

LBB0_3:
	WORD $0xd37ef50b // lsl	x11, x8, #2
	WORD $0xcb080088 // sub	x8, x4, x8
	WORD $0x8b0b0069 // add	x9, x3, x11
	WORD $0x8b0b004a // add	x10, x2, x11
	WORD $0x8b0b000b // add	x11, x0, x11

LBB0_4:
	WORD $0xbc404560 // ldr	s0, [x11], #4
	WORD $0xbd400021 // ldr	s1, [x1]
	WORD $0xbc404542 // ldr	s2, [x10], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbc004520 // str	s0, [x9], #4
	BNE  LBB0_4

LBB0_5:
	WORD $0xa8c17bfd // ldp	x29, x30, [sp], #16

LBB0_6:
	RET

LBB0_7:
	WORD $0xd37ef488 // lsl	x8, x4, #2
	WORD $0x91001029 // add	x9, x1, #4
	WORD $0xeb03013f // cmp	x9, x3
	WORD $0x8b08006b // add	x11, x3, x8
	WORD $0x8b08004a // add	x10, x2, x8
	WORD $0x8b080008 // add	x8, x0, x8
	WORD $0xfa418160 // ccmp	x11, x1, #0, hi
	WORD $0x1a9f97e9 // cset	w9, hi
	WORD $0xeb03015f // cmp	x10, x3
	WORD $0xfa428160 // ccmp	x11, x2, #0, hi
	WORD $0x1a9f97ea // cset	w10, hi
	WORD $0xeb00017f // cmp	x11, x0
	WORD $0xfa438100 // ccmp	x8, x3, #0, hi
	WORD $0xaa1f03e8 // mov	x8, xzr
	BHI  LBB0_3
	WORD $0x3707fc69 // tbnz	w9, #0, .LBB0_3
	WORD $0x3707fc4a // tbnz	w10, #0, .LBB0_3
	WORD $0x4d40c820 // ld1r	{ v0.4s }, [x1]
	WORD $0x927dec88 // and	x8, x4, #0x7ffffffffffffff8
	WORD $0x91004009 // add	x9, x0, #16
	WORD $0x9100404a // add	x10, x2, #16
	WORD $0x9100406b // add	x11, x3, #16
	WORD $0xaa0803ec // mov	x12, x8

LBB0_11:
	WORD $0xad7f9141 // ldp	q1, q4, [x10, #-16]
	WORD $0xf100218c // subs	x12, x12, #8
	WORD $0xad7f8d22 // ldp	q2, q3, [x9, #-16]
	WORD $0x91008129 // add	x9, x9, #32
	WORD $0x9100814a // add	x10, x10, #32
	WORD $0x4e22cc01 // fmla	v1.4s, v0.4s, v2.4s
	WORD $0x4e23cc04 // fmla	v4.4s, v0.4s, v3.4s
	WORD $0xad3f9161 // stp	q1, q4, [x11, #-16]
	WORD $0x9100816b // add	x11, x11, #32
	BNE  LBB0_11
	WORD $0xeb04011f // cmp	x8, x4
	BNE  LBB0_3
	B    LBB0_5

TEXT ·vmul_const_add(SB), $0-32
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD n+24(FP), R3
	WORD $0xf100047f  // cmp	x3, #1
	BLT  LBB1_6
	WORD $0xa9bf7bfd  // stp	x29, x30, [sp, #-16]!
	WORD $0xf100207f  // cmp	x3, #8
	WORD $0x910003fd  // mov	x29, sp
	BHS  LBB1_7
	WORD $0xaa1f03e8  // mov	x8, xzr

LBB1_3:
	WORD $0xd37ef50a // lsl	x10, x8, #2
	WORD $0xcb080068 // sub	x8, x3, x8
	WORD $0x8b0a0049 // add	x9, x2, x10
	WORD $0x8b0a000a // add	x10, x0, x10

LBB1_4:
	WORD $0xbc404540 // ldr	s0, [x10], #4
	WORD $0xbd400021 // ldr	s1, [x1]
	WORD $0xbd400122 // ldr	s2, [x9]
	WORD $0xf1000508 // subs	x8, x8, #1
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbc004520 // str	s0, [x9], #4
	BNE  LBB1_4

LBB1_5:
	WORD $0xa8c17bfd // ldp	x29, x30, [sp], #16

LBB1_6:
	RET

LBB1_7:
	WORD $0xd37ef468 // lsl	x8, x3, #2
	WORD $0x91001029 // add	x9, x1, #4
	WORD $0xeb02013f // cmp	x9, x2
	WORD $0x8b08004a // add	x10, x2, x8
	WORD $0x8b080008 // add	x8, x0, x8
	WORD $0xfa418140 // ccmp	x10, x1, #0, hi
	WORD $0x1a9f97e9 // cset	w9, hi
	WORD $0xeb00015f // cmp	x10, x0
	WORD $0xfa428100 // ccmp	x8, x2, #0, hi
	WORD $0xaa1f03e8 // mov	x8, xzr
	BHI  LBB1_3
	WORD $0x3707fd09 // tbnz	w9, #0, .LBB1_3
	WORD $0x4d40c820 // ld1r	{ v0.4s }, [x1]
	WORD $0x927dec68 // and	x8, x3, #0x7ffffffffffffff8
	WORD $0x91004009 // add	x9, x0, #16
	WORD $0x9100404a // add	x10, x2, #16
	WORD $0xaa0803eb // mov	x11, x8

LBB1_10:
	WORD $0xad7f9141 // ldp	q1, q4, [x10, #-16]
	WORD $0xf100216b // subs	x11, x11, #8
	WORD $0xad7f8d22 // ldp	q2, q3, [x9, #-16]
	WORD $0x91008129 // add	x9, x9, #32
	WORD $0x4e22cc01 // fmla	v1.4s, v0.4s, v2.4s
	WORD $0x4e23cc04 // fmla	v4.4s, v0.4s, v3.4s
	WORD $0xad3f9141 // stp	q1, q4, [x10, #-16]
	WORD $0x9100814a // add	x10, x10, #32
	BNE  LBB1_10
	WORD $0xeb03011f // cmp	x8, x3
	BNE  LBB1_3
	B    LBB1_5

TEXT ·vmul_const_to(SB), $0-32
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD n+24(FP), R3
	WORD $0xf100047f  // cmp	x3, #1
	BLT  LBB2_6
	WORD $0xa9bf7bfd  // stp	x29, x30, [sp, #-16]!
	WORD $0xf100207f  // cmp	x3, #8
	WORD $0x910003fd  // mov	x29, sp
	BHS  LBB2_7
	WORD $0xaa1f03e8  // mov	x8, xzr

LBB2_3:
	WORD $0xd37ef50a // lsl	x10, x8, #2
	WORD $0xcb080068 // sub	x8, x3, x8
	WORD $0x8b0a0049 // add	x9, x2, x10
	WORD $0x8b0a000a // add	x10, x0, x10

LBB2_4:
	WORD $0xbc404540 // ldr	s0, [x10], #4
	WORD $0xbd400021 // ldr	s1, [x1]
	WORD $0xf1000508 // subs	x8, x8, #1
	WORD $0x1e210800 // fmul	s0, s0, s1
	WORD $0xbc004520 // str	s0, [x9], #4
	BNE  LBB2_4

LBB2_5:
	WORD $0xa8c17bfd // ldp	x29, x30, [sp], #16

LBB2_6:
	RET

LBB2_7:
	WORD $0xd37ef468 // lsl	x8, x3, #2
	WORD $0x91001029 // add	x9, x1, #4
	WORD $0xeb02013f // cmp	x9, x2
	WORD $0x8b08004a // add	x10, x2, x8
	WORD $0x8b080008 // add	x8, x0, x8
	WORD $0xfa418140 // ccmp	x10, x1, #0, hi
	WORD $0x1a9f97e9 // cset	w9, hi
	WORD $0xeb00015f // cmp	x10, x0
	WORD $0xfa428100 // ccmp	x8, x2, #0, hi
	WORD $0xaa1f03e8 // mov	x8, xzr
	BHI  LBB2_3
	WORD $0x3707fd29 // tbnz	w9, #0, .LBB2_3
	WORD $0x4d40c820 // ld1r	{ v0.4s }, [x1]
	WORD $0x927dec68 // and	x8, x3, #0x7ffffffffffffff8
	WORD $0x91004009 // add	x9, x0, #16
	WORD $0x9100404a // add	x10, x2, #16
	WORD $0xaa0803eb // mov	x11, x8

LBB2_10:
	WORD $0xad7f8921 // ldp	q1, q2, [x9, #-16]
	WORD $0xf100216b // subs	x11, x11, #8
	WORD $0x91008129 // add	x9, x9, #32
	WORD $0x6e20dc21 // fmul	v1.4s, v1.4s, v0.4s
	WORD $0x6e20dc42 // fmul	v2.4s, v2.4s, v0.4s
	WORD $0xad3f8941 // stp	q1, q2, [x10, #-16]
	WORD $0x9100814a // add	x10, x10, #32
	BNE  LBB2_10
	WORD $0xeb03011f // cmp	x8, x3
	BNE  LBB2_3
	B    LBB2_5

TEXT ·vmul_const(SB), $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD n+16(FP), R2
	WORD $0xf100045f  // cmp	x2, #1
	BLT  LBB3_8
	WORD $0xa9bf7bfd  // stp	x29, x30, [sp, #-16]!
	WORD $0xf100205f  // cmp	x2, #8
	WORD $0x910003fd  // mov	x29, sp
	BLO  LBB3_4
	WORD $0x91001028  // add	x8, x1, #4
	WORD $0xeb00011f  // cmp	x8, x0
	BLS  LBB3_9
	WORD $0x8b020808  // add	x8, x0, x2, lsl #2
	WORD $0xeb01011f  // cmp	x8, x1
	BLS  LBB3_9

LBB3_4:
	WORD $0xaa1f03e8 // mov	x8, xzr

LBB3_5:
	WORD $0x8b080809 // add	x9, x0, x8, lsl #2
	WORD $0xcb080048 // sub	x8, x2, x8

LBB3_6:
	WORD $0xbd400020 // ldr	s0, [x1]
	WORD $0xbd400121 // ldr	s1, [x9]
	WORD $0xf1000508 // subs	x8, x8, #1
	WORD $0x1e210800 // fmul	s0, s0, s1
	WORD $0xbc004520 // str	s0, [x9], #4
	BNE  LBB3_6

LBB3_7:
	WORD $0xa8c17bfd // ldp	x29, x30, [sp], #16

LBB3_8:
	RET

LBB3_9:
	WORD $0x4d40c820 // ld1r	{ v0.4s }, [x1]
	WORD $0x927dec48 // and	x8, x2, #0x7ffffffffffffff8
	WORD $0x91004009 // add	x9, x0, #16
	WORD $0xaa0803ea // mov	x10, x8

LBB3_10:
	WORD $0xad7f8921 // ldp	q1, q2, [x9, #-16]
	WORD $0xf100214a // subs	x10, x10, #8
	WORD $0x6e21dc01 // fmul	v1.4s, v0.4s, v1.4s
	WORD $0x6e22dc02 // fmul	v2.4s, v0.4s, v2.4s
	WORD $0xad3f8921 // stp	q1, q2, [x9, #-16]
	WORD $0x91008129 // add	x9, x9, #32
	BNE  LBB3_10
	WORD $0xeb02011f // cmp	x8, x2
	BEQ  LBB3_7
	B    LBB3_5

TEXT ·vadd_const(SB), $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD n+16(FP), R2
	WORD $0xf100045f  // cmp	x2, #1
	BLT  LBB4_8
	WORD $0xa9bf7bfd  // stp	x29, x30, [sp, #-16]!
	WORD $0xf100205f  // cmp	x2, #8
	WORD $0x910003fd  // mov	x29, sp
	BLO  LBB4_4
	WORD $0x91001028  // add	x8, x1, #4
	WORD $0xeb00011f  // cmp	x8, x0
	BLS  LBB4_9
	WORD $0x8b020808  // add	x8, x0, x2, lsl #2
	WORD $0xeb01011f  // cmp	x8, x1
	BLS  LBB4_9

LBB4_4:
	WORD $0xaa1f03e8 // mov	x8, xzr

LBB4_5:
	WORD $0x8b080809 // add	x9, x0, x8, lsl #2
	WORD $0xcb080048 // sub	x8, x2, x8

LBB4_6:
	WORD $0xbd400020 // ldr	s0, [x1]
	WORD $0xbd400121 // ldr	s1, [x9]
	WORD $0xf1000508 // subs	x8, x8, #1
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0xbc004520 // str	s0, [x9], #4
	BNE  LBB4_6

LBB4_7:
	WORD $0xa8c17bfd // ldp	x29, x30, [sp], #16

LBB4_8:
	RET

LBB4_9:
	WORD $0x4d40c820 // ld1r	{ v0.4s }, [x1]
	WORD $0x927dec48 // and	x8, x2, #0x7ffffffffffffff8
	WORD $0x91004009 // add	x9, x0, #16
	WORD $0xaa0803ea // mov	x10, x8

LBB4_10:
	WORD $0xad7f8921 // ldp	q1, q2, [x9, #-16]
	WORD $0xf100214a // subs	x10, x10, #8
	WORD $0x4e21d401 // fadd	v1.4s, v0.4s, v1.4s
	WORD $0x4e22d402 // fadd	v2.4s, v0.4s, v2.4s
	WORD $0xad3f8921 // stp	q1, q2, [x9, #-16]
	WORD $0x91008129 // add	x9, x9, #32
	BNE  LBB4_10
	WORD $0xeb02011f // cmp	x8, x2
	BEQ  LBB4_7
	B    LBB4_5

TEXT ·vsub_to(SB), $0-32
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD n+24(FP), R3
	WORD $0xf100047f  // cmp	x3, #1
	BLT  LBB5_6
	WORD $0xa9bf7bfd  // stp	x29, x30, [sp, #-16]!
	WORD $0xf100207f  // cmp	x3, #8
	WORD $0x910003fd  // mov	x29, sp
	BHS  LBB5_7
	WORD $0xaa1f03e8  // mov	x8, xzr

LBB5_3:
	WORD $0xd37ef50b // lsl	x11, x8, #2
	WORD $0xcb080068 // sub	x8, x3, x8
	WORD $0x8b0b0049 // add	x9, x2, x11
	WORD $0x8b0b002a // add	x10, x1, x11
	WORD $0x8b0b000b // add	x11, x0, x11

LBB5_4:
	WORD $0xbc404560 // ldr	s0, [x11], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	WORD $0xbc404541 // ldr	s1, [x10], #4
	WORD $0x1e213800 // fsub	s0, s0, s1
	WORD $0xbc004520 // str	s0, [x9], #4
	BNE  LBB5_4

LBB5_5:
	WORD $0xa8c17bfd // ldp	x29, x30, [sp], #16

LBB5_6:
	RET

LBB5_7:
	WORD $0xcb000048 // sub	x8, x2, x0
	WORD $0xf100811f // cmp	x8, #32
	WORD $0xaa1f03e8 // mov	x8, xzr
	BLO  LBB5_3
	WORD $0xcb010049 // sub	x9, x2, x1
	WORD $0xf100813f // cmp	x9, #32
	BLO  LBB5_3
	WORD $0x927dec68 // and	x8, x3, #0x7ffffffffffffff8
	WORD $0x91004009 // add	x9, x0, #16
	WORD $0x9100402a // add	x10, x1, #16
	WORD $0x9100404b // add	x11, x2, #16
	WORD $0xaa0803ec // mov	x12, x8

LBB5_10:
	WORD $0xad7f8d40 // ldp	q0, q3, [x10, #-16]
	WORD $0xf100218c // subs	x12, x12, #8
	WORD $0xad7f8921 // ldp	q1, q2, [x9, #-16]
	WORD $0x91008129 // add	x9, x9, #32
	WORD $0x9100814a // add	x10, x10, #32
	WORD $0x4ea0d420 // fsub	v0.4s, v1.4s, v0.4s
	WORD $0x4ea3d441 // fsub	v1.4s, v2.4s, v3.4s
	WORD $0xad3f8560 // stp	q0, q1, [x11, #-16]
	WORD $0x9100816b // add	x11, x11, #32
	BNE  LBB5_10
	WORD $0xeb03011f // cmp	x8, x3
	BNE  LBB5_3
	B    LBB5_5

TEXT ·vsub(SB), $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD n+16(FP), R2
	WORD $0xf100045f  // cmp	x2, #1
	BLT  LBB6_8
	WORD $0xa9bf7bfd  // stp	x29, x30, [sp, #-16]!
	WORD $0xf100205f  // cmp	x2, #8
	WORD $0x910003fd  // mov	x29, sp
	BLO  LBB6_4
	WORD $0xd37ef448  // lsl	x8, x2, #2
	WORD $0x8b080029  // add	x9, x1, x8
	WORD $0xeb00013f  // cmp	x9, x0
	BLS  LBB6_9
	WORD $0x8b080008  // add	x8, x0, x8
	WORD $0xeb01011f  // cmp	x8, x1
	BLS  LBB6_9

LBB6_4:
	WORD $0xaa1f03e8 // mov	x8, xzr

LBB6_5:
	WORD $0xd37ef50a // lsl	x10, x8, #2
	WORD $0xcb080048 // sub	x8, x2, x8
	WORD $0x8b0a0009 // add	x9, x0, x10
	WORD $0x8b0a002a // add	x10, x1, x10

LBB6_6:
	WORD $0xbc404540 // ldr	s0, [x10], #4
	WORD $0xbd400121 // ldr	s1, [x9]
	WORD $0xf1000508 // subs	x8, x8, #1
	WORD $0x1e203820 // fsub	s0, s1, s0
	WORD $0xbc004520 // str	s0, [x9], #4
	BNE  LBB6_6

LBB6_7:
	WORD $0xa8c17bfd // ldp	x29, x30, [sp], #16

LBB6_8:
	RET

LBB6_9:
	WORD $0x927dec48 // and	x8, x2, #0x7ffffffffffffff8
	WORD $0x91004029 // add	x9, x1, #16
	WORD $0x9100400a // add	x10, x0, #16
	WORD $0xaa0803eb // mov	x11, x8

LBB6_10:
	WORD $0xad7f8d40 // ldp	q0, q3, [x10, #-16]
	WORD $0xf100216b // subs	x11, x11, #8
	WORD $0xad7f8921 // ldp	q1, q2, [x9, #-16]
	WORD $0x91008129 // add	x9, x9, #32
	WORD $0x4ea1d400 // fsub	v0.4s, v0.4s, v1.4s
	WORD $0x4ea2d461 // fsub	v1.4s, v3.4s, v2.4s
	WORD $0xad3f8540 // stp	q0, q1, [x10, #-16]
	WORD $0x9100814a // add	x10, x10, #32
	BNE  LBB6_10
	WORD $0xeb02011f // cmp	x8, x2
	BEQ  LBB6_7
	B    LBB6_5

TEXT ·vmul_to(SB), $0-32
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD n+24(FP), R3
	WORD $0xf100047f  // cmp	x3, #1
	BLT  LBB7_6
	WORD $0xa9bf7bfd  // stp	x29, x30, [sp, #-16]!
	WORD $0xf100207f  // cmp	x3, #8
	WORD $0x910003fd  // mov	x29, sp
	BHS  LBB7_7
	WORD $0xaa1f03e8  // mov	x8, xzr

LBB7_3:
	WORD $0xd37ef50b // lsl	x11, x8, #2
	WORD $0xcb080068 // sub	x8, x3, x8
	WORD $0x8b0b0049 // add	x9, x2, x11
	WORD $0x8b0b002a // add	x10, x1, x11
	WORD $0x8b0b000b // add	x11, x0, x11

LBB7_4:
	WORD $0xbc404560 // ldr	s0, [x11], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	WORD $0xbc404541 // ldr	s1, [x10], #4
	WORD $0x1e210800 // fmul	s0, s0, s1
	WORD $0xbc004520 // str	s0, [x9], #4
	BNE  LBB7_4

LBB7_5:
	WORD $0xa8c17bfd // ldp	x29, x30, [sp], #16

LBB7_6:
	RET

LBB7_7:
	WORD $0xcb000048 // sub	x8, x2, x0
	WORD $0xf100811f // cmp	x8, #32
	WORD $0xaa1f03e8 // mov	x8, xzr
	BLO  LBB7_3
	WORD $0xcb010049 // sub	x9, x2, x1
	WORD $0xf100813f // cmp	x9, #32
	BLO  LBB7_3
	WORD $0x927dec68 // and	x8, x3, #0x7ffffffffffffff8
	WORD $0x91004009 // add	x9, x0, #16
	WORD $0x9100402a // add	x10, x1, #16
	WORD $0x9100404b // add	x11, x2, #16
	WORD $0xaa0803ec // mov	x12, x8

LBB7_10:
	WORD $0xad7f8d40 // ldp	q0, q3, [x10, #-16]
	WORD $0xf100218c // subs	x12, x12, #8
	WORD $0xad7f8921 // ldp	q1, q2, [x9, #-16]
	WORD $0x91008129 // add	x9, x9, #32
	WORD $0x9100814a // add	x10, x10, #32
	WORD $0x6e20dc20 // fmul	v0.4s, v1.4s, v0.4s
	WORD $0x6e23dc41 // fmul	v1.4s, v2.4s, v3.4s
	WORD $0xad3f8560 // stp	q0, q1, [x11, #-16]
	WORD $0x9100816b // add	x11, x11, #32
	BNE  LBB7_10
	WORD $0xeb03011f // cmp	x8, x3
	BNE  LBB7_3
	B    LBB7_5

TEXT ·vdiv_to(SB), $0-32
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD n+24(FP), R3
	WORD $0xf100047f  // cmp	x3, #1
	BLT  LBB8_6
	WORD $0xa9bf7bfd  // stp	x29, x30, [sp, #-16]!
	WORD $0xf100207f  // cmp	x3, #8
	WORD $0x910003fd  // mov	x29, sp
	BHS  LBB8_7
	WORD $0xaa1f03e8  // mov	x8, xzr

LBB8_3:
	WORD $0xd37ef50b // lsl	x11, x8, #2
	WORD $0xcb080068 // sub	x8, x3, x8
	WORD $0x8b0b0049 // add	x9, x2, x11
	WORD $0x8b0b002a // add	x10, x1, x11
	WORD $0x8b0b000b // add	x11, x0, x11

LBB8_4:
	WORD $0xbc404560 // ldr	s0, [x11], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	WORD $0xbc404541 // ldr	s1, [x10], #4
	WORD $0x1e211800 // fdiv	s0, s0, s1
	WORD $0xbc004520 // str	s0, [x9], #4
	BNE  LBB8_4

LBB8_5:
	WORD $0xa8c17bfd // ldp	x29, x30, [sp], #16

LBB8_6:
	RET

LBB8_7:
	WORD $0xcb000048 // sub	x8, x2, x0
	WORD $0xf100811f // cmp	x8, #32
	WORD $0xaa1f03e8 // mov	x8, xzr
	BLO  LBB8_3
	WORD $0xcb010049 // sub	x9, x2, x1
	WORD $0xf100813f // cmp	x9, #32
	BLO  LBB8_3
	WORD $0x927dec68 // and	x8, x3, #0x7ffffffffffffff8
	WORD $0x91004009 // add	x9, x0, #16
	WORD $0x9100402a // add	x10, x1, #16
	WORD $0x9100404b // add	x11, x2, #16
	WORD $0xaa0803ec // mov	x12, x8

LBB8_10:
	WORD $0xad7f8d40 // ldp	q0, q3, [x10, #-16]
	WORD $0xf100218c // subs	x12, x12, #8
	WORD $0xad7f8921 // ldp	q1, q2, [x9, #-16]
	WORD $0x91008129 // add	x9, x9, #32
	WORD $0x9100814a // add	x10, x10, #32
	WORD $0x6e20fc20 // fdiv	v0.4s, v1.4s, v0.4s
	WORD $0x6e23fc41 // fdiv	v1.4s, v2.4s, v3.4s
	WORD $0xad3f8560 // stp	q0, q1, [x11, #-16]
	WORD $0x9100816b // add	x11, x11, #32
	BNE  LBB8_10
	WORD $0xeb03011f // cmp	x8, x3
	BNE  LBB8_3
	B    LBB8_5

TEXT ·vsqrt_to(SB), $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD n+16(FP), R2
	WORD $0xa9bf7bfd  // stp	x29, x30, [sp, #-16]!
	WORD $0x91000c48  // add	x8, x2, #3
	WORD $0xf100005f  // cmp	x2, #0
	WORD $0x910003fd  // mov	x29, sp
	WORD $0x9a82b108  // csel	x8, x8, x2, lt
	WORD $0xd342fd09  // lsr	x9, x8, #2
	WORD $0x927ef508  // and	x8, x8, #0xfffffffffffffffc
	WORD $0xcb080048  // sub	x8, x2, x8
	WORD $0x7100053f  // cmp	w9, #1
	BLT  LBB9_2

LBB9_1:
	WORD $0x3cc10400 // ldr	q0, [x0], #16
	WORD $0x71000529 // subs	w9, w9, #1
	WORD $0x6ea1f800 // fsqrt	v0.4s, v0.4s
	WORD $0x3c810420 // str	q0, [x1], #16
	BNE  LBB9_1

LBB9_2:
	WORD $0x7100051f // cmp	w8, #1
	BLT  LBB9_5
	WORD $0x92407d08 // and	x8, x8, #0xffffffff

LBB9_4:
	WORD $0x0ddfc800 // ld1r	{ v0.2s }, [x0], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	WORD $0x2ea1f800 // fsqrt	v0.2s, v0.2s
	WORD $0x0d9f8020 // st1	{ v0.s }[0], [x1], #4
	BNE  LBB9_4

LBB9_5:
	WORD $0xa8c17bfd // ldp	x29, x30, [sp], #16
	RET

TEXT ·vdot(SB), $8-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD n+16(FP), R2
	WORD $0xa9bf7bfd  // stp	x29, x30, [sp, #-16]!
	WORD $0x91000c48  // add	x8, x2, #3
	WORD $0xf100005f  // cmp	x2, #0
	WORD $0x910003fd  // mov	x29, sp
	WORD $0x9a82b108  // csel	x8, x8, x2, lt
	WORD $0x9342fd0a  // asr	x10, x8, #2
	WORD $0x927ef508  // and	x8, x8, #0xfffffffffffffffc
	WORD $0xcb080048  // sub	x8, x2, x8
	WORD $0x7100055f  // cmp	w10, #1
	BLT  LBB10_5
	WORD $0x3cc10400  // ldr	q0, [x0], #16
	WORD $0x71000549  // subs	w9, w10, #1
	WORD $0x3cc10421  // ldr	q1, [x1], #16
	WORD $0x6e21dc00  // fmul	v0.4s, v0.4s, v1.4s
	BEQ  LBB10_6
	WORD $0xb27b7beb  // mov	x11, #68719476704
	WORD $0xaa0103ec  // mov	x12, x1
	WORD $0x8b0a116a  // add	x10, x11, x10, lsl #4
	WORD $0xaa0003eb  // mov	x11, x0
	WORD $0x927c7d4a  // and	x10, x10, #0xffffffff0
	WORD $0x9100414a  // add	x10, x10, #16

LBB10_3:
	WORD $0x3cc10561 // ldr	q1, [x11], #16
	WORD $0x71000529 // subs	w9, w9, #1
	WORD $0x3cc10582 // ldr	q2, [x12], #16
	WORD $0x4e21cc40 // fmla	v0.4s, v2.4s, v1.4s
	BNE  LBB10_3
	WORD $0x8b0a0000 // add	x0, x0, x10
	WORD $0x8b0a0021 // add	x1, x1, x10
	B    LBB10_6

LBB10_5:
	WORD $0x6f00e400 // movi	v0.2d, #0000000000000000

LBB10_6:
	WORD $0x2f00e401 // movi	d1, #0000000000000000
	WORD $0x5e0c0402 // mov	s2, v0.s[1]
	WORD $0x7100011f // cmp	w8, #0
	WORD $0x1e212801 // fadd	s1, s0, s1
	WORD $0x1e212841 // fadd	s1, s2, s1
	WORD $0x5e140402 // mov	s2, v0.s[2]
	WORD $0x5e1c0400 // mov	s0, v0.s[3]
	WORD $0x1e212841 // fadd	s1, s2, s1
	WORD $0x1e212800 // fadd	s0, s0, s1
	BLE  LBB10_14
	WORD $0x92407d09 // and	x9, x8, #0xffffffff
	WORD $0xf100213f // cmp	x9, #8
	BHS  LBB10_9
	WORD $0xaa1f03e8 // mov	x8, xzr
	B    LBB10_12

LBB10_9:
	WORD $0x9240090a // and	x10, x8, #0x7
	WORD $0x9100400b // add	x11, x0, #16
	WORD $0x9100402c // add	x12, x1, #16
	WORD $0xcb0a0128 // sub	x8, x9, x10
	WORD $0xaa0803ed // mov	x13, x8

LBB10_10:
	WORD $0xad7f9181 // ldp	q1, q4, [x12, #-16]
	WORD $0xf10021ad // subs	x13, x13, #8
	WORD $0xad7f8d62 // ldp	q2, q3, [x11, #-16]
	WORD $0x9100816b // add	x11, x11, #32
	WORD $0x9100818c // add	x12, x12, #32
	WORD $0x6e21dc41 // fmul	v1.4s, v2.4s, v1.4s
	WORD $0x5e0c0422 // mov	s2, v1.s[1]
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x5e140425 // mov	s5, v1.s[2]
	WORD $0x5e1c0421 // mov	s1, v1.s[3]
	WORD $0x1e222800 // fadd	s0, s0, s2
	WORD $0x6e24dc62 // fmul	v2.4s, v3.4s, v4.4s
	WORD $0x1e252800 // fadd	s0, s0, s5
	WORD $0x5e140443 // mov	s3, v2.s[2]
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x5e0c0441 // mov	s1, v2.s[1]
	WORD $0x1e222800 // fadd	s0, s0, s2
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x5e1c0441 // mov	s1, v2.s[3]
	WORD $0x1e232800 // fadd	s0, s0, s3
	WORD $0x1e212800 // fadd	s0, s0, s1
	BNE  LBB10_10
	WORD $0xb400014a // cbz	x10, .LBB10_14

LBB10_12:
	WORD $0xd37ef50a // lsl	x10, x8, #2
	WORD $0xcb080128 // sub	x8, x9, x8
	WORD $0x8b0a0029 // add	x9, x1, x10
	WORD $0x8b0a000a // add	x10, x0, x10

LBB10_13:
	WORD $0xbc404541 // ldr	s1, [x10], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	WORD $0xbc404522 // ldr	s2, [x9], #4
	WORD $0x1f020020 // fmadd	s0, s1, s2, s0
	BNE  LBB10_13

LBB10_14:
	WORD  $0xa8c17bfd       // ldp	x29, x30, [sp], #16
	FMOVS F0, result+24(FP)
	RET

TEXT ·veuclidean(SB), $8-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD n+16(FP), R2
	WORD $0xa9bf7bfd  // stp	x29, x30, [sp, #-16]!
	WORD $0x910003fd  // mov	x29, sp
	WORD $0xd10043ff  // sub	sp, sp, #16
	WORD $0x91000c48  // add	x8, x2, #3
	WORD $0xf100005f  // cmp	x2, #0
	WORD $0x9a82b108  // csel	x8, x8, x2, lt
	WORD $0x9342fd0a  // asr	x10, x8, #2
	WORD $0x927ef508  // and	x8, x8, #0xfffffffffffffffc
	WORD $0xcb080049  // sub	x9, x2, x8
	WORD $0x7100055f  // cmp	w10, #1
	BLT  LBB11_5
	WORD $0x3cc10400  // ldr	q0, [x0], #16
	WORD $0x71000548  // subs	w8, w10, #1
	WORD $0x3cc10421  // ldr	q1, [x1], #16
	WORD $0x4ea1d400  // fsub	v0.4s, v0.4s, v1.4s
	WORD $0x6e20dc00  // fmul	v0.4s, v0.4s, v0.4s
	BEQ  LBB11_6
	WORD $0xb27b7beb  // mov	x11, #68719476704
	WORD $0xaa0103ec  // mov	x12, x1
	WORD $0x8b0a116a  // add	x10, x11, x10, lsl #4
	WORD $0x927c7d4a  // and	x10, x10, #0xffffffff0
	WORD $0x9100414b  // add	x11, x10, #16
	WORD $0x8b0b000a  // add	x10, x0, x11

LBB11_3:
	WORD $0x3cc10401 // ldr	q1, [x0], #16
	WORD $0x71000508 // subs	w8, w8, #1
	WORD $0x3cc10582 // ldr	q2, [x12], #16
	WORD $0x4ea2d421 // fsub	v1.4s, v1.4s, v2.4s
	WORD $0x4e21cc20 // fmla	v0.4s, v1.4s, v1.4s
	BNE  LBB11_3
	WORD $0x8b0b0021 // add	x1, x1, x11
	WORD $0xaa0a03e0 // mov	x0, x10
	B    LBB11_6

LBB11_5:
	WORD $0x6f00e400 // movi	v0.2d, #0000000000000000

LBB11_6:
	WORD $0x7e30d801 // faddp	s1, v0.2s
	WORD $0x5e140402 // mov	s2, v0.s[2]
	WORD $0x7100013f // cmp	w9, #0
	WORD $0x5e1c0400 // mov	s0, v0.s[3]
	WORD $0x1e212841 // fadd	s1, s2, s1
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0xbd000be0 // str	s0, [sp, #8]
	BLE  LBB11_15
	WORD $0x92407d28 // and	x8, x9, #0xffffffff
	WORD $0xf100211f // cmp	x8, #8
	BHS  LBB11_9
	WORD $0xaa1f03e9 // mov	x9, xzr
	B    LBB11_12

LBB11_9:
	WORD $0x9240092a // and	x10, x9, #0x7
	WORD $0x9100400b // add	x11, x0, #16
	WORD $0x9100402c // add	x12, x1, #16
	WORD $0xcb0a0109 // sub	x9, x8, x10
	WORD $0xaa0903ed // mov	x13, x9

LBB11_10:
	WORD $0xad7f9181 // ldp	q1, q4, [x12, #-16]
	WORD $0xf10021ad // subs	x13, x13, #8
	WORD $0xad7f8d62 // ldp	q2, q3, [x11, #-16]
	WORD $0x9100816b // add	x11, x11, #32
	WORD $0x9100818c // add	x12, x12, #32
	WORD $0x4ea1d441 // fsub	v1.4s, v2.4s, v1.4s
	WORD $0x6e21dc21 // fmul	v1.4s, v1.4s, v1.4s
	WORD $0x5e0c0422 // mov	s2, v1.s[1]
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x5e140425 // mov	s5, v1.s[2]
	WORD $0x5e1c0421 // mov	s1, v1.s[3]
	WORD $0x1e222800 // fadd	s0, s0, s2
	WORD $0x4ea4d462 // fsub	v2.4s, v3.4s, v4.4s
	WORD $0x1e252800 // fadd	s0, s0, s5
	WORD $0x6e22dc42 // fmul	v2.4s, v2.4s, v2.4s
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x5e0c0441 // mov	s1, v2.s[1]
	WORD $0x5e140443 // mov	s3, v2.s[2]
	WORD $0x1e222800 // fadd	s0, s0, s2
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x5e1c0441 // mov	s1, v2.s[3]
	WORD $0x1e232800 // fadd	s0, s0, s3
	WORD $0x1e212800 // fadd	s0, s0, s1
	BNE  LBB11_10
	WORD $0xb400016a // cbz	x10, .LBB11_14

LBB11_12:
	WORD $0xd37ef52b // lsl	x11, x9, #2
	WORD $0xcb090108 // sub	x8, x8, x9
	WORD $0x8b0b002a // add	x10, x1, x11
	WORD $0x8b0b000b // add	x11, x0, x11

LBB11_13:
	WORD $0xbc404561 // ldr	s1, [x11], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	WORD $0xbc404542 // ldr	s2, [x10], #4
	WORD $0x1e223821 // fsub	s1, s1, s2
	WORD $0x1f010020 // fmadd	s0, s1, s1, s0
	BNE  LBB11_13

LBB11_14:
	WORD $0xbd000be0 // str	s0, [sp, #8]

LBB11_15:
	WORD  $0xfd4007e0       // ldr	d0, [sp, #8]
	WORD  $0x2ea1f800       // fsqrt	v0.2s, v0.2s
	WORD  $0x910043ff       // add	sp, sp, #16
	WORD  $0xa8c17bfd       // ldp	x29, x30, [sp], #16
	FMOVS F0, result+24(FP)
	RET

TEXT ·vmm(SB), $24-88
	MOVD transA+0(FP), R0
	MOVD transB+1(FP), R1
	MOVD m+8(FP), R2
	MOVD n+16(FP), R3
	MOVD k+24(FP), R4
	MOVD a+32(FP), R5
	MOVD lda+40(FP), R6
	MOVD b+48(FP), R7
	MOVD ldb+56(FP), R8
	MOVD R8, 0(RSP)
	MOVD c+64(FP), R8
	MOVD R8, 8(RSP)
	MOVD ldc+72(FP), R8
	MOVD R8, 16(RSP)
	WORD $0xa9ba7bfd      // stp	x29, x30, [sp, #-96]!
	WORD $0x910003fd      // mov	x29, sp
	WORD $0xa9016ffc      // stp	x28, x27, [sp, #16]
	WORD $0xa946a7a8      // ldp	x8, x9, [x29, #104]
	WORD $0xf94033ab      // ldr	x11, [x29, #96]
	WORD $0xa90267fa      // stp	x26, x25, [sp, #32]
	WORD $0xa9035ff8      // stp	x24, x23, [sp, #48]
	WORD $0xa90457f6      // stp	x22, x21, [sp, #64]
	WORD $0xa9054ff4      // stp	x20, x19, [sp, #80]
	WORD $0x37000a80      // tbnz	w0, #0, .LBB12_16
	WORD $0x37000a61      // tbnz	w1, #0, .LBB12_16
	WORD $0xf100045f      // cmp	x2, #1
	BLT  LBB12_101
	WORD $0xf100048c      // subs	x12, x4, #1
	BLT  LBB12_101
	WORD $0xf100047f      // cmp	x3, #1
	BLT  LBB12_101
	WORD $0x9b0b0d8f      // madd	x15, x12, x11, x3
	WORD $0xd37ef529      // lsl	x9, x9, #2
	WORD $0xd37ef4cc      // lsl	x12, x6, #2
	WORD $0x8b03090d      // add	x13, x8, x3, lsl #2
	WORD $0x8b0408ae      // add	x14, x5, x4, lsl #2
	WORD $0xd37ef571      // lsl	x17, x11, #2
	WORD $0xd37df56b      // ubfx	x11, x11, #61, #1
	WORD $0xaa1f03ea      // mov	x10, xzr
	WORD $0x927df070      // and	x16, x3, #0xfffffffffffffff8
	WORD $0x910040e0      // add	x0, x7, #16
	WORD $0x91004101      // add	x1, x8, #16
	WORD $0xaa0803f3      // mov	x19, x8
	WORD $0x8b0f08ef      // add	x15, x7, x15, lsl #2
	B    LBB12_7

LBB12_6:
	WORD $0x9100054a // add	x10, x10, #1
	WORD $0x8b090021 // add	x1, x1, x9
	WORD $0x8b090273 // add	x19, x19, x9
	WORD $0xeb02015f // cmp	x10, x2
	BEQ  LBB12_101

LBB12_7:
	WORD $0x9b0a7d35 // mul	x21, x9, x10
	WORD $0xaa1f03f4 // mov	x20, xzr
	WORD $0x9b0a7d96 // mul	x22, x12, x10
	WORD $0x9b067d57 // mul	x23, x10, x6
	WORD $0x8b150118 // add	x24, x8, x21
	WORD $0x8b1501b9 // add	x25, x13, x21
	WORD $0xeb0f031f // cmp	x24, x15
	WORD $0x8b1601d5 // add	x21, x14, x22
	WORD $0xfa473320 // ccmp	x25, x7, #0, lo
	WORD $0x8b1600b6 // add	x22, x5, x22
	WORD $0x1a9f957a // csinc	w26, w11, wzr, ls
	WORD $0xeb15031f // cmp	x24, x21
	WORD $0xaa0003f8 // mov	x24, x0
	WORD $0x8b1708b5 // add	x21, x5, x23, lsl #2
	WORD $0xfa5932c2 // ccmp	x22, x25, #2, lo
	WORD $0xaa0703f7 // mov	x23, x7
	WORD $0x1a9f2756 // csinc	w22, w26, wzr, hs
	B    LBB12_9

LBB12_8:
	WORD $0x91000694 // add	x20, x20, #1
	WORD $0x8b110318 // add	x24, x24, x17
	WORD $0x8b1102f7 // add	x23, x23, x17
	WORD $0xeb04029f // cmp	x20, x4
	BEQ  LBB12_6

LBB12_9:
	WORD $0xf100207f // cmp	x3, #8
	WORD $0x1a9f26d9 // csinc	w25, w22, wzr, hs
	WORD $0x36000079 // tbz	w25, #0, .LBB12_11
	WORD $0xaa1f03fb // mov	x27, xzr
	B    LBB12_14

LBB12_11:
	WORD $0x8b140ab9 // add	x25, x21, x20, lsl #2
	WORD $0xaa0103fa // mov	x26, x1
	WORD $0xaa1803fb // mov	x27, x24
	WORD $0x4d40cb20 // ld1r	{ v0.4s }, [x25]
	WORD $0xaa1003f9 // mov	x25, x16

LBB12_12:
	WORD $0xad7f9341 // ldp	q1, q4, [x26, #-16]
	WORD $0xf1002339 // subs	x25, x25, #8
	WORD $0xad7f8f62 // ldp	q2, q3, [x27, #-16]
	WORD $0x9100837b // add	x27, x27, #32
	WORD $0x4e20cc41 // fmla	v1.4s, v2.4s, v0.4s
	WORD $0x4e20cc64 // fmla	v4.4s, v3.4s, v0.4s
	WORD $0xad3f9341 // stp	q1, q4, [x26, #-16]
	WORD $0x9100835a // add	x26, x26, #32
	BNE  LBB12_12
	WORD $0xeb03021f // cmp	x16, x3
	WORD $0xaa1003fb // mov	x27, x16
	BEQ  LBB12_8

LBB12_14:
	WORD $0xd37ef77a // lsl	x26, x27, #2
	WORD $0xcb1b007b // sub	x27, x3, x27
	WORD $0x8b1a02f9 // add	x25, x23, x26
	WORD $0x8b1a027a // add	x26, x19, x26

LBB12_15:
	WORD $0xbc747aa0 // ldr	s0, [x21, x20, lsl #2]
	WORD $0xbc404721 // ldr	s1, [x25], #4
	WORD $0xbd400342 // ldr	s2, [x26]
	WORD $0xf100077b // subs	x27, x27, #1
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbc004740 // str	s0, [x26], #4
	BNE  LBB12_15
	B    LBB12_8

LBB12_16:
	WORD $0x36000ca1 // tbz	w1, #0, .LBB12_34
	WORD $0x37000c80 // tbnz	w0, #0, .LBB12_34
	WORD $0xf100045f // cmp	x2, #1
	BLT  LBB12_101
	WORD $0x91000c8a // add	x10, x4, #3
	WORD $0xf100009f // cmp	x4, #0
	WORD $0x9a84b14a // csel	x10, x10, x4, lt
	WORD $0xf100047f // cmp	x3, #1
	BLT  LBB12_101
	WORD $0x9342fd4f // asr	x15, x10, #2
	WORD $0x927ef54a // and	x10, x10, #0xfffffffffffffffc
	WORD $0xcb0a008c // sub	x12, x4, x10
	WORD $0x710005ed // subs	w13, w15, #1
	WORD $0x92407d8a // and	x10, x12, #0xffffffff
	BLT  LBB12_62
	BNE  LBB12_74
	WORD $0x7100019f // cmp	w12, #0
	BLE  LBB12_97
	WORD $0x2f00e400 // movi	d0, #0000000000000000
	WORD $0x9240098c // and	x12, x12, #0x7
	WORD $0xd37ef4d0 // lsl	x16, x6, #2
	WORD $0xd37ef571 // lsl	x17, x11, #2
	WORD $0xaa1f03ed // mov	x13, xzr
	WORD $0xcb0c014e // sub	x14, x10, x12
	WORD $0x910080af // add	x15, x5, #32
	WORD $0x910080e0 // add	x0, x7, #32
	WORD $0x910040e1 // add	x1, x7, #16
	WORD $0x910040a4 // add	x4, x5, #16
	B    LBB12_25

LBB12_24:
	WORD $0x910005ad // add	x13, x13, #1
	WORD $0x8b1001ef // add	x15, x15, x16
	WORD $0x8b100084 // add	x4, x4, x16
	WORD $0xeb0201bf // cmp	x13, x2
	BEQ  LBB12_101

LBB12_25:
	WORD $0x9b067db4 // mul	x20, x13, x6
	WORD $0xaa1f03f3 // mov	x19, xzr
	WORD $0xaa0103f6 // mov	x22, x1
	WORD $0xaa0003f7 // mov	x23, x0
	WORD $0x9b097db5 // mul	x21, x13, x9
	WORD $0x8b1408b4 // add	x20, x5, x20, lsl #2
	WORD $0x8b150915 // add	x21, x8, x21, lsl #2
	B    LBB12_27

LBB12_26:
	WORD $0xbc337aa1 // str	s1, [x21, x19, lsl #2]
	WORD $0x91000673 // add	x19, x19, #1
	WORD $0x8b1102f7 // add	x23, x23, x17
	WORD $0xeb03027f // cmp	x19, x3
	WORD $0x8b1102d6 // add	x22, x22, x17
	BEQ  LBB12_24

LBB12_27:
	WORD $0x9b0b7e78 // mul	x24, x19, x11
	WORD $0x3dc00281 // ldr	q1, [x20]
	WORD $0xf100215f // cmp	x10, #8
	WORD $0xd37ef718 // lsl	x24, x24, #2
	WORD $0x3cf868e2 // ldr	q2, [x7, x24]
	WORD $0x6e22dc21 // fmul	v1.4s, v1.4s, v2.4s
	WORD $0x1e202822 // fadd	s2, s1, s0
	WORD $0x5e0c0423 // mov	s3, v1.s[1]
	WORD $0x1e222862 // fadd	s2, s3, s2
	WORD $0x5e140423 // mov	s3, v1.s[2]
	WORD $0x5e1c0421 // mov	s1, v1.s[3]
	WORD $0x1e222862 // fadd	s2, s3, s2
	WORD $0x1e222821 // fadd	s1, s1, s2
	BHS  LBB12_29
	WORD $0xaa1f03f8 // mov	x24, xzr
	B    LBB12_32

LBB12_29:
	WORD $0xaa1703f8 // mov	x24, x23
	WORD $0xaa0f03f9 // mov	x25, x15
	WORD $0xaa0e03fa // mov	x26, x14

LBB12_30:
	WORD $0xad7f9702 // ldp	q2, q5, [x24, #-16]
	WORD $0xf100235a // subs	x26, x26, #8
	WORD $0xad7f9323 // ldp	q3, q4, [x25, #-16]
	WORD $0x91008339 // add	x25, x25, #32
	WORD $0x91008318 // add	x24, x24, #32
	WORD $0x6e22dc62 // fmul	v2.4s, v3.4s, v2.4s
	WORD $0x5e0c0443 // mov	s3, v2.s[1]
	WORD $0x1e222821 // fadd	s1, s1, s2
	WORD $0x5e140446 // mov	s6, v2.s[2]
	WORD $0x5e1c0442 // mov	s2, v2.s[3]
	WORD $0x1e232821 // fadd	s1, s1, s3
	WORD $0x6e25dc83 // fmul	v3.4s, v4.4s, v5.4s
	WORD $0x1e262821 // fadd	s1, s1, s6
	WORD $0x5e140464 // mov	s4, v3.s[2]
	WORD $0x1e222821 // fadd	s1, s1, s2
	WORD $0x5e0c0462 // mov	s2, v3.s[1]
	WORD $0x1e232821 // fadd	s1, s1, s3
	WORD $0x1e222821 // fadd	s1, s1, s2
	WORD $0x5e1c0462 // mov	s2, v3.s[3]
	WORD $0x1e242821 // fadd	s1, s1, s4
	WORD $0x1e222821 // fadd	s1, s1, s2
	BNE  LBB12_30
	WORD $0xaa0e03f8 // mov	x24, x14
	WORD $0xb4fffa0c // cbz	x12, .LBB12_26

LBB12_32:
	WORD $0xd37ef71a // lsl	x26, x24, #2
	WORD $0xcb180158 // sub	x24, x10, x24
	WORD $0x8b1a02d9 // add	x25, x22, x26
	WORD $0x8b1a009a // add	x26, x4, x26

LBB12_33:
	WORD $0xbc404742 // ldr	s2, [x26], #4
	WORD $0xf1000718 // subs	x24, x24, #1
	WORD $0xbc404723 // ldr	s3, [x25], #4
	WORD $0x1f030441 // fmadd	s1, s2, s3, s1
	BNE  LBB12_33
	B    LBB12_26

LBB12_34:
	WORD $0xf100009f // cmp	x4, #0
	WORD $0xfa40c864 // ccmp	x3, #0, #4, gt
	WORD $0x1a9fd7ea // cset	w10, gt
	WORD $0x36000aa0 // tbz	w0, #0, .LBB12_48
	WORD $0x37000a81 // tbnz	w1, #0, .LBB12_48
	WORD $0xf100045f // cmp	x2, #1
	WORD $0x5200014a // eor	w10, w10, #0x1
	WORD $0x1a9fa54a // csinc	w10, w10, wzr, ge
	WORD $0x370030ea // tbnz	w10, #0, .LBB12_101
	WORD $0xd100048c // sub	x12, x4, #1
	WORD $0xd37ef529 // lsl	x9, x9, #2
	WORD $0xd37ef56e // lsl	x14, x11, #2
	WORD $0x9b067d8d // mul	x13, x12, x6
	WORD $0xd37df4cf // ubfx	x15, x6, #61, #1
	WORD $0xaa1f03ea // mov	x10, xzr
	WORD $0x910040e0 // add	x0, x7, #16
	WORD $0x91004101 // add	x1, x8, #16
	WORD $0xaa0803f3 // mov	x19, x8
	WORD $0x9b0b0d90 // madd	x16, x12, x11, x3
	WORD $0x8b03090c // add	x12, x8, x3, lsl #2
	WORD $0xd37df56b // ubfx	x11, x11, #61, #1
	WORD $0x8b0d08b1 // add	x17, x5, x13, lsl #2
	WORD $0x927df06d // and	x13, x3, #0xfffffffffffffff8
	WORD $0x8b1008f0 // add	x16, x7, x16, lsl #2
	WORD $0x91001231 // add	x17, x17, #4
	B    LBB12_39

LBB12_38:
	WORD $0x9100054a // add	x10, x10, #1
	WORD $0x8b090021 // add	x1, x1, x9
	WORD $0x8b090273 // add	x19, x19, x9
	WORD $0xeb02015f // cmp	x10, x2
	BEQ  LBB12_101

LBB12_39:
	WORD $0x9b0a7d35 // mul	x21, x9, x10
	WORD $0xd37ef556 // lsl	x22, x10, #2
	WORD $0xaa1f03f4 // mov	x20, xzr
	WORD $0x8b160238 // add	x24, x17, x22
	WORD $0x8b150117 // add	x23, x8, x21
	WORD $0x8b150199 // add	x25, x12, x21
	WORD $0x8b1600b5 // add	x21, x5, x22
	WORD $0xeb1802ff // cmp	x23, x24
	WORD $0xaa0003f8 // mov	x24, x0
	WORD $0xfa5932a2 // ccmp	x21, x25, #2, lo
	WORD $0x1a9f25f6 // csinc	w22, w15, wzr, hs
	WORD $0xeb1002ff // cmp	x23, x16
	WORD $0xfa473320 // ccmp	x25, x7, #0, lo
	WORD $0x1a9f9577 // csinc	w23, w11, wzr, ls
	WORD $0x2a1702d6 // orr	w22, w22, w23
	WORD $0xaa0703f7 // mov	x23, x7
	B    LBB12_41

LBB12_40:
	WORD $0x91000694 // add	x20, x20, #1
	WORD $0x8b0e0318 // add	x24, x24, x14
	WORD $0x8b0e02f7 // add	x23, x23, x14
	WORD $0xeb04029f // cmp	x20, x4
	BEQ  LBB12_38

LBB12_41:
	WORD $0x9b067e99 // mul	x25, x20, x6
	WORD $0xf100207f // cmp	x3, #8
	WORD $0x1a9f26da // csinc	w26, w22, wzr, hs
	WORD $0x3600007a // tbz	w26, #0, .LBB12_43
	WORD $0xaa1f03fc // mov	x28, xzr
	B    LBB12_46

LBB12_43:
	WORD $0x8b190aba // add	x26, x21, x25, lsl #2
	WORD $0xaa0103fb // mov	x27, x1
	WORD $0xaa1803fc // mov	x28, x24
	WORD $0x4d40cb40 // ld1r	{ v0.4s }, [x26]
	WORD $0xaa0d03fa // mov	x26, x13

LBB12_44:
	WORD $0xad7f9361 // ldp	q1, q4, [x27, #-16]
	WORD $0xf100235a // subs	x26, x26, #8
	WORD $0xad7f8f82 // ldp	q2, q3, [x28, #-16]
	WORD $0x9100839c // add	x28, x28, #32
	WORD $0x4e20cc41 // fmla	v1.4s, v2.4s, v0.4s
	WORD $0x4e20cc64 // fmla	v4.4s, v3.4s, v0.4s
	WORD $0xad3f9361 // stp	q1, q4, [x27, #-16]
	WORD $0x9100837b // add	x27, x27, #32
	BNE  LBB12_44
	WORD $0xeb0301bf // cmp	x13, x3
	WORD $0xaa0d03fc // mov	x28, x13
	BEQ  LBB12_40

LBB12_46:
	WORD $0xd37ef79b // lsl	x27, x28, #2
	WORD $0xcb1c007c // sub	x28, x3, x28
	WORD $0x8b1b02fa // add	x26, x23, x27
	WORD $0x8b1b027b // add	x27, x19, x27

LBB12_47:
	WORD $0xbc797aa0 // ldr	s0, [x21, x25, lsl #2]
	WORD $0xbc404741 // ldr	s1, [x26], #4
	WORD $0xbd400362 // ldr	s2, [x27]
	WORD $0xf100079c // subs	x28, x28, #1
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbc004760 // str	s0, [x27], #4
	BNE  LBB12_47
	B    LBB12_40

LBB12_48:
	WORD $0x0a01014a // and	w10, w10, w1
	WORD $0x7100055f // cmp	w10, #1
	BNE  LBB12_101
	WORD $0xf100045f // cmp	x2, #1
	BLT  LBB12_101
	WORD $0x36002640 // tbz	w0, #0, .LBB12_101
	WORD $0xd100048c // sub	x12, x4, #1
	WORD $0x8b030090 // add	x16, x4, x3
	WORD $0xf1001c7f // cmp	x3, #7
	WORD $0x9b067d8f // mul	x15, x12, x6
	WORD $0x8b1008f1 // add	x17, x7, x16, lsl #2
	WORD $0xfa418960 // ccmp	x11, #1, #0, hi
	WORD $0xd37ef529 // lsl	x9, x9, #2
	WORD $0x8b03090c // add	x12, x8, x3, lsl #2
	WORD $0xd37df4d0 // ubfx	x16, x6, #61, #1
	WORD $0x1a9f17e1 // cset	w1, eq
	WORD $0xaa1f03ea // mov	x10, xzr
	WORD $0x927df06d // and	x13, x3, #0xfffffffffffffff8
	WORD $0x910040ee // add	x14, x7, #16
	WORD $0x52000021 // eor	w1, w1, #0x1
	WORD $0xaa0803f3 // mov	x19, x8
	WORD $0x8b0f08a0 // add	x0, x5, x15, lsl #2
	WORD $0xd37ef56f // lsl	x15, x11, #2
	WORD $0xd100122b // sub	x11, x17, #4
	WORD $0x91001011 // add	x17, x0, #4
	WORD $0x91004100 // add	x0, x8, #16
	B    LBB12_53

LBB12_52:
	WORD $0x9100054a // add	x10, x10, #1
	WORD $0x8b090000 // add	x0, x0, x9
	WORD $0x8b090273 // add	x19, x19, x9
	WORD $0xeb02015f // cmp	x10, x2
	BEQ  LBB12_101

LBB12_53:
	WORD $0x9b0a7d35 // mul	x21, x9, x10
	WORD $0xd37ef556 // lsl	x22, x10, #2
	WORD $0xaa1f03f4 // mov	x20, xzr
	WORD $0x8b160238 // add	x24, x17, x22
	WORD $0x8b150117 // add	x23, x8, x21
	WORD $0x8b150199 // add	x25, x12, x21
	WORD $0x8b1600b5 // add	x21, x5, x22
	WORD $0xeb1802ff // cmp	x23, x24
	WORD $0xaa0e03f8 // mov	x24, x14
	WORD $0xfa5932a2 // ccmp	x21, x25, #2, lo
	WORD $0x1a9f2616 // csinc	w22, w16, wzr, hs
	WORD $0xeb0b02ff // cmp	x23, x11
	WORD $0xaa0703f7 // mov	x23, x7
	WORD $0xfa473320 // ccmp	x25, x7, #0, lo
	WORD $0x1a9f96d6 // csinc	w22, w22, wzr, ls
	WORD $0x2a160036 // orr	w22, w1, w22
	B    LBB12_55

LBB12_54:
	WORD $0x91000694 // add	x20, x20, #1
	WORD $0x91001318 // add	x24, x24, #4
	WORD $0x910012f7 // add	x23, x23, #4
	WORD $0xeb04029f // cmp	x20, x4
	BEQ  LBB12_52

LBB12_55:
	WORD $0x9b067e99 // mul	x25, x20, x6
	WORD $0x36000076 // tbz	w22, #0, .LBB12_57
	WORD $0xaa1f03fc // mov	x28, xzr
	B    LBB12_60

LBB12_57:
	WORD $0x8b190aba // add	x26, x21, x25, lsl #2
	WORD $0xaa0003fb // mov	x27, x0
	WORD $0xaa1803fc // mov	x28, x24
	WORD $0x4d40cb40 // ld1r	{ v0.4s }, [x26]
	WORD $0xaa0d03fa // mov	x26, x13

LBB12_58:
	WORD $0xad7f9361 // ldp	q1, q4, [x27, #-16]
	WORD $0xf100235a // subs	x26, x26, #8
	WORD $0xad7f8f82 // ldp	q2, q3, [x28, #-16]
	WORD $0x9100839c // add	x28, x28, #32
	WORD $0x4e20cc41 // fmla	v1.4s, v2.4s, v0.4s
	WORD $0x4e20cc64 // fmla	v4.4s, v3.4s, v0.4s
	WORD $0xad3f9361 // stp	q1, q4, [x27, #-16]
	WORD $0x9100837b // add	x27, x27, #32
	BNE  LBB12_58
	WORD $0xeb0301bf // cmp	x13, x3
	WORD $0xaa0d03fc // mov	x28, x13
	BEQ  LBB12_54

LBB12_60:
	WORD $0x9b1c5dfa // madd	x26, x15, x28, x23
	WORD $0x8b1c0a7b // add	x27, x19, x28, lsl #2
	WORD $0xcb1c007c // sub	x28, x3, x28

LBB12_61:
	WORD $0xbc797aa0 // ldr	s0, [x21, x25, lsl #2]
	WORD $0xbd400341 // ldr	s1, [x26]
	WORD $0xf100079c // subs	x28, x28, #1
	WORD $0xbd400362 // ldr	s2, [x27]
	WORD $0x8b0f035a // add	x26, x26, x15
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbc004760 // str	s0, [x27], #4
	BNE  LBB12_61
	B    LBB12_54

LBB12_62:
	WORD $0x7100019f // cmp	w12, #0
	BLE  LBB12_88
	WORD $0x9240098c // and	x12, x12, #0x7
	WORD $0xd37ef4ce // lsl	x14, x6, #2
	WORD $0xd37ef56b // lsl	x11, x11, #2
	WORD $0xaa1f03ed // mov	x13, xzr
	WORD $0xcb0c014f // sub	x15, x10, x12
	WORD $0x910040b0 // add	x16, x5, #16
	WORD $0x910040f1 // add	x17, x7, #16
	B    LBB12_65

LBB12_64:
	WORD $0x910005ad // add	x13, x13, #1
	WORD $0x8b0e0210 // add	x16, x16, x14
	WORD $0x8b0e00a5 // add	x5, x5, x14
	WORD $0xeb0201bf // cmp	x13, x2
	BEQ  LBB12_101

LBB12_65:
	WORD $0x9b097da1 // mul	x1, x13, x9
	WORD $0xaa1f03e0 // mov	x0, xzr
	WORD $0xaa0703e4 // mov	x4, x7
	WORD $0xaa1103e6 // mov	x6, x17
	WORD $0x8b010901 // add	x1, x8, x1, lsl #2
	B    LBB12_67

LBB12_66:
	WORD $0xbc207820 // str	s0, [x1, x0, lsl #2]
	WORD $0x91000400 // add	x0, x0, #1
	WORD $0x8b0b00c6 // add	x6, x6, x11
	WORD $0xeb03001f // cmp	x0, x3
	WORD $0x8b0b0084 // add	x4, x4, x11
	BEQ  LBB12_64

LBB12_67:
	WORD $0x2f00e400 // movi	d0, #0000000000000000
	WORD $0xf100215f // cmp	x10, #8
	BHS  LBB12_69
	WORD $0xaa1f03f3 // mov	x19, xzr
	B    LBB12_72

LBB12_69:
	WORD $0xaa0f03f3 // mov	x19, x15
	WORD $0xaa0603f4 // mov	x20, x6
	WORD $0xaa1003f5 // mov	x21, x16

LBB12_70:
	WORD $0xad7f9281 // ldp	q1, q4, [x20, #-16]
	WORD $0xf1002273 // subs	x19, x19, #8
	WORD $0xad7f8ea2 // ldp	q2, q3, [x21, #-16]
	WORD $0x910082b5 // add	x21, x21, #32
	WORD $0x91008294 // add	x20, x20, #32
	WORD $0x6e21dc41 // fmul	v1.4s, v2.4s, v1.4s
	WORD $0x5e0c0422 // mov	s2, v1.s[1]
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x5e140425 // mov	s5, v1.s[2]
	WORD $0x5e1c0421 // mov	s1, v1.s[3]
	WORD $0x1e222800 // fadd	s0, s0, s2
	WORD $0x6e24dc62 // fmul	v2.4s, v3.4s, v4.4s
	WORD $0x1e252800 // fadd	s0, s0, s5
	WORD $0x5e140443 // mov	s3, v2.s[2]
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x5e0c0441 // mov	s1, v2.s[1]
	WORD $0x1e222800 // fadd	s0, s0, s2
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x5e1c0441 // mov	s1, v2.s[3]
	WORD $0x1e232800 // fadd	s0, s0, s3
	WORD $0x1e212800 // fadd	s0, s0, s1
	BNE  LBB12_70
	WORD $0xaa0f03f3 // mov	x19, x15
	WORD $0xb4fffb6c // cbz	x12, .LBB12_66

LBB12_72:
	WORD $0xd37ef675 // lsl	x21, x19, #2
	WORD $0xcb130153 // sub	x19, x10, x19
	WORD $0x8b150094 // add	x20, x4, x21
	WORD $0x8b1500b5 // add	x21, x5, x21

LBB12_73:
	WORD $0xbc4046a1 // ldr	s1, [x21], #4
	WORD $0xf1000673 // subs	x19, x19, #1
	WORD $0xbc404682 // ldr	s2, [x20], #4
	WORD $0x1f020020 // fmadd	s0, s1, s2, s0
	BNE  LBB12_73
	B    LBB12_66

LBB12_74:
	WORD $0xb27b7bf0 // mov	x16, #68719476704
	WORD $0x2f00e400 // movi	d0, #0000000000000000
	WORD $0xd37ef571 // lsl	x17, x11, #2
	WORD $0x8b0f1210 // add	x16, x16, x15, lsl #4
	WORD $0x9240098f // and	x15, x12, #0x7
	WORD $0xaa1f03ee // mov	x14, xzr
	WORD $0xcb0f0140 // sub	x0, x10, x15
	WORD $0x927c7e01 // and	x1, x16, #0xffffffff0
	WORD $0xd37ef4d0 // lsl	x16, x6, #2
	WORD $0x9100c024 // add	x4, x1, #48
	WORD $0x91008034 // add	x20, x1, #32
	WORD $0x8b0400a1 // add	x1, x5, x4
	WORD $0x8b0400e4 // add	x4, x7, x4
	WORD $0x8b1400f3 // add	x19, x7, x20
	WORD $0x8b1400b4 // add	x20, x5, x20
	B    LBB12_76

LBB12_75:
	WORD $0x910005ce // add	x14, x14, #1
	WORD $0x8b100021 // add	x1, x1, x16
	WORD $0x8b100294 // add	x20, x20, x16
	WORD $0xeb0201df // cmp	x14, x2
	BEQ  LBB12_101

LBB12_76:
	WORD $0x9b067dd6 // mul	x22, x14, x6
	WORD $0xaa1f03f5 // mov	x21, xzr
	WORD $0xaa1303f9 // mov	x25, x19
	WORD $0xaa0403fa // mov	x26, x4
	WORD $0x9b097dd7 // mul	x23, x14, x9
	WORD $0x8b1608b6 // add	x22, x5, x22, lsl #2
	WORD $0x8b170917 // add	x23, x8, x23, lsl #2
	WORD $0x910042d8 // add	x24, x22, #16
	B    LBB12_78

LBB12_77:
	WORD $0xbc357ae1 // str	s1, [x23, x21, lsl #2]
	WORD $0x910006b5 // add	x21, x21, #1
	WORD $0x8b11035a // add	x26, x26, x17
	WORD $0xeb0302bf // cmp	x21, x3
	WORD $0x8b110339 // add	x25, x25, x17
	BEQ  LBB12_75

LBB12_78:
	WORD $0x9b0b7ebb // mul	x27, x21, x11
	WORD $0x3dc002c1 // ldr	q1, [x22]
	WORD $0x2a0d03fc // mov	w28, w13
	WORD $0xaa1803fe // mov	x30, x24
	WORD $0x8b1b08fb // add	x27, x7, x27, lsl #2
	WORD $0x3cc10762 // ldr	q2, [x27], #16
	WORD $0x6e22dc21 // fmul	v1.4s, v1.4s, v2.4s

LBB12_79:
	WORD $0x3cc107c2 // ldr	q2, [x30], #16
	WORD $0x7100079c // subs	w28, w28, #1
	WORD $0x3cc10763 // ldr	q3, [x27], #16
	WORD $0x4e22cc61 // fmla	v1.4s, v3.4s, v2.4s
	BNE  LBB12_79
	WORD $0x1e202822 // fadd	s2, s1, s0
	WORD $0x5e0c0423 // mov	s3, v1.s[1]
	WORD $0x7100059f // cmp	w12, #1
	WORD $0x1e222862 // fadd	s2, s3, s2
	WORD $0x5e140423 // mov	s3, v1.s[2]
	WORD $0x5e1c0421 // mov	s1, v1.s[3]
	WORD $0x1e222862 // fadd	s2, s3, s2
	WORD $0x1e222821 // fadd	s1, s1, s2
	BLT  LBB12_77
	WORD $0xf100215f // cmp	x10, #8
	BHS  LBB12_83
	WORD $0xaa1f03fb // mov	x27, xzr
	B    LBB12_86

LBB12_83:
	WORD $0xaa1a03fb // mov	x27, x26
	WORD $0xaa0103fc // mov	x28, x1
	WORD $0xaa0003fe // mov	x30, x0

LBB12_84:
	WORD $0xad7f9762 // ldp	q2, q5, [x27, #-16]
	WORD $0xf10023de // subs	x30, x30, #8
	WORD $0xad7f9383 // ldp	q3, q4, [x28, #-16]
	WORD $0x9100839c // add	x28, x28, #32
	WORD $0x9100837b // add	x27, x27, #32
	WORD $0x6e22dc62 // fmul	v2.4s, v3.4s, v2.4s
	WORD $0x5e0c0443 // mov	s3, v2.s[1]
	WORD $0x1e222821 // fadd	s1, s1, s2
	WORD $0x5e140446 // mov	s6, v2.s[2]
	WORD $0x5e1c0442 // mov	s2, v2.s[3]
	WORD $0x1e232821 // fadd	s1, s1, s3
	WORD $0x6e25dc83 // fmul	v3.4s, v4.4s, v5.4s
	WORD $0x1e262821 // fadd	s1, s1, s6
	WORD $0x5e140464 // mov	s4, v3.s[2]
	WORD $0x1e222821 // fadd	s1, s1, s2
	WORD $0x5e0c0462 // mov	s2, v3.s[1]
	WORD $0x1e232821 // fadd	s1, s1, s3
	WORD $0x1e222821 // fadd	s1, s1, s2
	WORD $0x5e1c0462 // mov	s2, v3.s[3]
	WORD $0x1e242821 // fadd	s1, s1, s4
	WORD $0x1e222821 // fadd	s1, s1, s2
	BNE  LBB12_84
	WORD $0xaa0003fb // mov	x27, x0
	WORD $0xb4fff8ef // cbz	x15, .LBB12_77

LBB12_86:
	WORD $0xd37ef77e // lsl	x30, x27, #2
	WORD $0xcb1b015b // sub	x27, x10, x27
	WORD $0x8b1e033c // add	x28, x25, x30
	WORD $0x8b1e029e // add	x30, x20, x30

LBB12_87:
	WORD $0xbc4047c2 // ldr	s2, [x30], #4
	WORD $0xf100077b // subs	x27, x27, #1
	WORD $0xbc404783 // ldr	s3, [x28], #4
	WORD $0x1f030441 // fmadd	s1, s2, s3, s1
	BNE  LBB12_87
	B    LBB12_77

LBB12_88:
	WORD $0x6f00e400 // movi	v0.2d, #0000000000000000
	WORD $0xd37ef529 // lsl	x9, x9, #2
	WORD $0xaa1f03ea // mov	x10, xzr
	WORD $0x927dec6b // and	x11, x3, #0x7ffffffffffffff8
	WORD $0x9100410c // add	x12, x8, #16
	B    LBB12_90

LBB12_89:
	WORD $0x9100054a // add	x10, x10, #1
	WORD $0x8b09018c // add	x12, x12, x9
	WORD $0x8b090108 // add	x8, x8, x9
	WORD $0xeb02015f // cmp	x10, x2
	BEQ  LBB12_101

LBB12_90:
	WORD $0xf100207f // cmp	x3, #8
	BHS  LBB12_92
	WORD $0xaa1f03ee // mov	x14, xzr
	B    LBB12_95

LBB12_92:
	WORD $0xaa0b03ed // mov	x13, x11
	WORD $0xaa0c03ee // mov	x14, x12

LBB12_93:
	WORD $0xad3f81c0 // stp	q0, q0, [x14, #-16]
	WORD $0xf10021ad // subs	x13, x13, #8
	WORD $0x910081ce // add	x14, x14, #32
	BNE  LBB12_93
	WORD $0xeb03017f // cmp	x11, x3
	WORD $0xaa0b03ee // mov	x14, x11
	BEQ  LBB12_89

LBB12_95:
	WORD $0x8b0e090d // add	x13, x8, x14, lsl #2
	WORD $0xcb0e006e // sub	x14, x3, x14

LBB12_96:
	WORD $0xf10005ce // subs	x14, x14, #1
	WORD $0xb80045bf // str	wzr, [x13], #4
	BNE  LBB12_96
	B    LBB12_89

LBB12_97:
	WORD $0x2f00e400 // movi	d0, #0000000000000000
	WORD $0xd37ef56a // lsl	x10, x11, #2
	WORD $0xd37ef529 // lsl	x9, x9, #2
	WORD $0xaa1f03eb // mov	x11, xzr

LBB12_98:
	WORD $0x9b067d6c // mul	x12, x11, x6
	WORD $0xaa0303ed // mov	x13, x3
	WORD $0xaa0803ee // mov	x14, x8
	WORD $0xaa0703ef // mov	x15, x7
	WORD $0x8b0c08ac // add	x12, x5, x12, lsl #2

LBB12_99:
	WORD $0x3dc00181 // ldr	q1, [x12]
	WORD $0x3dc001e2 // ldr	q2, [x15]
	WORD $0xf10005ad // subs	x13, x13, #1
	WORD $0x8b0a01ef // add	x15, x15, x10
	WORD $0x6e22dc21 // fmul	v1.4s, v1.4s, v2.4s
	WORD $0x1e202822 // fadd	s2, s1, s0
	WORD $0x5e0c0423 // mov	s3, v1.s[1]
	WORD $0x1e222862 // fadd	s2, s3, s2
	WORD $0x5e140423 // mov	s3, v1.s[2]
	WORD $0x5e1c0421 // mov	s1, v1.s[3]
	WORD $0x1e222862 // fadd	s2, s3, s2
	WORD $0x1e222821 // fadd	s1, s1, s2
	WORD $0xbc0045c1 // str	s1, [x14], #4
	BNE  LBB12_99
	WORD $0x9100056b // add	x11, x11, #1
	WORD $0x8b090108 // add	x8, x8, x9
	WORD $0xeb02017f // cmp	x11, x2
	BNE  LBB12_98

LBB12_101:
	WORD $0xa9454ff4 // ldp	x20, x19, [sp, #80]
	WORD $0xa94457f6 // ldp	x22, x21, [sp, #64]
	WORD $0xa9435ff8 // ldp	x24, x23, [sp, #48]
	WORD $0xa94267fa // ldp	x26, x25, [sp, #32]
	WORD $0xa9416ffc // ldp	x28, x27, [sp, #16]
	WORD $0xa8c67bfd // ldp	x29, x30, [sp], #96
	RET
