//go:build !noasm && riscv64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -march=rv64imafdv_zvfhmin -isystem /usr/lib/llvm-21/lib/clang/21/include -O3
// source: src/floats_rvv.c

TEXT ·vfrom_float32(SB), $0-24
	MOV  a+0(FP), A0
	MOV  dst+8(FP), A1
	MOV  n+16(FP), A2
	BLEZ A2, LBB0_2

LBB0_1:
	WORD $0x0c8676d7 // vsetvli	a3, a2, e16, m1, ta, ma
	WORD $0x02056407 // vle32.v	v8, (a0)
	WORD $0x00269713 // slli	a4, a3, 2
	WORD $0x00e50533 // add	a0, a0, a4
	WORD $0x00169713 // slli	a4, a3, 1
	WORD $0x40d60633 // sub	a2, a2, a3
	WORD $0x4a8a1557 // vfncvt.f.f.w	v10, v8
	WORD $0x0205d527 // vse16.v	v10, (a1)
	WORD $0x00e585b3 // add	a1, a1, a4
	BGTZ A2, LBB0_1

LBB0_2:
	RET

TEXT ·vto_float32(SB), $0-24
	MOV  a+0(FP), A0
	MOV  dst+8(FP), A1
	MOV  n+16(FP), A2
	BLEZ A2, LBB1_2

LBB1_1:
	WORD $0x0c8676d7 // vsetvli	a3, a2, e16, m1, ta, ma
	WORD $0x02055507 // vle16.v	v10, (a0)
	WORD $0x00169713 // slli	a4, a3, 1
	WORD $0x00e50533 // add	a0, a0, a4
	WORD $0x00269713 // slli	a4, a3, 2
	WORD $0x40d60633 // sub	a2, a2, a3
	WORD $0x4aa61457 // vfwcvt.f.f.v	v8, v10
	WORD $0x0205e427 // vse32.v	v8, (a1)
	WORD $0x00e585b3 // add	a1, a1, a4
	BGTZ A2, LBB1_1

LBB1_2:
	RET

TEXT ·vmul_const_add_to(SB), $0-40
	MOV  a+0(FP), A0
	MOV  b+8(FP), A1
	MOV  c+16(FP), A2
	MOV  dst+24(FP), A3
	MOV  n+32(FP), A4
	BLEZ A4, LBB2_7
	WORD $0xc22028f3    // csrr	a7, vlenb
	WORD $0x0018d293    // srli	t0, a7, 1
	WORD $0x01800793    // li	a5, 24
	WORD $0x00028813    // mv	a6, t0
	BLTU A5, T0, LBB2_3
	WORD $0x01800813    // li	a6, 24

LBB2_3:
	WORD $0x00271793    // slli	a5, a4, 2
	BGEU A4, A6, LBB2_8
	WORD $0x00000813    // li	a6, 0

LBB2_5:
	WORD $0x00281813 // slli	a6, a6, 2
	WORD $0x01068733 // add	a4, a3, a6
	WORD $0x01060633 // add	a2, a2, a6
	WORD $0x01050533 // add	a0, a0, a6
	WORD $0x00f686b3 // add	a3, a3, a5

LBB2_6:
	WORD $0x00052787    // flw	fa5, 0(a0)
	WORD $0x0005a707    // flw	fa4, 0(a1)
	WORD $0x00062687    // flw	fa3, 0(a2)
	WORD $0x68e7f7c3    // fmadd.s	fa5, fa5, fa4, fa3
	WORD $0x00f72027    // fsw	fa5, 0(a4)
	WORD $0x00470713    // addi	a4, a4, 4
	WORD $0x00460613    // addi	a2, a2, 4
	WORD $0x00450513    // addi	a0, a0, 4
	BNE  A4, A3, LBB2_6

LBB2_7:
	RET

LBB2_8:
	WORD $0x00f68333 // add	t1, a3, a5
	WORD $0x00f50833 // add	a6, a0, a5
	WORD $0x0106b833 // sltu	a6, a3, a6
	WORD $0x006533b3 // sltu	t2, a0, t1
	WORD $0x007873b3 // and	t2, a6, t2
	WORD $0x00000813 // li	a6, 0
	BNEZ T2, LBB2_5
	WORD $0x00458393 // addi	t2, a1, 4
	WORD $0x0076b3b3 // sltu	t2, a3, t2
	WORD $0x0065be33 // sltu	t3, a1, t1
	WORD $0x01c3f3b3 // and	t2, t2, t3
	BNEZ T2, LBB2_5
	WORD $0x00f603b3 // add	t2, a2, a5
	WORD $0x0076b3b3 // sltu	t2, a3, t2
	WORD $0x00663333 // sltu	t1, a2, t1
	WORD $0x0063f333 // and	t1, t2, t1
	BNEZ T1, LBB2_5
	WORD $0x40500833 // neg	a6, t0
	WORD $0x01077833 // and	a6, a4, a6
	WORD $0x40580333 // sub	t1, a6, t0
	WORD $0x025352b3 // divu	t0, t1, t0
	WORD $0x0038d313 // srli	t1, a7, 3
	WORD $0x0005a787 // flw	fa5, 0(a1)
	WORD $0x00431893 // slli	a7, t1, 4
	WORD $0x00429293 // slli	t0, t0, 4
	WORD $0x01028293 // addi	t0, t0, 16
	WORD $0x026282b3 // mul	t0, t0, t1
	WORD $0x005682b3 // add	t0, a3, t0
	WORD $0x00050313 // mv	t1, a0
	WORD $0x00060393 // mv	t2, a2
	WORD $0x00068e13 // mv	t3, a3
	WORD $0x0d107ed7 // vsetvli	t4, zero, e32, m2, ta, ma

LBB2_12:
	WORD $0x22836407     // vl2re32.v	v8, (t1)
	WORD $0x2283e507     // vl2re32.v	v10, (t2)
	WORD $0xb287d557     // vfmacc.vf	v10, fa5, v8
	WORD $0x228e0527     // vs2r.v	v10, (t3)
	WORD $0x011e0e33     // add	t3, t3, a7
	WORD $0x011383b3     // add	t2, t2, a7
	WORD $0x01130333     // add	t1, t1, a7
	BNE  T3, T0, LBB2_12
	BNE  A4, A6, LBB2_5
	JMP  LBB2_7

TEXT ·vmul_const_add(SB), $0-32
	MOV  a+0(FP), A0
	MOV  b+8(FP), A1
	MOV  c+16(FP), A2
	MOV  n+24(FP), A3
	BLEZ A3, LBB3_7
	WORD $0xc2202873    // csrr	a6, vlenb
	WORD $0x00185893    // srli	a7, a6, 1
	WORD $0x01000713    // li	a4, 16
	WORD $0x00088793    // mv	a5, a7
	BLTU A4, A7, LBB3_3
	WORD $0x01000793    // li	a5, 16

LBB3_3:
	WORD $0x00269713    // slli	a4, a3, 2
	BGEU A3, A5, LBB3_8
	WORD $0x00000793    // li	a5, 0

LBB3_5:
	WORD $0x00279793 // slli	a5, a5, 2
	WORD $0x00f606b3 // add	a3, a2, a5
	WORD $0x00f50533 // add	a0, a0, a5
	WORD $0x00e60633 // add	a2, a2, a4

LBB3_6:
	WORD $0x00052787    // flw	fa5, 0(a0)
	WORD $0x0005a707    // flw	fa4, 0(a1)
	WORD $0x0006a687    // flw	fa3, 0(a3)
	WORD $0x68e7f7c3    // fmadd.s	fa5, fa5, fa4, fa3
	WORD $0x00f6a027    // fsw	fa5, 0(a3)
	WORD $0x00468693    // addi	a3, a3, 4
	WORD $0x00450513    // addi	a0, a0, 4
	BNE  A3, A2, LBB3_6

LBB3_7:
	RET

LBB3_8:
	WORD $0x00e602b3 // add	t0, a2, a4
	WORD $0x00e507b3 // add	a5, a0, a4
	WORD $0x00f637b3 // sltu	a5, a2, a5
	WORD $0x00553333 // sltu	t1, a0, t0
	WORD $0x0067f333 // and	t1, a5, t1
	WORD $0x00000793 // li	a5, 0
	BNEZ T1, LBB3_5
	WORD $0x00458313 // addi	t1, a1, 4
	WORD $0x00663333 // sltu	t1, a2, t1
	WORD $0x0055b2b3 // sltu	t0, a1, t0
	WORD $0x005372b3 // and	t0, t1, t0
	BNEZ T0, LBB3_5
	WORD $0x411007b3 // neg	a5, a7
	WORD $0x00f6f7b3 // and	a5, a3, a5
	WORD $0x411782b3 // sub	t0, a5, a7
	WORD $0x0312d8b3 // divu	a7, t0, a7
	WORD $0x00385293 // srli	t0, a6, 3
	WORD $0x0005a787 // flw	fa5, 0(a1)
	WORD $0x00429813 // slli	a6, t0, 4
	WORD $0x00489893 // slli	a7, a7, 4
	WORD $0x01088893 // addi	a7, a7, 16
	WORD $0x025888b3 // mul	a7, a7, t0
	WORD $0x011608b3 // add	a7, a2, a7
	WORD $0x00050293 // mv	t0, a0
	WORD $0x00060313 // mv	t1, a2
	WORD $0x0d1073d7 // vsetvli	t2, zero, e32, m2, ta, ma

LBB3_11:
	WORD $0x2282e407     // vl2re32.v	v8, (t0)
	WORD $0x22836507     // vl2re32.v	v10, (t1)
	WORD $0xb287d557     // vfmacc.vf	v10, fa5, v8
	WORD $0x22830527     // vs2r.v	v10, (t1)
	WORD $0x01030333     // add	t1, t1, a6
	WORD $0x010282b3     // add	t0, t0, a6
	BNE  T1, A7, LBB3_11
	BNE  A3, A5, LBB3_5
	JMP  LBB3_7

TEXT ·vmul_const_to(SB), $0-32
	MOV  a+0(FP), A0
	MOV  b+8(FP), A1
	MOV  c+16(FP), A2
	MOV  n+24(FP), A3
	BLEZ A3, LBB4_7
	WORD $0xc2202873    // csrr	a6, vlenb
	WORD $0x00185893    // srli	a7, a6, 1
	WORD $0x01000713    // li	a4, 16
	WORD $0x00088793    // mv	a5, a7
	BLTU A4, A7, LBB4_3
	WORD $0x01000793    // li	a5, 16

LBB4_3:
	WORD $0x00269713    // slli	a4, a3, 2
	BGEU A3, A5, LBB4_8
	WORD $0x00000793    // li	a5, 0

LBB4_5:
	WORD $0x00279793 // slli	a5, a5, 2
	WORD $0x00f606b3 // add	a3, a2, a5
	WORD $0x00f50533 // add	a0, a0, a5
	WORD $0x00e60633 // add	a2, a2, a4

LBB4_6:
	WORD $0x00052787    // flw	fa5, 0(a0)
	WORD $0x0005a707    // flw	fa4, 0(a1)
	WORD $0x10e7f7d3    // fmul.s	fa5, fa5, fa4
	WORD $0x00f6a027    // fsw	fa5, 0(a3)
	WORD $0x00468693    // addi	a3, a3, 4
	WORD $0x00450513    // addi	a0, a0, 4
	BNE  A3, A2, LBB4_6

LBB4_7:
	RET

LBB4_8:
	WORD $0x00e602b3 // add	t0, a2, a4
	WORD $0x00e507b3 // add	a5, a0, a4
	WORD $0x00f637b3 // sltu	a5, a2, a5
	WORD $0x00553333 // sltu	t1, a0, t0
	WORD $0x0067f333 // and	t1, a5, t1
	WORD $0x00000793 // li	a5, 0
	BNEZ T1, LBB4_5
	WORD $0x00458313 // addi	t1, a1, 4
	WORD $0x00663333 // sltu	t1, a2, t1
	WORD $0x0055b2b3 // sltu	t0, a1, t0
	WORD $0x005372b3 // and	t0, t1, t0
	BNEZ T0, LBB4_5
	WORD $0x411007b3 // neg	a5, a7
	WORD $0x00f6f7b3 // and	a5, a3, a5
	WORD $0x411782b3 // sub	t0, a5, a7
	WORD $0x0312d8b3 // divu	a7, t0, a7
	WORD $0x00385293 // srli	t0, a6, 3
	WORD $0x0005a787 // flw	fa5, 0(a1)
	WORD $0x00429813 // slli	a6, t0, 4
	WORD $0x00489893 // slli	a7, a7, 4
	WORD $0x01088893 // addi	a7, a7, 16
	WORD $0x025888b3 // mul	a7, a7, t0
	WORD $0x011608b3 // add	a7, a2, a7
	WORD $0x00050293 // mv	t0, a0
	WORD $0x00060313 // mv	t1, a2
	WORD $0x0d1073d7 // vsetvli	t2, zero, e32, m2, ta, ma

LBB4_11:
	WORD $0x2282e407     // vl2re32.v	v8, (t0)
	WORD $0x9287d457     // vfmul.vf	v8, v8, fa5
	WORD $0x22830427     // vs2r.v	v8, (t1)
	WORD $0x01030333     // add	t1, t1, a6
	WORD $0x010282b3     // add	t0, t0, a6
	BNE  T1, A7, LBB4_11
	BNE  A3, A5, LBB4_5
	JMP  LBB4_7

TEXT ·vmul_const(SB), $0-24
	MOV  a+0(FP), A0
	MOV  b+8(FP), A1
	MOV  n+16(FP), A2
	BLEZ A2, LBB5_9
	WORD $0xc22027f3    // csrr	a5, vlenb
	WORD $0x0017d813    // srli	a6, a5, 1
	WORD $0x00800693    // li	a3, 8
	WORD $0x00080713    // mv	a4, a6
	BLTU A3, A6, LBB5_3
	WORD $0x00800713    // li	a4, 8

LBB5_3:
	WORD $0x00261693     // slli	a3, a2, 2
	BLTU A2, A4, LBB5_6
	WORD $0x00458713     // addi	a4, a1, 4
	BGEU A0, A4, LBB5_10
	WORD $0x00d50733     // add	a4, a0, a3
	BGEU A1, A4, LBB5_10

LBB5_6:
	WORD $0x00000713 // li	a4, 0

LBB5_7:
	WORD $0x00271613 // slli	a2, a4, 2
	WORD $0x00c50633 // add	a2, a0, a2
	WORD $0x00d50533 // add	a0, a0, a3

LBB5_8:
	WORD $0x0005a787    // flw	fa5, 0(a1)
	WORD $0x00062707    // flw	fa4, 0(a2)
	WORD $0x10e7f7d3    // fmul.s	fa5, fa5, fa4
	WORD $0x00f62027    // fsw	fa5, 0(a2)
	WORD $0x00460613    // addi	a2, a2, 4
	BNE  A2, A0, LBB5_8

LBB5_9:
	RET

LBB5_10:
	WORD $0x41000733 // neg	a4, a6
	WORD $0x00e67733 // and	a4, a2, a4
	WORD $0x410708b3 // sub	a7, a4, a6
	WORD $0x0308d833 // divu	a6, a7, a6
	WORD $0x0037d893 // srli	a7, a5, 3
	WORD $0x0005a787 // flw	fa5, 0(a1)
	WORD $0x00489793 // slli	a5, a7, 4
	WORD $0x00481813 // slli	a6, a6, 4
	WORD $0x01080813 // addi	a6, a6, 16
	WORD $0x03180833 // mul	a6, a6, a7
	WORD $0x01050833 // add	a6, a0, a6
	WORD $0x00050893 // mv	a7, a0
	WORD $0x0d1072d7 // vsetvli	t0, zero, e32, m2, ta, ma

LBB5_11:
	WORD $0x2288e407     // vl2re32.v	v8, (a7)
	WORD $0x9287d457     // vfmul.vf	v8, v8, fa5
	WORD $0x22888427     // vs2r.v	v8, (a7)
	WORD $0x00f888b3     // add	a7, a7, a5
	BNE  A7, A6, LBB5_11
	BEQ  A2, A4, LBB5_9
	JMP  LBB5_7

TEXT ·vadd_const(SB), $0-24
	MOV  a+0(FP), A0
	MOV  b+8(FP), A1
	MOV  n+16(FP), A2
	BLEZ A2, LBB6_9
	WORD $0xc22027f3    // csrr	a5, vlenb
	WORD $0x0017d813    // srli	a6, a5, 1
	WORD $0x00800693    // li	a3, 8
	WORD $0x00080713    // mv	a4, a6
	BLTU A3, A6, LBB6_3
	WORD $0x00800713    // li	a4, 8

LBB6_3:
	WORD $0x00261693     // slli	a3, a2, 2
	BLTU A2, A4, LBB6_6
	WORD $0x00458713     // addi	a4, a1, 4
	BGEU A0, A4, LBB6_10
	WORD $0x00d50733     // add	a4, a0, a3
	BGEU A1, A4, LBB6_10

LBB6_6:
	WORD $0x00000713 // li	a4, 0

LBB6_7:
	WORD $0x00271613 // slli	a2, a4, 2
	WORD $0x00c50633 // add	a2, a0, a2
	WORD $0x00d50533 // add	a0, a0, a3

LBB6_8:
	WORD $0x0005a787    // flw	fa5, 0(a1)
	WORD $0x00062707    // flw	fa4, 0(a2)
	WORD $0x00e7f7d3    // fadd.s	fa5, fa5, fa4
	WORD $0x00f62027    // fsw	fa5, 0(a2)
	WORD $0x00460613    // addi	a2, a2, 4
	BNE  A2, A0, LBB6_8

LBB6_9:
	RET

LBB6_10:
	WORD $0x41000733 // neg	a4, a6
	WORD $0x00e67733 // and	a4, a2, a4
	WORD $0x410708b3 // sub	a7, a4, a6
	WORD $0x0308d833 // divu	a6, a7, a6
	WORD $0x0037d893 // srli	a7, a5, 3
	WORD $0x0005a787 // flw	fa5, 0(a1)
	WORD $0x00489793 // slli	a5, a7, 4
	WORD $0x00481813 // slli	a6, a6, 4
	WORD $0x01080813 // addi	a6, a6, 16
	WORD $0x03180833 // mul	a6, a6, a7
	WORD $0x01050833 // add	a6, a0, a6
	WORD $0x00050893 // mv	a7, a0
	WORD $0x0d1072d7 // vsetvli	t0, zero, e32, m2, ta, ma

LBB6_11:
	WORD $0x2288e407     // vl2re32.v	v8, (a7)
	WORD $0x0287d457     // vfadd.vf	v8, v8, fa5
	WORD $0x22888427     // vs2r.v	v8, (a7)
	WORD $0x00f888b3     // add	a7, a7, a5
	BNE  A7, A6, LBB6_11
	BEQ  A2, A4, LBB6_9
	JMP  LBB6_7

TEXT ·vsub_to(SB), $0-32
	MOV  a+0(FP), A0
	MOV  b+8(FP), A1
	MOV  c+16(FP), A2
	MOV  n+24(FP), A3
	BLEZ A3, LBB7_7
	WORD $0xc2202873    // csrr	a6, vlenb
	WORD $0x00185893    // srli	a7, a6, 1
	WORD $0x01000793    // li	a5, 16
	WORD $0x00088713    // mv	a4, a7
	BLTU A5, A7, LBB7_3
	WORD $0x01000713    // li	a4, 16

LBB7_3:
	BGEU A3, A4, LBB7_8
	WORD $0x00000713    // li	a4, 0

LBB7_5:
	WORD $0x00271713 // slli	a4, a4, 2
	WORD $0x00269793 // slli	a5, a3, 2
	WORD $0x00e606b3 // add	a3, a2, a4
	WORD $0x00e585b3 // add	a1, a1, a4
	WORD $0x00e50533 // add	a0, a0, a4
	WORD $0x00f60633 // add	a2, a2, a5

LBB7_6:
	WORD $0x00052787    // flw	fa5, 0(a0)
	WORD $0x0005a707    // flw	fa4, 0(a1)
	WORD $0x08e7f7d3    // fsub.s	fa5, fa5, fa4
	WORD $0x00f6a027    // fsw	fa5, 0(a3)
	WORD $0x00468693    // addi	a3, a3, 4
	WORD $0x00458593    // addi	a1, a1, 4
	WORD $0x00450513    // addi	a0, a0, 4
	BNE  A3, A2, LBB7_6

LBB7_7:
	RET

LBB7_8:
	WORD $0x00181793    // slli	a5, a6, 1
	WORD $0x40a602b3    // sub	t0, a2, a0
	WORD $0x00000713    // li	a4, 0
	BLTU T0, A5, LBB7_5
	WORD $0x40b602b3    // sub	t0, a2, a1
	BLTU T0, A5, LBB7_5
	WORD $0x41100733    // neg	a4, a7
	WORD $0x00e6f733    // and	a4, a3, a4
	WORD $0x411702b3    // sub	t0, a4, a7
	WORD $0x0312d8b3    // divu	a7, t0, a7
	WORD $0x00385813    // srli	a6, a6, 3
	WORD $0x00489893    // slli	a7, a7, 4
	WORD $0x01088893    // addi	a7, a7, 16
	WORD $0x03088833    // mul	a6, a7, a6
	WORD $0x01060833    // add	a6, a2, a6
	WORD $0x00050893    // mv	a7, a0
	WORD $0x00058293    // mv	t0, a1
	WORD $0x00060313    // mv	t1, a2
	WORD $0x0d1073d7    // vsetvli	t2, zero, e32, m2, ta, ma

LBB7_11:
	WORD $0x2288e407     // vl2re32.v	v8, (a7)
	WORD $0x2282e507     // vl2re32.v	v10, (t0)
	WORD $0x0a851457     // vfsub.vv	v8, v8, v10
	WORD $0x22830427     // vs2r.v	v8, (t1)
	WORD $0x00f30333     // add	t1, t1, a5
	WORD $0x00f282b3     // add	t0, t0, a5
	WORD $0x00f888b3     // add	a7, a7, a5
	BNE  T1, A6, LBB7_11
	BNE  A3, A4, LBB7_5
	JMP  LBB7_7

TEXT ·vsub(SB), $0-24
	MOV  a+0(FP), A0
	MOV  b+8(FP), A1
	MOV  n+16(FP), A2
	BLEZ A2, LBB8_9
	WORD $0xc22027f3    // csrr	a5, vlenb
	WORD $0x0017d813    // srli	a6, a5, 1
	WORD $0x01000693    // li	a3, 16
	WORD $0x00080713    // mv	a4, a6
	BLTU A3, A6, LBB8_3
	WORD $0x01000713    // li	a4, 16

LBB8_3:
	WORD $0x00261693     // slli	a3, a2, 2
	BLTU A2, A4, LBB8_6
	WORD $0x00d58733     // add	a4, a1, a3
	BGEU A0, A4, LBB8_10
	WORD $0x00d50733     // add	a4, a0, a3
	BGEU A1, A4, LBB8_10

LBB8_6:
	WORD $0x00000713 // li	a4, 0

LBB8_7:
	WORD $0x00271713 // slli	a4, a4, 2
	WORD $0x00e50633 // add	a2, a0, a4
	WORD $0x00e585b3 // add	a1, a1, a4
	WORD $0x00d50533 // add	a0, a0, a3

LBB8_8:
	WORD $0x0005a787    // flw	fa5, 0(a1)
	WORD $0x00062707    // flw	fa4, 0(a2)
	WORD $0x08f777d3    // fsub.s	fa5, fa4, fa5
	WORD $0x00f62027    // fsw	fa5, 0(a2)
	WORD $0x00460613    // addi	a2, a2, 4
	WORD $0x00458593    // addi	a1, a1, 4
	BNE  A2, A0, LBB8_8

LBB8_9:
	RET

LBB8_10:
	WORD $0x41000733 // neg	a4, a6
	WORD $0x00e67733 // and	a4, a2, a4
	WORD $0x410708b3 // sub	a7, a4, a6
	WORD $0x0308d833 // divu	a6, a7, a6
	WORD $0x0037d893 // srli	a7, a5, 3
	WORD $0x00489793 // slli	a5, a7, 4
	WORD $0x00481813 // slli	a6, a6, 4
	WORD $0x01080813 // addi	a6, a6, 16
	WORD $0x03180833 // mul	a6, a6, a7
	WORD $0x01050833 // add	a6, a0, a6
	WORD $0x00058893 // mv	a7, a1
	WORD $0x00050293 // mv	t0, a0
	WORD $0x0d107357 // vsetvli	t1, zero, e32, m2, ta, ma

LBB8_11:
	WORD $0x2288e407     // vl2re32.v	v8, (a7)
	WORD $0x2282e507     // vl2re32.v	v10, (t0)
	WORD $0x0aa41457     // vfsub.vv	v8, v10, v8
	WORD $0x22828427     // vs2r.v	v8, (t0)
	WORD $0x00f282b3     // add	t0, t0, a5
	WORD $0x00f888b3     // add	a7, a7, a5
	BNE  T0, A6, LBB8_11
	BEQ  A2, A4, LBB8_9
	JMP  LBB8_7

TEXT ·vmul_to(SB), $0-32
	MOV  a+0(FP), A0
	MOV  b+8(FP), A1
	MOV  c+16(FP), A2
	MOV  n+24(FP), A3
	BLEZ A3, LBB9_7
	WORD $0xc2202873    // csrr	a6, vlenb
	WORD $0x00185893    // srli	a7, a6, 1
	WORD $0x01000793    // li	a5, 16
	WORD $0x00088713    // mv	a4, a7
	BLTU A5, A7, LBB9_3
	WORD $0x01000713    // li	a4, 16

LBB9_3:
	BGEU A3, A4, LBB9_8
	WORD $0x00000713    // li	a4, 0

LBB9_5:
	WORD $0x00271713 // slli	a4, a4, 2
	WORD $0x00269793 // slli	a5, a3, 2
	WORD $0x00e606b3 // add	a3, a2, a4
	WORD $0x00e585b3 // add	a1, a1, a4
	WORD $0x00e50533 // add	a0, a0, a4
	WORD $0x00f60633 // add	a2, a2, a5

LBB9_6:
	WORD $0x00052787    // flw	fa5, 0(a0)
	WORD $0x0005a707    // flw	fa4, 0(a1)
	WORD $0x10e7f7d3    // fmul.s	fa5, fa5, fa4
	WORD $0x00f6a027    // fsw	fa5, 0(a3)
	WORD $0x00468693    // addi	a3, a3, 4
	WORD $0x00458593    // addi	a1, a1, 4
	WORD $0x00450513    // addi	a0, a0, 4
	BNE  A3, A2, LBB9_6

LBB9_7:
	RET

LBB9_8:
	WORD $0x00181793    // slli	a5, a6, 1
	WORD $0x40a602b3    // sub	t0, a2, a0
	WORD $0x00000713    // li	a4, 0
	BLTU T0, A5, LBB9_5
	WORD $0x40b602b3    // sub	t0, a2, a1
	BLTU T0, A5, LBB9_5
	WORD $0x41100733    // neg	a4, a7
	WORD $0x00e6f733    // and	a4, a3, a4
	WORD $0x411702b3    // sub	t0, a4, a7
	WORD $0x0312d8b3    // divu	a7, t0, a7
	WORD $0x00385813    // srli	a6, a6, 3
	WORD $0x00489893    // slli	a7, a7, 4
	WORD $0x01088893    // addi	a7, a7, 16
	WORD $0x03088833    // mul	a6, a7, a6
	WORD $0x01060833    // add	a6, a2, a6
	WORD $0x00050893    // mv	a7, a0
	WORD $0x00058293    // mv	t0, a1
	WORD $0x00060313    // mv	t1, a2
	WORD $0x0d1073d7    // vsetvli	t2, zero, e32, m2, ta, ma

LBB9_11:
	WORD $0x2288e407     // vl2re32.v	v8, (a7)
	WORD $0x2282e507     // vl2re32.v	v10, (t0)
	WORD $0x92851457     // vfmul.vv	v8, v8, v10
	WORD $0x22830427     // vs2r.v	v8, (t1)
	WORD $0x00f30333     // add	t1, t1, a5
	WORD $0x00f282b3     // add	t0, t0, a5
	WORD $0x00f888b3     // add	a7, a7, a5
	BNE  T1, A6, LBB9_11
	BNE  A3, A4, LBB9_5
	JMP  LBB9_7

TEXT ·vdiv_to(SB), $0-32
	MOV  a+0(FP), A0
	MOV  b+8(FP), A1
	MOV  c+16(FP), A2
	MOV  n+24(FP), A3
	BLEZ A3, LBB10_7
	WORD $0xc2202873     // csrr	a6, vlenb
	WORD $0x00185893     // srli	a7, a6, 1
	WORD $0x01000793     // li	a5, 16
	WORD $0x00088713     // mv	a4, a7
	BLTU A5, A7, LBB10_3
	WORD $0x01000713     // li	a4, 16

LBB10_3:
	BGEU A3, A4, LBB10_8
	WORD $0x00000713     // li	a4, 0

LBB10_5:
	WORD $0x00271713 // slli	a4, a4, 2
	WORD $0x00269793 // slli	a5, a3, 2
	WORD $0x00e606b3 // add	a3, a2, a4
	WORD $0x00e585b3 // add	a1, a1, a4
	WORD $0x00e50533 // add	a0, a0, a4
	WORD $0x00f60633 // add	a2, a2, a5

LBB10_6:
	WORD $0x00052787     // flw	fa5, 0(a0)
	WORD $0x0005a707     // flw	fa4, 0(a1)
	WORD $0x18e7f7d3     // fdiv.s	fa5, fa5, fa4
	WORD $0x00f6a027     // fsw	fa5, 0(a3)
	WORD $0x00468693     // addi	a3, a3, 4
	WORD $0x00458593     // addi	a1, a1, 4
	WORD $0x00450513     // addi	a0, a0, 4
	BNE  A3, A2, LBB10_6

LBB10_7:
	RET

LBB10_8:
	WORD $0x00181793     // slli	a5, a6, 1
	WORD $0x40a602b3     // sub	t0, a2, a0
	WORD $0x00000713     // li	a4, 0
	BLTU T0, A5, LBB10_5
	WORD $0x40b602b3     // sub	t0, a2, a1
	BLTU T0, A5, LBB10_5
	WORD $0x41100733     // neg	a4, a7
	WORD $0x00e6f733     // and	a4, a3, a4
	WORD $0x411702b3     // sub	t0, a4, a7
	WORD $0x0312d8b3     // divu	a7, t0, a7
	WORD $0x00385813     // srli	a6, a6, 3
	WORD $0x00489893     // slli	a7, a7, 4
	WORD $0x01088893     // addi	a7, a7, 16
	WORD $0x03088833     // mul	a6, a7, a6
	WORD $0x01060833     // add	a6, a2, a6
	WORD $0x00050893     // mv	a7, a0
	WORD $0x00058293     // mv	t0, a1
	WORD $0x00060313     // mv	t1, a2
	WORD $0x0d1073d7     // vsetvli	t2, zero, e32, m2, ta, ma

LBB10_11:
	WORD $0x2288e407      // vl2re32.v	v8, (a7)
	WORD $0x2282e507      // vl2re32.v	v10, (t0)
	WORD $0x82851457      // vfdiv.vv	v8, v8, v10
	WORD $0x22830427      // vs2r.v	v8, (t1)
	WORD $0x00f30333      // add	t1, t1, a5
	WORD $0x00f282b3      // add	t0, t0, a5
	WORD $0x00f888b3      // add	a7, a7, a5
	BNE  T1, A6, LBB10_11
	BNE  A3, A4, LBB10_5
	JMP  LBB10_7

TEXT ·vsqrt_to(SB), $0-24
	MOV  a+0(FP), A0
	MOV  b+8(FP), A1
	MOV  n+16(FP), A2
	BLEZ A2, LBB11_2

LBB11_1:
	WORD $0x0d0676d7 // vsetvli	a3, a2, e32, m1, ta, ma
	WORD $0x02056407 // vle32.v	v8, (a0)
	WORD $0x4e801457 // vfsqrt.v	v8, v8
	WORD $0x00269713 // slli	a4, a3, 2
	WORD $0x40d60633 // sub	a2, a2, a3
	WORD $0x00e50533 // add	a0, a0, a4
	WORD $0x0205e427 // vse32.v	v8, (a1)
	WORD $0x00e585b3 // add	a1, a1, a4
	BGTZ A2, LBB11_1

LBB11_2:
	RET

TEXT ·vdot(SB), $8-24
	MOV  a+0(FP), A0
	MOV  b+8(FP), A1
	MOV  n+16(FP), A2
	WORD $0x0d0076d7  // vsetvli	a3, zero, e32, m1, ta, ma
	WORD $0x02d65733  // divu	a4, a2, a3
	WORD $0x0007079b  // sext.w	a5, a4
	WORD $0x5e003457  // vmv.v.i	v8, 0
	BLEZ A5, LBB12_3
	WORD $0x00000813  // li	a6, 0
	WORD $0x00269893  // slli	a7, a3, 2
	WORD $0x9e8034d7  // vmv1r.v	v9, v8

LBB12_2:
	WORD $0x02056507     // vle32.v	v10, (a0)
	WORD $0x0205e587     // vle32.v	v11, (a1)
	WORD $0x0018081b     // addiw	a6, a6, 1
	WORD $0x01150533     // add	a0, a0, a7
	WORD $0xb2a594d7     // vfmacc.vv	v9, v11, v10
	WORD $0x011585b3     // add	a1, a1, a7
	BLT  A6, A5, LBB12_2
	JMP  LBB12_4

LBB12_3:
	WORD $0x9e8034d7 // vmv1r.v	v9, v8

LBB12_4:
	WORD $0x02d706b3        // mul	a3, a4, a3
	WORD $0x40d60633        // sub	a2, a2, a3
	WORD $0x0d067057        // vsetvli	zero, a2, e32, m1, ta, ma
	WORD $0x02056507        // vle32.v	v10, (a0)
	WORD $0x0205e587        // vle32.v	v11, (a1)
	WORD $0x0d007557        // vsetvli	a0, zero, e32, m1, ta, ma
	WORD $0x0e941457        // vfredosum.vs	v8, v9, v8
	WORD $0x0d067057        // vsetvli	zero, a2, e32, m1, ta, ma
	WORD $0x92a594d7        // vfmul.vv	v9, v10, v11
	WORD $0x0e941457        // vfredosum.vs	v8, v9, v8
	WORD $0x42801557        // vfmv.f.s	fa0, v8
	MOVF FA0, result+24(FP)
	RET

TEXT ·veuclidean(SB), $8-24
	MOV  a+0(FP), A0
	MOV  b+8(FP), A1
	MOV  n+16(FP), A2
	WORD $0x0d0076d7  // vsetvli	a3, zero, e32, m1, ta, ma
	WORD $0x02d65733  // divu	a4, a2, a3
	WORD $0x0007079b  // sext.w	a5, a4
	WORD $0x5e003457  // vmv.v.i	v8, 0
	BLEZ A5, LBB13_3
	WORD $0x00000813  // li	a6, 0
	WORD $0x00269893  // slli	a7, a3, 2
	WORD $0x9e8034d7  // vmv1r.v	v9, v8

LBB13_2:
	WORD $0x02056507     // vle32.v	v10, (a0)
	WORD $0x0205e587     // vle32.v	v11, (a1)
	WORD $0x0018081b     // addiw	a6, a6, 1
	WORD $0x01150533     // add	a0, a0, a7
	WORD $0x0aa59557     // vfsub.vv	v10, v10, v11
	WORD $0xb2a514d7     // vfmacc.vv	v9, v10, v10
	WORD $0x011585b3     // add	a1, a1, a7
	BLT  A6, A5, LBB13_2
	JMP  LBB13_4

LBB13_3:
	WORD $0x9e8034d7 // vmv1r.v	v9, v8

LBB13_4:
	WORD $0x02d706b3        // mul	a3, a4, a3
	WORD $0x40d60633        // sub	a2, a2, a3
	WORD $0x0d067057        // vsetvli	zero, a2, e32, m1, ta, ma
	WORD $0x02056507        // vle32.v	v10, (a0)
	WORD $0x0205e587        // vle32.v	v11, (a1)
	WORD $0x0d007557        // vsetvli	a0, zero, e32, m1, ta, ma
	WORD $0x0e941457        // vfredosum.vs	v8, v9, v8
	WORD $0x0d067057        // vsetvli	zero, a2, e32, m1, ta, ma
	WORD $0x0aa594d7        // vfsub.vv	v9, v10, v11
	WORD $0x929494d7        // vfmul.vv	v9, v9, v9
	WORD $0x0e941457        // vfredosum.vs	v8, v9, v8
	WORD $0x0d007557        // vsetvli	a0, zero, e32, m1, ta, ma
	WORD $0x4e801457        // vfsqrt.v	v8, v8
	WORD $0x42801557        // vfmv.f.s	fa0, v8
	MOVF FA0, result+24(FP)
	RET

TEXT ·vmm(SB), $0-88
	MOVB transA+0(FP), A0
	MOVB transB+1(FP), A1
	MOV  m+8(FP), A2
	MOV  n+16(FP), A3
	MOV  k+24(FP), A4
	MOV  a+32(FP), A5
	MOV  lda+40(FP), A6
	MOV  b+48(FP), A7
	ADDI -24, SP, SP
	MOV  ldb+80(FP), T0
	MOV  T0, 0(SP)
	MOV  c+88(FP), T0
	MOV  T0, 8(SP)
	MOV  ldc+96(FP), T0
	MOV  T0, 16(SP)
	WORD $0xf8010113      // addi	sp, sp, -128
	WORD $0x06113c23      // sd	ra, 120(sp)                     # 8-byte Folded Spill
	WORD $0x06813823      // sd	s0, 112(sp)                     # 8-byte Folded Spill
	WORD $0x06913423      // sd	s1, 104(sp)                     # 8-byte Folded Spill
	WORD $0x07213023      // sd	s2, 96(sp)                      # 8-byte Folded Spill
	WORD $0x05313c23      // sd	s3, 88(sp)                      # 8-byte Folded Spill
	WORD $0x05413823      // sd	s4, 80(sp)                      # 8-byte Folded Spill
	WORD $0x05513423      // sd	s5, 72(sp)                      # 8-byte Folded Spill
	WORD $0x05613023      // sd	s6, 64(sp)                      # 8-byte Folded Spill
	WORD $0x03713c23      // sd	s7, 56(sp)                      # 8-byte Folded Spill
	WORD $0x03813823      // sd	s8, 48(sp)                      # 8-byte Folded Spill
	WORD $0x03913423      // sd	s9, 40(sp)                      # 8-byte Folded Spill
	WORD $0x03a13023      // sd	s10, 32(sp)                     # 8-byte Folded Spill
	WORD $0x00c13823      // sd	a2, 16(sp)                      # 8-byte Folded Spill
	WORD $0x09013303      // ld	t1, 144(sp)
	WORD $0x08813603      // ld	a2, 136(sp)
	WORD $0x00c13c23      // sd	a2, 24(sp)                      # 8-byte Folded Spill
	WORD $0x08013383      // ld	t2, 128(sp)
	BNEZ A0, LBB14_18
	BNEZ A1, LBB14_18
	WORD $0x01013503      // ld	a0, 16(sp)                      # 8-byte Folded Reload
	BLEZ A0, LBB14_63
	BLEZ A4, LBB14_63
	BLEZ A3, LBB14_63
	WORD $0x00269f13      // slli	t5, a3, 2
	WORD $0x00271f93      // slli	t6, a4, 2
	WORD $0xfff70513      // addi	a0, a4, -1
	WORD $0xc2202473      // csrr	s0, vlenb
	WORD $0x02a385b3      // mul	a1, t2, a0
	WORD $0x00145513      // srli	a0, s0, 1
	WORD $0x00d585b3      // add	a1, a1, a3
	WORD $0x00800e13      // li	t3, 8
	WORD $0x00259e93      // slli	t4, a1, 2
	WORD $0x00050293      // mv	t0, a0
	BLTU T3, A0, LBB14_7
	WORD $0x00800293      // li	t0, 8

LBB14_7:
	WORD $0x00000593 // li	a1, 0
	WORD $0x00231313 // slli	t1, t1, 2
	WORD $0x00281e13 // slli	t3, a6, 2
	WORD $0x01d88eb3 // add	t4, a7, t4
	WORD $0x01813a03 // ld	s4, 24(sp)                      # 8-byte Folded Reload
	WORD $0x01ea0f33 // add	t5, s4, t5
	WORD $0x01f78fb3 // add	t6, a5, t6
	WORD $0x00100993 // li	s3, 1
	WORD $0x00141413 // slli	s0, s0, 1
	WORD $0x00239493 // slli	s1, t2, 2
	WORD $0x0056b933 // sltu	s2, a3, t0
	WORD $0x40a002b3 // neg	t0, a0
	WORD $0x03d99993 // slli	s3, s3, 61
	WORD $0x0133f3b3 // and	t2, t2, s3
	WORD $0x007033b3 // snez	t2, t2
	WORD $0x0056f9b3 // and	s3, a3, t0
	JMP  LBB14_9

LBB14_8:
	WORD $0x00158593      // addi	a1, a1, 1
	WORD $0x006a0a33      // add	s4, s4, t1
	WORD $0x01013603      // ld	a2, 16(sp)                      # 8-byte Folded Reload
	BEQ  A1, A2, LBB14_63

LBB14_9:
	WORD $0x00000a93 // li	s5, 0
	WORD $0x02b302b3 // mul	t0, t1, a1
	WORD $0x02be0b33 // mul	s6, t3, a1
	WORD $0x01813b83 // ld	s7, 24(sp)                      # 8-byte Folded Reload
	WORD $0x005b8bb3 // add	s7, s7, t0
	WORD $0x005f02b3 // add	t0, t5, t0
	WORD $0x01678c33 // add	s8, a5, s6
	WORD $0x016f8b33 // add	s6, t6, s6
	WORD $0x016bbb33 // sltu	s6, s7, s6
	WORD $0x005c3c33 // sltu	s8, s8, t0
	WORD $0x018b7c33 // and	s8, s6, s8
	WORD $0x03058b33 // mul	s6, a1, a6
	WORD $0x002b1b13 // slli	s6, s6, 2
	WORD $0x01678b33 // add	s6, a5, s6
	WORD $0x01dbbbb3 // sltu	s7, s7, t4
	WORD $0x0058b2b3 // sltu	t0, a7, t0
	WORD $0x005bf2b3 // and	t0, s7, t0
	WORD $0x0072e2b3 // or	t0, t0, t2
	WORD $0x01896bb3 // or	s7, s2, s8
	WORD $0x005be2b3 // or	t0, s7, t0
	WORD $0x0012fb93 // andi	s7, t0, 1
	WORD $0x00088c13 // mv	s8, a7
	JMP  LBB14_11

LBB14_10:
	WORD $0x001a8a93     // addi	s5, s5, 1
	WORD $0x009c0c33     // add	s8, s8, s1
	BEQ  S5, A4, LBB14_8

LBB14_11:
	WORD $0x002a9c93  // slli	s9, s5, 2
	WORD $0x019b0cb3  // add	s9, s6, s9
	BEQZ S7, LBB14_13
	WORD $0x00000293  // li	t0, 0
	JMP  LBB14_16

LBB14_13:
	WORD $0x000ca787 // flw	fa5, 0(s9)
	WORD $0x000c0293 // mv	t0, s8
	WORD $0x000a0d13 // mv	s10, s4
	WORD $0x00098093 // mv	ra, s3
	WORD $0x0d107657 // vsetvli	a2, zero, e32, m2, ta, ma

LBB14_14:
	WORD $0x2282e407      // vl2re32.v	v8, (t0)
	WORD $0x228d6507      // vl2re32.v	v10, (s10)
	WORD $0x40a080b3      // sub	ra, ra, a0
	WORD $0xb287d557      // vfmacc.vf	v10, fa5, v8
	WORD $0x228d0527      // vs2r.v	v10, (s10)
	WORD $0x008d0d33      // add	s10, s10, s0
	WORD $0x008282b3      // add	t0, t0, s0
	BNEZ RA, LBB14_14
	WORD $0x00098293      // mv	t0, s3
	BEQ  A3, S3, LBB14_10

LBB14_16:
	WORD $0x00229093 // slli	ra, t0, 2
	WORD $0x001c0d33 // add	s10, s8, ra
	WORD $0x001a00b3 // add	ra, s4, ra
	WORD $0x405682b3 // sub	t0, a3, t0

LBB14_17:
	WORD $0x000ca787  // flw	fa5, 0(s9)
	WORD $0x000d2707  // flw	fa4, 0(s10)
	WORD $0x0000a687  // flw	fa3, 0(ra)
	WORD $0x004d0d13  // addi	s10, s10, 4
	WORD $0xfff28293  // addi	t0, t0, -1
	WORD $0x68e7f7c3  // fmadd.s	fa5, fa5, fa4, fa3
	WORD $0x00f0a027  // fsw	fa5, 0(ra)
	WORD $0x00408093  // addi	ra, ra, 4
	BNEZ T0, LBB14_17
	JMP  LBB14_10

LBB14_18:
	WORD $0x00154293  // xori	t0, a0, 1
	BEQZ A1, LBB14_29
	BEQZ T0, LBB14_29
	WORD $0x01013503  // ld	a0, 16(sp)                      # 8-byte Folded Reload
	BLEZ A0, LBB14_63
	BLEZ A3, LBB14_63
	WORD $0x0d007e57  // vsetvli	t3, zero, e32, m1, ta, ma
	WORD $0x03c75533  // divu	a0, a4, t3
	WORD $0x5e003457  // vmv.v.i	v8, 0
	WORD $0x0005059b  // sext.w	a1, a0
	WORD $0x03c50533  // mul	a0, a0, t3
	WORD $0x40a70533  // sub	a0, a4, a0
	WORD $0x0d057057  // vsetvli	zero, a0, e32, m1, ta, ma
	BLEZ A1, LBB14_59
	WORD $0x00000713  // li	a4, 0
	WORD $0x00281813  // slli	a6, a6, 2
	WORD $0x002e1e13  // slli	t3, t3, 2
	WORD $0x00239393  // slli	t2, t2, 2

LBB14_24:
	WORD $0x00000e93 // li	t4, 0
	WORD $0x02670633 // mul	a2, a4, t1
	WORD $0x00261613 // slli	a2, a2, 2
	WORD $0x01813f03 // ld	t5, 24(sp)                      # 8-byte Folded Reload
	WORD $0x00cf0f33 // add	t5, t5, a2
	WORD $0x00088f93 // mv	t6, a7

LBB14_25:
	WORD $0x00000413 // li	s0, 0
	WORD $0x000f8493 // mv	s1, t6
	WORD $0x00078913 // mv	s2, a5
	WORD $0xcc00f057 // vsetivli	zero, 1, e8, m1, ta, ma
	WORD $0x9e8034d7 // vmv1r.v	v9, v8

LBB14_26:
	WORD $0x0d007657      // vsetvli	a2, zero, e32, m1, ta, ma
	WORD $0x02096507      // vle32.v	v10, (s2)
	WORD $0x0204e587      // vle32.v	v11, (s1)
	WORD $0x0014041b      // addiw	s0, s0, 1
	WORD $0x01c90933      // add	s2, s2, t3
	WORD $0xb2a594d7      // vfmacc.vv	v9, v11, v10
	WORD $0x01c484b3      // add	s1, s1, t3
	BLT  S0, A1, LBB14_26
	WORD $0x0e9414d7      // vfredosum.vs	v9, v9, v8
	WORD $0x0d057057      // vsetvli	zero, a0, e32, m1, ta, ma
	WORD $0x02096507      // vle32.v	v10, (s2)
	WORD $0x0204e587      // vle32.v	v11, (s1)
	WORD $0x002e9613      // slli	a2, t4, 2
	WORD $0x001e8e93      // addi	t4, t4, 1
	WORD $0x00cf0633      // add	a2, t5, a2
	WORD $0x92a59557      // vfmul.vv	v10, v10, v11
	WORD $0x0ea494d7      // vfredosum.vs	v9, v10, v9
	WORD $0xcd00f057      // vsetivli	zero, 1, e32, m1, ta, ma
	WORD $0x020664a7      // vse32.v	v9, (a2)
	WORD $0x007f8fb3      // add	t6, t6, t2
	BNE  T4, A3, LBB14_25
	WORD $0x00170713      // addi	a4, a4, 1
	WORD $0x010787b3      // add	a5, a5, a6
	WORD $0x01013603      // ld	a2, 16(sp)                      # 8-byte Folded Reload
	BNE  A4, A2, LBB14_24
	JMP  LBB14_63

LBB14_29:
	WORD $0x0055e633      // or	a2, a1, t0
	WORD $0x01013283      // ld	t0, 16(sp)                      # 8-byte Folded Reload
	WORD $0x005022b3      // sgtz	t0, t0
	WORD $0x00e02e33      // sgtz	t3, a4
	WORD $0x00d02eb3      // sgtz	t4, a3
	WORD $0x01de7e33      // and	t3, t3, t4
	WORD $0x005e72b3      // and	t0, t3, t0
	BEQZ A2, LBB14_45
	WORD $0x00b2f5b3      // and	a1, t0, a1
	BEQZ A1, LBB14_63
	BEQZ A0, LBB14_63
	WORD $0x00269f13      // slli	t5, a3, 2
	WORD $0xfff70593      // addi	a1, a4, -1
	WORD $0x00d70633      // add	a2, a4, a3
	WORD $0xc2202573      // csrr	a0, vlenb
	WORD $0x02b802b3      // mul	t0, a6, a1
	WORD $0x00261613      // slli	a2, a2, 2
	WORD $0x00155593      // srli	a1, a0, 1
	WORD $0x00229293      // slli	t0, t0, 2
	WORD $0x00c88eb3      // add	t4, a7, a2
	WORD $0x00800613      // li	a2, 8
	WORD $0x00578fb3      // add	t6, a5, t0
	WORD $0x00058293      // mv	t0, a1
	BLTU A2, A1, LBB14_34
	WORD $0x00800293      // li	t0, 8

LBB14_34:
	WORD $0x00000e13 // li	t3, 0
	WORD $0x00231313 // slli	t1, t1, 2
	WORD $0xffce8e93 // addi	t4, t4, -4
	WORD $0x01813983 // ld	s3, 24(sp)                      # 8-byte Folded Reload
	WORD $0x01e98f33 // add	t5, s3, t5
	WORD $0x004f8f93 // addi	t6, t6, 4
	WORD $0x0056b633 // sltu	a2, a3, t0
	WORD $0xfff38293 // addi	t0, t2, -1
	WORD $0x00100493 // li	s1, 1
	WORD $0x00151413 // slli	s0, a0, 1
	WORD $0x00239393 // slli	t2, t2, 2
	WORD $0xfff64613 // not	a2, a2
	WORD $0x0012b293 // seqz	t0, t0
	WORD $0x03d49493 // slli	s1, s1, 61
	WORD $0x00567633 // and	a2, a2, t0
	WORD $0x009872b3 // and	t0, a6, s1
	WORD $0x005034b3 // snez	s1, t0
	WORD $0xfff64913 // not	s2, a2
	JMP  LBB14_36

LBB14_35:
	WORD $0x001e0e13      // addi	t3, t3, 1
	WORD $0x006989b3      // add	s3, s3, t1
	WORD $0x01013603      // ld	a2, 16(sp)                      # 8-byte Folded Reload
	BEQ  T3, A2, LBB14_63

LBB14_36:
	WORD $0x00000a13 // li	s4, 0
	WORD $0x03c30633 // mul	a2, t1, t3
	WORD $0x002e1293 // slli	t0, t3, 2
	WORD $0x01813b03 // ld	s6, 24(sp)                      # 8-byte Folded Reload
	WORD $0x00cb0b33 // add	s6, s6, a2
	WORD $0x00cf0633 // add	a2, t5, a2
	WORD $0x00578ab3 // add	s5, a5, t0
	WORD $0x005f82b3 // add	t0, t6, t0
	WORD $0x005b32b3 // sltu	t0, s6, t0
	WORD $0x00cabbb3 // sltu	s7, s5, a2
	WORD $0x0172f2b3 // and	t0, t0, s7
	WORD $0x01db3b33 // sltu	s6, s6, t4
	WORD $0x00c8b633 // sltu	a2, a7, a2
	WORD $0x00cb7633 // and	a2, s6, a2
	WORD $0x0092e2b3 // or	t0, t0, s1
	WORD $0x00c96633 // or	a2, s2, a2
	WORD $0x00566633 // or	a2, a2, t0
	WORD $0x00167b13 // andi	s6, a2, 1
	WORD $0x00088b93 // mv	s7, a7
	JMP  LBB14_38

LBB14_37:
	WORD $0x001a0a13      // addi	s4, s4, 1
	WORD $0x004b8b93      // addi	s7, s7, 4
	BEQ  S4, A4, LBB14_35

LBB14_38:
	WORD $0x030a0633  // mul	a2, s4, a6
	WORD $0x00261613  // slli	a2, a2, 2
	WORD $0x00ca8c33  // add	s8, s5, a2
	BEQZ S6, LBB14_40
	WORD $0x00000c93  // li	s9, 0
	JMP  LBB14_43

LBB14_40:
	WORD $0x00155613 // srli	a2, a0, 1
	WORD $0x000c2787 // flw	fa5, 0(s8)
	WORD $0x40c00633 // neg	a2, a2
	WORD $0x00c6fcb3 // and	s9, a3, a2
	WORD $0x000b8293 // mv	t0, s7
	WORD $0x00098d13 // mv	s10, s3
	WORD $0x000c8093 // mv	ra, s9
	WORD $0x0d107657 // vsetvli	a2, zero, e32, m2, ta, ma

LBB14_41:
	WORD $0x2282e407      // vl2re32.v	v8, (t0)
	WORD $0x228d6507      // vl2re32.v	v10, (s10)
	WORD $0x40b080b3      // sub	ra, ra, a1
	WORD $0xb287d557      // vfmacc.vf	v10, fa5, v8
	WORD $0x228d0527      // vs2r.v	v10, (s10)
	WORD $0x008d0d33      // add	s10, s10, s0
	WORD $0x008282b3      // add	t0, t0, s0
	BNEZ RA, LBB14_41
	BEQ  A3, S9, LBB14_37

LBB14_43:
	WORD $0x03938d33 // mul	s10, t2, s9
	WORD $0x002c9293 // slli	t0, s9, 2
	WORD $0x01ab8d33 // add	s10, s7, s10
	WORD $0x005982b3 // add	t0, s3, t0
	WORD $0x41968cb3 // sub	s9, a3, s9

LBB14_44:
	WORD $0x000c2787  // flw	fa5, 0(s8)
	WORD $0x000d2707  // flw	fa4, 0(s10)
	WORD $0x0002a687  // flw	fa3, 0(t0)
	WORD $0x007d0d33  // add	s10, s10, t2
	WORD $0xfffc8c93  // addi	s9, s9, -1
	WORD $0x68e7f7c3  // fmadd.s	fa5, fa5, fa4, fa3
	WORD $0x00f2a027  // fsw	fa5, 0(t0)
	WORD $0x00428293  // addi	t0, t0, 4
	BNEZ S9, LBB14_44
	JMP  LBB14_37

LBB14_45:
	BEQZ T0, LBB14_63
	WORD $0x00269f13      // slli	t5, a3, 2
	WORD $0xfff70593      // addi	a1, a4, -1
	WORD $0xc2202573      // csrr	a0, vlenb
	WORD $0x00800613      // li	a2, 8
	WORD $0x02b802b3      // mul	t0, a6, a1
	WORD $0x02b38e33      // mul	t3, t2, a1
	WORD $0x00155593      // srli	a1, a0, 1
	WORD $0x00229293      // slli	t0, t0, 2
	WORD $0x00de0e33      // add	t3, t3, a3
	WORD $0x002e1e93      // slli	t4, t3, 2
	WORD $0x00578fb3      // add	t6, a5, t0
	WORD $0x00058293      // mv	t0, a1
	BLTU A2, A1, LBB14_48
	WORD $0x00800293      // li	t0, 8

LBB14_48:
	WORD $0x00000e13 // li	t3, 0
	WORD $0x00231313 // slli	t1, t1, 2
	WORD $0x01d88eb3 // add	t4, a7, t4
	WORD $0x01d13423 // sd	t4, 8(sp)                       # 8-byte Folded Spill
	WORD $0x01813a03 // ld	s4, 24(sp)                      # 8-byte Folded Reload
	WORD $0x01ea0f33 // add	t5, s4, t5
	WORD $0x004f8f93 // addi	t6, t6, 4
	WORD $0x00100613 // li	a2, 1
	WORD $0x00151413 // slli	s0, a0, 1
	WORD $0x00239493 // slli	s1, t2, 2
	WORD $0x03d61613 // slli	a2, a2, 61
	WORD $0x00c87eb3 // and	t4, a6, a2
	WORD $0x00c3f633 // and	a2, t2, a2
	WORD $0x00c033b3 // snez	t2, a2
	WORD $0x01d03933 // snez	s2, t4
	WORD $0x0056b9b3 // sltu	s3, a3, t0
	WORD $0x000a0293 // mv	t0, s4
	JMP  LBB14_50

LBB14_49:
	WORD $0x001e0e13      // addi	t3, t3, 1
	WORD $0x006282b3      // add	t0, t0, t1
	WORD $0x01013603      // ld	a2, 16(sp)                      # 8-byte Folded Reload
	BEQ  T3, A2, LBB14_63

LBB14_50:
	WORD $0x00000a93 // li	s5, 0
	WORD $0x03c30633 // mul	a2, t1, t3
	WORD $0x002e1e93 // slli	t4, t3, 2
	WORD $0x01813a03 // ld	s4, 24(sp)                      # 8-byte Folded Reload
	WORD $0x00ca0a33 // add	s4, s4, a2
	WORD $0x00cf0633 // add	a2, t5, a2
	WORD $0x01d78b33 // add	s6, a5, t4
	WORD $0x01df8eb3 // add	t4, t6, t4
	WORD $0x01da3eb3 // sltu	t4, s4, t4
	WORD $0x00cb3bb3 // sltu	s7, s6, a2
	WORD $0x017efeb3 // and	t4, t4, s7
	WORD $0x00813b83 // ld	s7, 8(sp)                       # 8-byte Folded Reload
	WORD $0x017a3a33 // sltu	s4, s4, s7
	WORD $0x00c8b633 // sltu	a2, a7, a2
	WORD $0x00ca7633 // and	a2, s4, a2
	WORD $0x012eeeb3 // or	t4, t4, s2
	WORD $0x00766633 // or	a2, a2, t2
	WORD $0x00cee633 // or	a2, t4, a2
	WORD $0x00c9e633 // or	a2, s3, a2
	WORD $0x00167b93 // andi	s7, a2, 1
	WORD $0x00088c13 // mv	s8, a7
	JMP  LBB14_52

LBB14_51:
	WORD $0x001a8a93      // addi	s5, s5, 1
	WORD $0x009c0c33      // add	s8, s8, s1
	BEQ  S5, A4, LBB14_49

LBB14_52:
	WORD $0x030a8633  // mul	a2, s5, a6
	WORD $0x00261613  // slli	a2, a2, 2
	WORD $0x00cb0cb3  // add	s9, s6, a2
	BEQZ S7, LBB14_54
	WORD $0x00000e93  // li	t4, 0
	JMP  LBB14_57

LBB14_54:
	WORD $0x00155613 // srli	a2, a0, 1
	WORD $0x000ca787 // flw	fa5, 0(s9)
	WORD $0x40c00633 // neg	a2, a2
	WORD $0x00c6feb3 // and	t4, a3, a2
	WORD $0x000c0a13 // mv	s4, s8
	WORD $0x00028093 // mv	ra, t0
	WORD $0x000e8d13 // mv	s10, t4
	WORD $0x0d107657 // vsetvli	a2, zero, e32, m2, ta, ma

LBB14_55:
	WORD $0x228a6407      // vl2re32.v	v8, (s4)
	WORD $0x2280e507      // vl2re32.v	v10, (ra)
	WORD $0x40bd0d33      // sub	s10, s10, a1
	WORD $0xb287d557      // vfmacc.vf	v10, fa5, v8
	WORD $0x22808527      // vs2r.v	v10, (ra)
	WORD $0x008080b3      // add	ra, ra, s0
	WORD $0x008a0a33      // add	s4, s4, s0
	BNEZ S10, LBB14_55
	BEQ  A3, T4, LBB14_51

LBB14_57:
	WORD $0x002e9a13 // slli	s4, t4, 2
	WORD $0x014c00b3 // add	ra, s8, s4
	WORD $0x01428a33 // add	s4, t0, s4
	WORD $0x41d68d33 // sub	s10, a3, t4

LBB14_58:
	WORD $0x000ca787   // flw	fa5, 0(s9)
	WORD $0x0000a707   // flw	fa4, 0(ra)
	WORD $0x000a2687   // flw	fa3, 0(s4)
	WORD $0x00408093   // addi	ra, ra, 4
	WORD $0xfffd0d13   // addi	s10, s10, -1
	WORD $0x68e7f7c3   // fmadd.s	fa5, fa5, fa4, fa3
	WORD $0x00fa2027   // fsw	fa5, 0(s4)
	WORD $0x004a0a13   // addi	s4, s4, 4
	BNEZ S10, LBB14_58
	JMP  LBB14_51

LBB14_59:
	WORD $0x00000593 // li	a1, 0
	WORD $0x0d007657 // vsetvli	a2, zero, e32, m1, ta, ma
	WORD $0x0e841457 // vfredosum.vs	v8, v8, v8
	WORD $0x00239393 // slli	t2, t2, 2
	WORD $0x00231313 // slli	t1, t1, 2

LBB14_60:
	WORD $0x03058633 // mul	a2, a1, a6
	WORD $0x00261613 // slli	a2, a2, 2
	WORD $0x00c78733 // add	a4, a5, a2
	WORD $0x00068e13 // mv	t3, a3
	WORD $0x01813e83 // ld	t4, 24(sp)                      # 8-byte Folded Reload
	WORD $0x00088293 // mv	t0, a7

LBB14_61:
	WORD $0x0d057057      // vsetvli	zero, a0, e32, m1, ta, ma
	WORD $0x02076487      // vle32.v	v9, (a4)
	WORD $0x0202e507      // vle32.v	v10, (t0)
	WORD $0x007282b3      // add	t0, t0, t2
	WORD $0xfffe0e13      // addi	t3, t3, -1
	WORD $0x929514d7      // vfmul.vv	v9, v9, v10
	WORD $0x0e9414d7      // vfredosum.vs	v9, v9, v8
	WORD $0xcd00f057      // vsetivli	zero, 1, e32, m1, ta, ma
	WORD $0x020ee4a7      // vse32.v	v9, (t4)
	WORD $0x004e8e93      // addi	t4, t4, 4
	BNEZ T3, LBB14_61
	WORD $0x00158593      // addi	a1, a1, 1
	WORD $0x01813603      // ld	a2, 24(sp)                      # 8-byte Folded Reload
	WORD $0x00660633      // add	a2, a2, t1
	WORD $0x00c13c23      // sd	a2, 24(sp)                      # 8-byte Folded Spill
	WORD $0x01013603      // ld	a2, 16(sp)                      # 8-byte Folded Reload
	BNE  A1, A2, LBB14_60

LBB14_63:
	WORD $0x07813083 // ld	ra, 120(sp)                     # 8-byte Folded Reload
	WORD $0x07013403 // ld	s0, 112(sp)                     # 8-byte Folded Reload
	WORD $0x06813483 // ld	s1, 104(sp)                     # 8-byte Folded Reload
	WORD $0x06013903 // ld	s2, 96(sp)                      # 8-byte Folded Reload
	WORD $0x05813983 // ld	s3, 88(sp)                      # 8-byte Folded Reload
	WORD $0x05013a03 // ld	s4, 80(sp)                      # 8-byte Folded Reload
	WORD $0x04813a83 // ld	s5, 72(sp)                      # 8-byte Folded Reload
	WORD $0x04013b03 // ld	s6, 64(sp)                      # 8-byte Folded Reload
	WORD $0x03813b83 // ld	s7, 56(sp)                      # 8-byte Folded Reload
	WORD $0x03013c03 // ld	s8, 48(sp)                      # 8-byte Folded Reload
	WORD $0x02813c83 // ld	s9, 40(sp)                      # 8-byte Folded Reload
	WORD $0x02013d03 // ld	s10, 32(sp)                     # 8-byte Folded Reload
	WORD $0x08010113 // addi	sp, sp, 128
	ADDI 24, SP, SP
	RET
